### ISSUE TITLE
Implement a as(xcmsSet) for XCMSnExp

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#100]
Implement a function/method to coerce an `XCMSnExp` to an `xcmsSet`.

**Comment by 13479776** [comment]
When i use the 'as' function, An error was happened as following, "Error in chromPeaks(from)[, "is_filled"] : subscript out of bounds".   I dont know how to do it.

**Comment by sneumann** [comment]
Hi, could you add a new issue for your issue ? We'll also need your `traceback()` to locate the error and `sessionInfo()` for the versions used. Yours, Steffen

**Comment by 13479776** [comment]
Hi steffen. I think i got the keys. I use the XCMS V3.6.1 to produce the XCMSnEXp. The chromPeaks function from V3.5.1 could not process the XCMSnEXp rightly.
