### ISSUE TITLE
Should it error on no scales?

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#102]
Should this be a warning and return no peaks instead:
https://github.com/sneumann/xcms/blob/647e2f9c5fc7e6ea40d839c9846b07d668a95f0d/R/do_detectFeatures-functions.R#L179

**Comment by jotsetung** [comment]
Makes sense. I'll fix.

**Comment by jotsetung** [comment]
Will also be fixed once `xcms3` is next merged into `devel`.

**Comment by jotsetung** [comment]
OK - it's in xcms version 1.51.6
