### ISSUE TITLE
Error on tokay2 Bioconductor build machine

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#118]
We get the error:
```
Last 13 lines of output:
  1 Test Suite : 
  xcms unit testing - 131 test functions, 0 errors, 1 failure
  FAILURE in test_breaks: Error in checkIdentical(res, seq(2, 8, length.out = 21)) : FALSE 
   
  Error: 
  
  unit testing failed (#test failures: 1, #R errors: 0)
```
on the Windows build machine for xcms 1.51.4

**Comment by jotsetung** [comment]
I guess this has something to do with floating point precision as I'm using `checkIdentical` there.

**Comment by jotsetung** [comment]
OK, whether this works has to be evaluated next time xcms3 is merged into devel and that is checked on the Bioconductor Windows test machine - chances are high that it works now.

**Comment by jotsetung** [comment]
OK, could also be a problem with the server itself - according to a email from Valerie Obenchain (2017-01-30) tokay2 has problems.

**Comment by sneumann** [comment]
Hi, still present in 1.51.7:
```
  FAILURE in test_breaks: Error in checkEquals(brks[cmn], brksR[cmn]) : 
    Mean relative difference: 5.64487e-07
```

**Comment by jotsetung** [comment]
That's a sneaky one. I'll set up a Windows build machine to see whether and how I can reproduce this error. For now I've disabled the one line in the unit test that causes the error.
