### ISSUE TITLE
Extract MS data subset

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#120]
The idea is to have a method/function that extracts a subset of the MS data given `rtrange` and `mzrange`. It should be something like the `getEIC` (but not extracting data from the profile matrix), `rawMat` and `rawEIC`. All 3 methods do similar stuff - in the end they should be fused to one `extractMsData` method/function (function name might be improved).

Input arguments should be:
+ `object`
+ `rtrange`
+ `mzrange`

The results object will most likely be a `list` or equivalent - or a `DataFrame`?

**Comment by sneumann** [comment]
So not return same type as object?

---
I blame Android for the brevity and typos

**Comment by jotsetung** [comment]
good point - have to think it over again. `filterRt` and `filterMz` do already exactly that.

**Comment by jotsetung** [comment]
Just to clarify:
*this extraction of MS data* should be somewhat similar to the `getEIC`, just being more generic (not extracting ) and using the new capabilities of the `XCMSnExp`/`OnDiskMSnExp` classes, i.e. read just a data subset from the raw files which can lead to an increased performance.

Along the lines, it might be eventually interesting to define a `Chromatogram` class (in analogy to `MSnbase` `Spectrum` class). Such objects might then be extracted/returned similarily to the `EIC` class.

**Comment by sneumann** [comment]
mzR has recently had some activity on adding chromatogram reading, 
but not yet available, see https://github.com/sneumann/mzR/issues/74

**Comment by jotsetung** [comment]
Thanks - have to check that.

**Comment by jotsetung** [comment]
See also issue #125

**Comment by jotsetung** [comment]
With the `extractChromatograms`, `spectra` and `extractMsData` methods there are now plenty of methods available to get access to the raw (or modified) data.
