### ISSUE TITLE
Test dataset

### ISSUE THREAD

**Issue by Babababa** [sneumann/xcms#121]
Hi,

Is there a test dataset that is available along with a test output that it should produce if following the instructions in the manual?

Thanks,

**Comment by jotsetung** [comment]
There is a test data set, yes, the `faahKO` library/data set, but no output data to compare the results to. 
Good point, this might be something we should consider to ensure that the algorithms produce the same result on all platforms.

**Comment by sneumann** [comment]
Another data set readily available is `library(mtbls2)` which corresponds 
to the paper http://link.springer.com/article/10.1007%2Fs11306-012-0401-0, 
but again without "true" values.

**Comment by Babababa** [comment]
And would it be possible to get a benchmarking dataset, including, say, 5
input files, the corresponding output files and the commands with which the
output was generated? I would really appreciate it and would acknowledge
you in my paper.

Thank you very much,
Orsolya
