### ISSUE TITLE
Define Chromatogram class

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#125]
Define a `Chromatogram` class with slots:
+ `intenstiy`: the intensity values, e.g. the `max` intensity for a retention time across the mz range (for a BPC) or `sum` (TIC).
+ `rtime`: the retention time.
+ `aggregationFun` function used to aggregate intensity values across mz range for the same retention time (e.g. `"sum"` etc).
+ `mz`: the range of the mz values.
+ `fromFile`: integer defining the index of the file (within the object from which the chromatogram was extracted). 

To create such object: extract it from an `OnDiskMSnExp` or `XCMSnExp` given a `rt` range and `mz` range.

Now, definition of this object is based on what data I've got and how I see that it can be created/extracted from an `OnDiskMSnExp` or `XCMSnExp` object - but still matter of discussion.

Note: in principle, this is sort of an extended `EIC` object.

**Comment by sneumann** [comment]
For one chromatogram we need to capture from what it came from,  e.g. An MRM transition or whatever else.

---
I blame Android for the brevity and typos

**Comment by jotsetung** [comment]
How could that be captured? Is such a `Chromatogram` related to a specific mz, or spectrum or other chromatogram?

**Comment by sneumann** [comment]
Hi, typically, this will be MRM transitions, e.g. 273->153 where is Q1 set to 273
and Q3 set to 153 in targeted metabolomics. These are stored as cvParams 
in the mzML file. 

Let's not expose that class in NAMESPACE in this devel cycle, 
to have some time to finalise the interface and try a few options.

**Comment by jotsetung** [comment]
Sorry for my dumb questions, but does this mean that in untargeted you will never have such chromatograms?

Do you have such a file or is one included already in `msdata`? 

AFAIK `MSnbase` has all data objects organized by `Spectrum`, are these mzML files organized by chromatogram instead or even a mixture of spectra and chromatograms? This would require some considerable changes...

**Comment by jotsetung** [comment]
The definition of the `Chromatogram` class above does already cover the *SIM* (selected ion monitoring), since its `mz` value (or rather the, very small, mz range) defines the ion that was monitored.

Tracking SRM (selective reaction monitoring), MRM (multiple SRM) should also be straight forward by either adding a slot `parentMz` to the original `Chromatogram` object or defining a `SRMChromatogram` extending `Chromatogram` that has this additional slot.

A MRM transition 273 > 153 could thus be represented by two `Chromatogram` objects, the first having an `@mz = c(273, 273)` and the second a `@mz = c(153, 153)` and `@parentMz = c(273, 273)`.

@sneumann do you think that might do it?

**Comment by sneumann** [comment]
Two object sounds too complicated. What about one `Chromatogram`,
with slots `@parentMz` and `@productMz` ? For SIM product could be NULL.

**Comment by jotsetung** [comment]
A, OK, so you want to go both direction, parent to product and product to parent. Yes, that's fine for me. Regarding naming convention: should the product be called `@productMz` or `@fragmentMz`?

**Comment by lgatto** [comment]
Every raw file will have a least one chromatogram. It it's a targeted experiment (MRM/SRM, `f[1]` below), it will have many more:
```r
  [list output truncated]
> f
[1] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.4/msdata/proteomics/MRM-standmix-5.mzML.gz"                                       
[2] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.4/msdata/proteomics/MS3TMT10_01022016_32917-33481.mzML.gz"                        
[3] "/home/lg390/R/x86_64-pc-linux-gnu-library/3.4/msdata/proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz"
```

In the case of a shotgun proteomics experiment, the chromatogram is the total ion count over time
```r
> x <- mzR:::openMSfile(f[2], "pwiz")
> str(chromatograms(x))
List of 1
 $ :'data.frame':	52486 obs. of  2 variables:
  ..$ time: num [1:52486] 0.00147 0.01041 0.01149 0.01251 0.01385 ...
  ..$ TIC : num [1:52486] 31682852 34179548 3711 5629 2902 ...
```

In the case of an MRM experiment the first chromatogram is the TIC
```r
> x <- mzR:::openMSfile(f[1], "pwiz")
> str(chromatograms(x, 1L))
'data.frame':	85799 obs. of  2 variables:
 $ time: num  1.67e-05 4.23e-03 8.45e-03 1.27e-02 1.69e-02 ...
 $ TIC : num  45.4 44.4 45.3 44.3 45.4 ...
```
and all the other ones are transitions
```r
> length(chromatograms(x))
[1] 138
> str(chromatograms(x, 2:5))
List of 4
 $ :'data.frame':	962 obs. of  2 variables:
  ..$ time                                                    : num [1:962] 5.21 5.22 5.23 5.24 5.25 ...
  ..$ X..SRM.SIC.Q1.89.Q3.40.996.start.5.21145.end.15.20321667: num [1:962] 42.3 42 41.5 41.3 41.1 ...
 $ :'data.frame':	962 obs. of  2 variables:
  ..$ time                                                        : num [1:962] 5.21 5.22 5.23 5.24 5.25 ...
  ..$ X..SRM.SIC.Q1.89.Q3.42.996.start.5.211116667.end.15.20308333: num [1:962] 46.7 46.3 46 45 44.8 ...
 $ :'data.frame':	523 obs. of  2 variables:
  ..$ time                                                         : num [1:523] 10.1 10.2 10.2 10.2 10.2 ...
  ..$ X..SRM.SIC.Q1.115.Q3.26.996.start.10.14841667.end.16.16721667: num [1:523] 40.9 40.9 41 41 41 ...
 $ :'data.frame':	523 obs. of  2 variables:
  ..$ time                                                         : num [1:523] 10.1 10.2 10.2 10.2 10.2 ...
  ..$ X..SRM.SIC.Q1.115.Q3.70.996.start.10.14816667.end.16.16706667: num [1:523] 42.4 43.2 44.1 44.6 45.1 ...
```

**Comment by lgatto** [comment]
I think one important accessor that is currently missing in `mzR` is to parse the CV params to get the Q1 and Q3 transitions and retention times. I didn't get any time to do that so far.

**Comment by lgatto** [comment]
I also came across this [*sRm*](https://github.com/wilsontom/sRm) package. It parses the `mzML` files manually, but good to look at and do some testing.

**Comment by jotsetung** [comment]
Nice, thanks. So I have something to play with.

**Comment by lgatto** [comment]
We also keep in mind that, at the end, we will want an array with transitions (mz, rt) intensities for multiple acquisitions (samples).

**Comment by jotsetung** [comment]
That should be covered. Check
https://github.com/sneumann/xcms/blob/xcms3/R/DataClasses.R#L2221-L2241
for its current definition. One `Chromatogram` contains the chromatogram for one file, contains the retention time (`@rtime`) and intensity values (`@intensity`) and is defined by `@fromFile` and `@mz`. This `mz` slot is actually designed to represent an mz value __range__ and not a single mz value. So, both SRM/MRM are covered (e.g. with `@mz = c(89, 89)`) as well as a TIC (e.g. `@mz = c(0, 1000)`).

Still missing is the `parentMz` and the `productMz` to link between transitions.

For a simple first approach I would put the `Chromatogram` objects into a `list`.

**Comment by lgatto** [comment]
This is something that would be also highly relevant for proteomics. Would it be worth considering moving it to `mzR`? Or it's own package?

**Comment by jotsetung** [comment]
Isn't `mzR` more the data access layer? An own package for a single object seems a little too much I believe - and what about `MSnbase`? It could live there along with the `Spectrum` classes (just *rectangular* to them).

**Comment by lgatto** [comment]
- Yes, re `mzR`, but I would also see scope for a relatively low level class to be used by multiple MS packages (metabolomics/proteomics).
- Re own package, there might be more than a single class - any processing/binning methods anticipated? This would also influence whether `mzR` is a good place.
- No problem to add it to `MSnbase`. I think we wouldn't necessarily need cross-dependencies between `MSnbase` and `xcms` because they are quite large. But `xcms` already depends on `MSnbase`, so maybe that wouldn't be a problem. We could also consider separating core MS functionality and purely proteomics stuff.

**Comment by jotsetung** [comment]
For now I would like to keep it in `xcms` a little (means 1-3 weeks at max) so that I can test stuff there and make quick changes. I didn't really anticipate for it to become such a fundamental object, just wanted to have something to put my extracted features/peaks into and represent them in rt dimension.

`MSnbase` importing stuff from `xmcs` is a no-go, because I'm already importing `MSnbase` - we would run into big circularity problems.

**Comment by jotsetung** [comment]
I've implemented now a `Chromatogram` class that should be able to handle all possible scenarios, from EIC to ion traces to SRM/MRM.

**Comment by jotsetung** [comment]
Moving the `Chromatogram` class to `MSnbase` since it is sort of an *infrastructure* type of class that will also be used in proteomics (see https://github.com/lgatto/MSnbase/issues/222)
