### ISSUE TITLE
Define a common nomenclature

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#126]
We should come to a standard nomenclature for *things* in `xcms`:

1) **peak**; peak is mostly used to describe a peak in mz; we could eventually use **chromatographic peak** for that (but not `feature`).
2) **feature**: is supposed to be the feature in the resulting matrix. This would correspond to the `group` in the old `xcms` UI and `featureGroups` in the new one.

**Comment by jotsetung** [comment]
Suggestion from @pietrofranceschi : for the new user interface and its methods: call what's called in `xcms` `group` into `features` and use the term *chromatographic peak* for what's called `peaks`, to distinguish from *mass peaks*.
OK with that @sneumann ?

**Comment by rhelmus** [comment]
Note that some other tools (Bruker DataAnalysis, OpenMS) are using the term feature to describe what comes out of their chromatographic peak finders (actually those features may also contain e.g. isotopic info). Calling grouped peaks across samples 'features' might sound a bit conflicting?

There seem to be so many names used out there to describe features across samples (feature groups, profiles, consensus, groups, ...). I actually favor feature groups to describe them.

I look forward to the day we all call it the same, but yeah what can we expect in the LC-MS/MS world :-)

**Comment by jotsetung** [comment]
Thanks for your input @rhelmus

**Comment by jotsetung** [comment]
Still, I'd like to call the aligned chromatic groups *features*. I think it's not perfect, but it seems to me that many people in LCMS are used to that nomenclature, i.e. the results coming out from the peak detection and alignment hence the output from an `xcms` run are referred to as the `features`.

**Comment by jotsetung** [comment]
+ [ ] chromatographic peak: `chromPeak`.
+ [ ] aligned (across samples) and grouped (within sample) chromatographic peaks: `features`.
+ [ ] identifying peaks in chromatographic space: `findChromPeaks`.
+ [ ] adjust retention times: `adjustRtime`.
+ [ ] correspondence/chromatographic peak alignment: `groupChromPeaks`

**Comment by jotsetung** [comment]
Done in xcms version 1.51.7
