### ISSUE TITLE
xcmsSet constructor endless loop

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#134]
Hi, `xcmsSet()` will simply never return, and allocate lots of memory

**Comment by jotsetung** [comment]
could you please provide the output from the `sessionInfo`? It might be related to `BiocParallel` on some systems.

**Comment by jotsetung** [comment]
Ah, now I got it - `xcmsSet()` without arguments. I'll fix that.

**Comment by jotsetung** [comment]
The function is scanning recursively all files and folders for CDF, mzML etc files if parameter `files` is not provided. I added a message listing the directory and all files found in them. Users thus at least know what the function is doing.
