### ISSUE TITLE
xcmsRaw using mzR backend=Ramp, so polarity wrong for mzML files (always negative)

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#143]
Hi, the mzR backend Ramp is getting polarity wrong for positive mode mzML.
xcms should use the new backed=pwiz in 
https://github.com/sneumann/xcms/blob/6e0381eef656d2f32fa8d3affabd2a9f995bfc38/R/functions-IO.R#L52

**Comment by jotsetung** [comment]
I'll fix
