### ISSUE TITLE
Create arbitrary feature ids

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#148]
`groupval` and the `groups` matrix used a combination of (rounded) mz and retention time values to build an ID for each feature. These were however not necessarily unique in a data set.

The `matrix` returned by `featureDefinitions` and `featureValues` should also have unique row names that ensure mapping between these tables, even if they are sub-setted or re-ordered.

**Comment by jotsetung** [comment]
I don't see a clear benefit of IDs build from mz-rt values over completely arbitrary IDs (as long as they can be identified as being IDs of features).
I would go for something like `FT0000123`, the `FT` indicating that it is the ID of a feature and the number being a running, unique, number. To get the definition of the feature, the user can simply go back to the `featureDefinitions` `data.frame`.

**Comment by sneumann** [comment]
So it is still easy to get labels suitable for labelling features in e.g. a PCA loadings plot ?

**Comment by jotsetung** [comment]
That should be OK. The matrix returned by `featureValues` (`groupval` in the old interface) has the file name as column name and e.g. `FT0001`, `FT0002` etc as `rownames`. Loadings would then have these names. The advantage is also that the `featureDefinitions` `DataFrame` (`groups` in the old interface) has the same names.

You think that's OK?
