### ISSUE TITLE
random_shuffle() causes a WARNING on Linux

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#149]
Hi, `random_shuffle()` is called in https://github.com/sneumann/xcms/blob/5b73c67688add8718c998763a9d9053ea2885511/src/massifquant/TrMgr.cpp#L528.

On linux, the STL uses rand() under the hood, causing a WARNING,
and `random_shuffle()` is deprecated in C++14 in favour of `shuffle()`,
see http://en.cppreference.com/w/cpp/algorithm/random_shuffle

Moving to `shuffle()` requires C++-11 support, and something like the following, 
but Christopher Conley needs to confirm that this the correct random numbers.
Yours, Steffen

```{diff}
diff --git a/src/massifquant/TrMgr.cpp b/src/massifquant/TrMgr.cpp
index 12ac19f..2cc017a 100644
--- a/src/massifquant/TrMgr.cpp
+++ b/src/massifquant/TrMgr.cpp
@@ -1,5 +1,6 @@
 //TrMgr.cpp
 #include <algorithm>
+#include <random>
 #include <fstream>
 #include <iostream>
 #include "Tracker.h"
@@ -524,8 +525,12 @@ bool  TrMgr::isSeizmo(int i) {
     std::vector<double> rmz = mzVec; //make copy
     int midIdx = int(mzList.size()/2);
     int n = mzList.size() - midIdx;
+
+    std::random_device rd;
+    std::mt19937 g(rd());
+    
     for (int i = 0; i < 3; ++i) {
-        random_shuffle ( rmz.begin(), rmz.end() );
+        shuffle ( rmz.begin(), rmz.end(), g );
         std::vector<double> seizmo(n);
         int k = 0;
         for (size_t j = midIdx; j < mzVec.size(); ++j) {
```
Yours, Steffen

**Comment by topherconley** [comment]
Thanks Steffen, this patch looks good.

Doing some digging I realized that `isSeizmo` is a private function of `TrMgr` class that was once a naive attempt to filter out poor peaks that had lots of m/z variance. Apparently, at some point I commented out this specific filter (so `isSeizmo` is never executed) and I ought to probably delete that function at some point. 

Best,
Chris

**Comment by jotsetung** [comment]
Just an info: I've tried the above patch on my CentOS based linux build machine:
I had to add `-std=c++11` to the `Makevars` but then I got the following WARNING on `R CMD check`:
```
* checking compilation flags in Makevars ... WARNING
Non-portable flags in variable 'PKG_CPPFLAGS':
  -std=c++11
```

The gcc version:
```
[jo@centjos src]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by jotsetung** [comment]
I would thus rather go for @topherconley 's suggestion and remove the function. That OK with you @sneumann ?

**Comment by jotsetung** [comment]
Removing the `isSeizmo` function fixes this issue.
