### ISSUE TITLE
Getting rid of WARNING due to abort() down inside C++ STL

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#150]
For XCMS, R CMD check is complaining in
http://bioconductor.org/checkResults/devel/bioc-LATEST/xcms/malbec2-checksrc.html

about: 
`  Found ‘abort’, possibly from ‘abort’ (C) Objects: ‘massifquant/TrMgr.o’, ‘massifquant/Tracker.o’`

This is not called in the *.cpp code, but instead from deep inside the C++ STL, which I checked running 
the compilation only up to the preprocessor, see below. I currently have no idea how avoid the `abort()` in the C++ STL. Ideas ? Yours, Steffen

```
g++ -I/usr/share/R/include -DNDEBUG      -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c massifquant/TrMgr.cpp -E | less

...
# 1770 "/usr/include/c++/5/bits/stl_list.h"
void _M_check_equal_allocators(list& __x) {
 if (_M_get_Node_allocator())
   __builtin_abort();
}
```

**Comment by jotsetung** [comment]
Sorry, I've no idea how we could fix this - also I find it strange that this does not happen on mac, not on the build system and not on mine.

**Comment by jotsetung** [comment]
Just as a note: on CentOS with `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)` I don't get a warning related to the `abort`, but only the `rand` (issue #149) as a NOTE.

**Comment by jotsetung** [comment]
I've checked the `stl_list.h` that ships with mac os (c++ version 4.2.1) and it does not contain any such `__builtin_abort()` calls that the GCC implementation does.
Side not: found also a document describing the `__builtin_abort()`: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4000.pdf

**Comment by sneumann** [comment]
For convenient online reading, here is the `__builtin_abort();` in  gcc/libstdc++-v3/include/bits/stl_list.h
:
https://github.com/gcc-mirror/gcc/blob/1cb6c2eb3b8361d850be8e8270c597270a1a7967/libstdc%2B%2B-v3/include/bits/stl_list.h#L1825

**Comment by sneumann** [comment]
Update: Seems that CXXFLAGS are missing `-O2` on linux BioC machines. 
I can reproduce this using the BioC docker image:

```
root@a2c54e191bd1:/tmp/xcms/src# g++  -I/usr/local/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -fdebug-prefix-map=/build/r-base-3.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c massifquant/TrMgr.cpp -o massifquant/TrMgr.o && nm massifquant/TrMgr.o | grep abort
                 U abort
root@a2c54e191bd1:/tmp/xcms/src# g++  -I/usr/local/lib/R/include -DNDEBUG   -I/usr/local/include   -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-3.3.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c massifquant/TrMgr.cpp -o massifquant/TrMgr.o && nm massifquant/TrMgr.o | grep abort
```

**Comment by sneumann** [comment]
Closing, as the CXXFLAGS are not under XCMS control.

**Comment by sneumann** [comment]
Ok, Hervé Pagès commented that -O2 is not default in R-3.4 beta anymore, 
so we might have to add this ourselves in Makevars. Yours, Steffen

**Comment by jotsetung** [comment]
Think we can close this now, as the relevant C++ options are included again.
