### ISSUE TITLE
Update documentation to include also deprecations

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#158]
+ Label `nSlaves` as deprecated in `fillPeaks`.
+ Check all other documentations that deprecated things are labeled as such.

**Comment by hpbenton** [comment]
I wonder if it’s necessary to deprecate nSlaves. The naming makes a lot more sense than BPPRAM to users. We seem to have added a lot of new dependencies and changed the language on users.

**Comment by jotsetung** [comment]
For `xcms` users that might be true, `BPPARAM` is however known to *regular* Bioconductor users, as this is a parameter included in many Bioconductor packages. I'll keep the parameter anyways and will just show a message suggesting to use `BPPARAM` instead.

And yes, we have added new dependencies, but also removed some. I'm also not happy that e.g. package loading time is slower now. But by importing already established functionality from other packages we aimed to better integrate `xcms` into Bioc. Also we can reuse core functionality that was already implemented, like data subsetting etc. - I've found subsetting of xcmsSet and xcmsRaw particularly tricky, also access to raw data is not really straight forward.

Regarding the language, there have been changes too, but I tried to use terms that appear (talking to several people) more familiar to people in the metabolomics field (like `feature` instead of `group`).

**Comment by jotsetung** [comment]
Just as a general info: `BiocParallel` allows to define the parallel processing globally and all functions/methods from `xcms` will use these settings. Also, `BiocParallel` supports parallel processing using `multicore`, `doPar` and `snow` and would even allow to use schedulers on a large computer cluster.

```r
## To set the parallel processing using 4 CPUs globally using multicore:
library(BiocParallel)
register(MulticoreParam(4))
```
The user doesn't have to use the `BPPARAM` parameter in any function, each function will use this global setting by default.
