### ISSUE TITLE
fillPeaks indirectly calling deprecated profFun

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#163]
As experienced in http://bioconductor.org/checkResults/devel/bioc-LATEST/CAMERA/malbec2-checksrc.html
```
* checking examples ... WARNING
Found the following significant warnings:
  Warning: 'profFun' is deprecated.
```
which is because `fillPeaks` is calling `getPeaks,xcmsRaw` which in turn calls the deprecated `profFun`
in https://github.com/sneumann/xcms/blob/e9f39ecd6540aae7ba4a438d9ca8b26a1e8e80ff/R/MPI.R#L124

**Comment by jotsetung** [comment]
OK, seems I can fix that using the `.createProfileMatrix` function. I will implement a newer `getPeaks` that:
+ does not iteratively buffer and calculate the profile data (see also issue #47 for why to avoid that).
+ uses the newer `binYonX` and `imputeLinInterpol` functions.

**Comment by jotsetung** [comment]
Done and merged into devel branch.
