### ISSUE TITLE
Purpose of getSpecWindow and plotSpecWindow for xcmsSet?

### ISSUE THREAD

**Issue by ColeWunderlich** [sneumann/xcms#166]
This references code at: https://github.com/sneumann/xcms/blob/f775cbb7336e160ff7157d5e897c5cd1a0e93d8c/R/functions-xcmsSet.R#L444

I am wondering what the purpose of these functions are since I cannot find them referenced or used anywhere else in the source code, nor are they documented with their own man page.  I am wondering if these two functions are unused/legacy code.

**Comment by jotsetung** [comment]
These two functions are not exported by the package and are thus also not documented. The `getSpecWindow` is called from `plotSpecWindow` and the `plotSpecWindow` in the `diffreport` method.

**Comment by jotsetung** [comment]
I'm closing this now - if there is still something unclear you can re-open it any time @ColeWunderlich

**Comment by ColeWunderlich** [comment]
Thanks, missed the diffreport call.
