### ISSUE TITLE
SRM/MRM feature detection

### ISSUE THREAD

**Issue by wilsontom** [sneumann/xcms#169]
I'm not sure how feasible this is (or infact if it already exists); but now both `mzR` and `xcms3` are supporting SRM/MRM chromatograms is it possible to implement feature detection on `Chromatogram` objects ? So that `xcms3` can return feature information for SRM/MRM chromatograms (ie, peak area, rtmin, rtmax, etc..)

Thanks

Tom

**Comment by jotsetung** [comment]
Good point. Not yet, but that might be worth considering!

**Comment by jotsetung** [comment]
One note: the mz width of a chromatographic peak identified in a `Chromatogram` should be set to the `mz` width of the `Chromatogram`.

**Comment by wilsontom** [comment]
I'm not sure I follow; for a SRM/MRM chromatogram there would be no`mz` width as such, as the only data collected is intensity over time. 

Any feature detection would need to be applied only in the time domain and probably just have to rely on detection of 'valid' peak shape.

If you've got any pointers/ideas on how a `xcms3` feature detection method like this could be implemented; i'm happy to try and contribute wherever possible.

**Comment by jotsetung** [comment]
Yes, you're right. This was just an internal note to myself. A `Chromatogram` could also be extracted for the full `mz` range which would then correspond to a e.g. base peak chromatogram. Peak detection on such a chromatogram would also be possible (questionable whether that's meaningful though).

**Comment by stanstrup** [comment]
Related to https://github.com/sneumann/xcms/issues/57

**Comment by jotsetung** [comment]
Just to update - there's the chance I'll be able to work on that in the future - we've added SRM/MRM support in `MSnbase`: https://github.com/lgatto/MSnbase/issues/286

**Comment by wilsontom** [comment]
Excellent. 

I've been playing around with a couple of different approaches. But the easiest way might be to just convert SRM chromatogram data into LC-MS style scan data. Then matchedFilter detection in xcms could be used for feature integration. I've hacked together some code in [MRMConverteR](https://github.com/wilsontom/MRMConverteR) but definitely needs refining. 

Tom

**Comment by jotsetung** [comment]
Thanks @wilsontom for the suggestion. In the end I think converting to spectrum data is not really necessary. The detection algorithms are pretty agnostic whether the data is in chromatogram or spectrum mode - they just want vectors with intensity, retention time and m/z values. There will be some fixing though (e.g. for `centWave`'s first *find regions of interest* part).

**Comment by jotsetung** [comment]
I think we can close this issue now, since the functionality has been implemented. Feel free to re-open if needed.
