### ISSUE TITLE
switch to ggplot2?

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#172]
I was wondering if it is time to switch the plotting feature to ggplot2?
That would allow post-processing of the plots and allow turning them easily interactive with plotly.

**Comment by sneumann** [comment]
Hi, cool idea. would you mind starting e.g. a vignette, exemplifying 
some of the ggplot2 visualisations ? Then we could migrate that code 
into the core of xcms.

**Comment by jotsetung** [comment]
Awesome idea! Always wanted to do that - will do for new plotting functions.

**Comment by stanstrup** [comment]
so @jotsetung how can I best help with that?

**Comment by jotsetung** [comment]
@stanstrup You could for example ggplot2ify the plotChromatogram function - that would be awesome.

**Comment by stanstrup** [comment]
I'll look into that.

**Comment by jotsetung** [comment]
ggplot2-based functions should also enable to define different colors for each sample/line. Ideally by not providing the colors with an argument `col` but by changing it afterwards, e.g. using `+ scale_color_manual` - don't know whether that would be easy to implement though...

**Comment by michaelwitting** [comment]
Great idea... if you need any beta-tester: I'm here... ;-)

**Comment by stanstrup** [comment]
I did some Friday procrastination: https://rawgit.com/stanstrup/xcms_ggplot2/master/plot.Chromatograms.html

I need to figure how to handle when the `Chromatogram` object can have more than one mzrange per file.
But what do you think? Is this way of doing it useful? I guess one downside is that you need some ggplot2 knowledge to be able to get a useful plot.

**Comment by jotsetung** [comment]
Looks great! Some notes:
+ while ggplot2 is nice, I would also want to keep base plotting in parallel (at least for some time). The downside of ggplot IMHO: reformatting the data in the `S4objects` into `data.frame`s might be memory demanding and eventually slow things down. 
+ what about using a consistent naming scheme for the plots? e.g. `plot...` for base plotting and `ggplot...` for functions/methods that use `ggplot2`?
+ Note that in more recent `xcms` versions the `Chromatogram` functionality (including plotting etc) was moved to `MSnbase` and that the `plotChromatogram` method is now deprecated (replaced by `plot,Chromatogram`. Also, there is now a `Chromatograms` class (extending `matrix` to contain multiple `Chromatogram` objects. sounds complicated but is actually quite handy: columns are always samples, rows are mz/rt ranges.

**Comment by stanstrup** [comment]
Thanks.

You are right. Probably better keep base plots around for the foreseeable future.
As for memory I don't think it is a major issue. The data.frame created in the current example is for example only 600kB including the tooltip text.

I think it could be nice as you said to have parallel plot and ggplot. Is that straight forward to implement?

I did see that the plots were moved to `MSnbase`. `xcms` was loaded in my example but never actually used. So it works with the newest  `MSnbase`.

I updated the functions and examples (https://rawgit.com/stanstrup/xcms_ggplot2/master/ggplot.Chromatograms.html):

* uses NAnnotatedDataFrame object to inject additional info in the same way `readMSData2` does. btw.: wouldn't it make sense if the pdata was preserved in the `chromatogram` object?
* Added interactivity including hover info.
* Now works with mz, rt intervals.

So where do we go from here?
Perhaps we should also move this conversation to the MSnbase repo?

**Comment by jotsetung** [comment]
This is awesome! Cool stuff @stanstrup 
re phenoData in `Chromatograms`: I added an issue over in `MSnbase` (https://github.com/lgatto/MSnbase/issues/236) and will implement that.

And yes, you're right. These methods should be added in `MSnbase`, not `xcms` (https://github.com/lgatto/MSnbase/issues/237).

**Comment by stanstrup** [comment]
Lets close this then and keep it in the MSnbase repo.
