### ISSUE TITLE
no slot of name ".processHistory" for this object of class "xcmsSet"

### ISSUE THREAD

**Issue by eschen42** [sneumann/xcms#176]
I have an xset.RData file produced by xcms 1.46.0, attached
[Galaxy2-xset.RData.zip](https://github.com/sneumann/xcms/files/1012803/Galaxy2-xset.RData.zip)

When I try to load it into R (RStudio) with xcms 1.52.0, I get the following response when I run `str(xset)`:

```
Error in FUN(X[[i]], ...) : 
  no slot of name ".processHistory" for this object of class "xcmsSet"
```

The obvious workaround for me was to revert my xcms version that I am using in RStudio to 1.46.0, which worked as expected; I thought that you might like to know about this which appears to me to be a backward compatibility-issue.

**Comment by jotsetung** [comment]
You can update the object to the *newer* `xcmsSet` class definition:
```r
> str(xset)
Error in FUN(X[[i]], ...) : 
  no slot of name ".processHistory" for this object of class "xcmsSet"
> xset <- updateObject(xset)
> str(xset)
Formal class 'xcmsSet' [package "xcms"] with 15 slots
  ..@ peaks           : num [1:1788, 1:11] 291 211 211 211 211 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : NULL
  .. .. ..$ : chr [1:11] "mz" "mzmin" "mzmax" "rt" ...
  ..@ groups          : logi[0 , 0 ] 
  ..@ groupidx        : list()
  ..@ filled          : int(0) 
  ..@ phenoData       :'data.frame':	1 obs. of  1 variable:
  .. ..$ class: Factor w/ 1 level "y8": 1
  ..@ rt              :List of 2
  .. ..$ raw      :List of 1
  .. .. ..$ : num [1:2431] 1.16 1.68 2.21 2.74 3.27 ...
  .. ..$ corrected:List of 1
  .. .. ..$ : num [1:2431] 1.16 1.68 2.21 2.74 3.27 ...
  ..@ filepaths       : chr "yarrow-one/y8/Y-065-GB4-Y18_3.mzML"
  ..@ profinfo        :List of 2
  .. ..$ method: chr "bin"
  .. ..$ step  : num 0.1
  ..@ dataCorrection  : int(0) 
  ..@ polarity        : chr(0) 
  ..@ progressInfo    :List of 12
  .. ..$ group.density          : num 0
  .. ..$ group.mzClust          : num 0
  .. ..$ group.nearest          : num 0
  .. ..$ findPeaks.centWave     : num 0
  .. ..$ findPeaks.massifquant  : num 0
  .. ..$ findPeaks.matchedFilter: num 0
  .. ..$ findPeaks.MS1          : num 0
  .. ..$ findPeaks.MSW          : num 0
  .. ..$ retcor.obiwarp         : num 0
  .. ..$ retcor.peakgroups      : num 0
  .. ..$ fillPeaks.chrom        : num 0
  .. ..$ fillPeaks.MSW          : num 0
  ..@ progressCallback:function (progress)  
  ..@ mslevel         : num(0) 
  ..@ scanrange       : num(0) 
  ..@ .processHistory : list()
```

**Comment by eschen42** [comment]
Super! That works great.  Thank you for your help.

Would it make sense to update the xset object in place (if that is even possible)?
Or (if it is impossible) is it possible to provide a hint (e.g., `Try something like 'xset <- updateObject(xset)' to address this error.`) when emitting the `no slot of name ".processHistory" for this object of class "xcmsSet"` error message?

**Comment by jotsetung** [comment]
Just always call `xset <- updateObject(xset)`. That will update the `xset` to the new version.

**Comment by eschen42** [comment]
Yes, I understand that and will try to remember that trick for the future. 

But, would it make sense to add it to the error message? Is that even possible? Thanks.

**Comment by jotsetung** [comment]
Most functions in `xcms` test if the `xcmsSet` object is the newest version and show a warning if it is not suggesting to use the `updateObject` function.
Functions like `str` are outside our control and we can not add any specific warnings/errors there. I know it's not ideal, but there's no way around that. We did anyway just introduce slots that keep track of the processing history, so all analysis methods will work even if these slots are not present.
