### ISSUE TITLE
retcor: error when both method and smooth explicit

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#180]
Shouldn't all these 4 combinations of arguments work?

```
> library(faahKO)
> library(xcms)
> xs_g <- group(faahko)
Processing 3195 mz slices ... OK
```
``` 
> xs_r1 <- retcor(xs_g)
Performing retention time correction using 132 peak groups.
```

```
> xs_r2 <- retcor(xs_g, method="loess")
Performing retention time correction using 132 peak groups.
```
```
> xs_r3 <- retcor(xs_g, smooth="loess")
Performing retention time correction using 132 peak groups.
```

```
> xs_r4 <- retcor(xs_g, method="loess", smooth="loess")
Error in .local(object, ...) : 
  formal argument "smooth" matched by multiple actual arguments
```

**Comment by jotsetung** [comment]
I'll look into that.

**Comment by jotsetung** [comment]
Fixed it. Now you get a warning instead:
```r
> xs_r4 <- retcor(xs_g, method="loess", smooth="loess")
Performing retention time correction using 132 peak groups.
Warning message:
In .local(object, ...) :
  Provided argument 'smooth' will be replaced with the value of 'method', i.e. with loess
```

**Comment by stanstrup** [comment]
But isn't the point that you can have method="loess", smooth="linear"?

**Comment by jotsetung** [comment]
I can see only two `retcor` methods in the code, the `retcor.peakgroups` and the `retcor.obiwarp`. The former supports the `smooth` parameter. method should actually either be `"peakgroups"` or `"obiwarp"`. If `method == "loess"` or `method == "linear"` the `retcor` method automatically calls the `retcor.peakgroups` and passes either `"loess"` or `"linear"` as `smooth` parameter.

What would a `method = "loess", smooth = "linear"` expected to do? The smooth parameter is supposed to define the method how retention times between the peak groups are adjusted, either using a linear fit or using loess... the name `smooth` for this parameter is actually quite misleading...

**Comment by stanstrup** [comment]
OK. I think there is very confusing documentation then.
It says:

> Different algorithms can be used by specifying them with the method argument. For example to use the approach described by Smith et al (2006) one would use: retcor(object, method="loess"). This is also the default.

So from that it reads to me as if loess is the name of the method that then has a parameter smooth to choose actual loess or linear.
The links at the buttom of the retcor-methods man page also links to retcor.loess. It does send you to 
retcor.peakgroups-methods though but at this point it had me sufficiently fooled...

I think in this case the method nicknaming is confusing things.

**Comment by stanstrup** [comment]
So actually since `method="loess"` is supposed to be nick name for `method="peakgroups"`
I would expect
```r
method="loess", smooth="linear"
```

to be equivalent of 
```r
method="peakgroups", smooth="linear"
```

**Comment by jotsetung** [comment]
Ah, no. 
`method = "loess"` and `method = "linear"` both link to `retcor.peakgroups`. And if you use `method` the argument `smooth` is discarded. It's confusing, I know. I think this all comes from the time where there was no `retcor.obiwarp` and hence the `method` argument was used to switch between `linear` and `loess` interpolation. Then `retcor.obiwarp` was implemented and, to be consistent with the other methods (`findPeaks` etc) the `method` argument was used to switch between different methods, i.e. between `retcor.obiwarp` and `retcor.peakgroups`. I'm afraid that the documentation was however never updated.

**Comment by jotsetung** [comment]
Closing since this should have been fixed. Re-open if necessary.
