### ISSUE TITLE
Problem with isCentroid() data returning NA prior to findChromPeaks() Centwave method.

### ISSUE THREAD

**Issue by crmclean** [sneumann/xcms#181]
Good Afternoon,

I was able to follow the examples on bioconductor using the new XCMS interface to processes raw data, but I have struggled to do the same with my own data. I would very much appreciate the help of you all to diagnose the issue and recommend possible solutions. 

The issue I am having involves running the function isCentroid() on my OnDiskMSnExp object within the findChromPeaks() function using a centwave method. After running just isCentroid() on the OnDIskMSnExp object based on my data, many of the values are returned as NA. Given the if statement looking at centroid mode in the code for the centwave findChromPeaks() method, I am assuming that the lack of a logical value here is what is causing the code to break. 

In the past, I have been able to accomplish the peakpicking using the findPeaks.centWave method on our data without any problem. 

An example of a very short script using my data illustrating this issue can be found here:

https://github.com/crmclean/Reproducible_Examples/tree/master/xcms

I am sorry if this is a trivial issue that I am just simply overlooking, and I am very grateful to you for taking the time to look at my question.

**Comment by jotsetung** [comment]
Thanks for posting this issue. I will look into this.

**Comment by jotsetung** [comment]
The `isCentroided` method is imported from the `MSnbase` package - I have to check how `MSnbase` estimates whether a spectrum is centroided or not and then check how we can fix that.

**Comment by crmclean** [comment]
If it helps, I found this link to what appears to be a similar issue an ```MSnbase``` user had using the ```isCentroided```. 

https://github.com/lgatto/MSnbase/issues/150

**Comment by jotsetung** [comment]
I have a fix ready - but need to fix first some other stuff before I push it.

**Comment by jotsetung** [comment]
you can go ahead and install the newest version with the fix for your problem from github. Unfortunately you are then stuck on the development branch of `xcms`, but it's unlikely that we push this to the current stable `xcms` (from Bioconductor version 3.5).

```r
library(devtools)
install_github("sneumann/xcms", ref = "xcms3")
```

**Comment by crmclean** [comment]
Just tried the update, and it worked well! Thank you for the help!
