### ISSUE TITLE
No console messages xcmsSet (xcms v1.50.1)

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#186]
From the forum: http://www.metabolomics-forum.com/index.php?topic=1169.new#new

**Comment by jotsetung** [comment]
Will check if we can restore that `cat` and `message` calls within `bplapply` are shown immediately.

**Comment by jotsetung** [comment]
See https://support.bioconductor.org/p/96856/ for an explanation. Will report this at the forum.
