### ISSUE TITLE
Timeout in CHECK on Tokay 

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#187]
Hi, after moving to pwiz backend by default in mzR, and fixing some MSnbase fallout
about the unknown file types, we're left with "only" a timeout on Windows.
Both other architectures finish in 1100 seconds, but Windows needs >2400.
Note that windows is running tests and examples twice. None of the 
examples take >20sec on i386 nor x64, but there are no timings 
for the unit tests.

http://bioconductor.org/checkResults/devel/bioc-LATEST/xcms/tokay1-checksrc.html
ends with  
```
** running tests for arch 'i386' ...
  Running 'doRUnit.R'
 OK
** running tests for arch 'x64' ...
  Running 'doRUnit.R'
````
without `OK` for x64, possibly due to the timeout.

**Comment by jotsetung** [comment]
I tweaked the unit tests - so they *should* be fast. I'll look into that.

**Comment by jotsetung** [comment]
Unfortunately I have no access to my Windows virtual machine this week, but I'll fix next week.

**Comment by jotsetung** [comment]
It might help to remove some tests introduced during the definition of the core API `do` functions.

**Comment by jotsetung** [comment]
check times should be faster now - closing as the TIMEOUT has gone.
