### ISSUE TITLE
Forcing input file type

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#188]
Hi, it seems that Galaxy is renaming all input files to `*.dat*`, 
and when reading poor xcms is unsure what file type this is. 
Some file-type override would be cool, or getting galaxy to not 
mess with filenames, or guessing file type by first X bytes 
(checking for e.g. `<mzML>`) would be cool.

**Comment by jotsetung** [comment]
Is galaxy replacing the file ending or just appending a *.dat*. The function to guess the file type would account for appending another suffix.
Otherwise, yes, we need to implement a function that checks the file content for files that are not recognized (by file ending).

**Comment by sneumann** [comment]
Hi, galaxy will replace the ending. The following expressions should do the trick:

netCDF magic bytes taken from https://github.com/file/file/blob/844a691f9161af44a3997de433cae716766e04aa/magic/Magdir/images#L1107 ,
`substr(readBin("/.../faahKO/cdf/KO/ko21.CDF", character(), n=1),1,3) == "CDF"`

and for the XML flavours something like 
`any(grepl("<mzML", readLines("/tmp/MM8.dat", n=4)))`
taking into account that there might be later be leading lines with encoding
as in `<?xml version="1.0" encoding="ISO-8859-1"?>` but also other filetypes mentioned later 
as in `<processingOperation name="Conversion to mzXML"/>` which should 
not trigger detection of mzXML, hence limiting to first, say, 4 lines. Will fail in very weird 
cases with everything cramped into a single line and mentioning different mzML/mzXML/mzData.

**Comment by c-ruttkies** [comment]
Hi, maybe an additional parameter for xcmsSet function like 'filetype="mzml"' would be a quick workaround to force the file type independently of the file ending. 
Best regards, Christoph

**Comment by jotsetung** [comment]
That might be a nice intermediate solution - I check into this.

**Comment by jotsetung** [comment]
Looking at the code, the quick solution seems to be a little more complicated. Adding a parameter `filetype` to the `xcmsSet` and `xcmsRaw` functions would be OK and would allow to manually specify the file type, the problem however is, that the `xcmsSet` *forgets* this information, i.e. there is no slot for that in the `xcmsSet` class.

So, I'll try now @sneumann 's approach.

**Comment by jotsetung** [comment]
OK, it's done in https://github.com/sneumann/xcms/commit/7ef70598754cffc9e896ddb3358f62471e0d16cb (`xcms3` branch) and I merged the `xcms3` branch already into `devel`.
@sneumann, I realized that the `biocdevel` branch is not up-to-date, so I didn't merge `devel` into `biocdevel` yet.

**Comment by jotsetung** [comment]
Closing this issue as we seem to have fixed it.
