### ISSUE TITLE
Splitting MS2 data into different MRM windows

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#190]
Hi all.

I used the old XCMS version to do some analysis on SWATH data and similar data types (with the help of Steffen). I wanted to change now to the new XCMS version since I saw that it processes much faster.

Following code is used:

`#read MS1 data into xcmsRaw
xrms1 <- readMSData2("mzML\\test.mzml", msLevel. = 1)

cwp <- CentWaveParam(snthresh = 20, noise = 1000)
xod <- findChromPeaks(xrms1, param = cwp)

chromPeaks(xod)`

This works fine for MS1 peak picking.
Now I import the MS2 data and split according to the different "precursors".
`xrms2 <- readMSData2("mzML\\test.mzml", msLevel. = 2)
precurors <- xrms2@featureData@data$precursorMZ

xrswaths <- split(xrms2, f=as.integer(precurors))`

If I'm now performing peak picking on the MS2 level data with the following command I'm getting an error:

xod2 <- findChromPeaks(xrswaths[[1]], param = cwp)

Error in fromFile(x)[[i]] : subscript out of bounds

Any idea, what I can do?

Thank you very much in advance!

Michael

**Comment by jotsetung** [comment]
cool that you're using the new user interface! I've never analyzed SWATH data so far, so I was puzzled that you do chromatographic peak detection on the MS2.
In case, if you could provide a test file and an example analysis (e.g. how you would expect the analysis to work) I could have a closer look what is going on.

**Comment by michaelwitting** [comment]
Hi,

in my dropbox you find the file from the code above.

**Comment by michaelwitting** [comment]
Traced it back to MsnBase package... Looks like the function fromFile(x) cannot handle this...

**Comment by jotsetung** [comment]
This error was misleading. I had in the `findChromPeaks` method a call that explicitly subsetted the data set to MS1 spectra only - without checking if the object is empty after subsetting.
I fixed it now in the most recent version in the `xcms3` branch adding also an argument `msLevel` to the `findChromPeaks` method that allows to specify on which MS level the peak detection should be performed.

The slightly updated code from above:
```r
library(xcms)
## Read the full data at once (all MS level). Advantage: easier to link
## MS1 and MS2 data and file has to be read only once. 
xrms <- readMSData2("test.mzML")

## Do peak detection on MS1
cwp <- CentWaveParam(snthresh = 20, noise = 1000)
xod <- findChromPeaks(xrms, param = cwp)
chromPeaks(xod)

## Subset to MS2 spectra/data
xrms_ms2 <- filterMsLevel(xrms, msLevel = 2)
## Use the fData method to access the "feature data" (i.e. the mzML header)
precursors <- fData(xrms_ms2)$precursorMZ

xrswaths <- split(xrms2, f = as.integer(precursors))

## Peak detection on all; explicitely tell findChromPeaks to run on MS2
xrswaths_x <- lapply(xrswaths, FUN = findChromPeaks, param = cwp, msLevel = 2)
```

In order to run this you need the most recent `MSnbase` and `xcms` package developmental versions:
```r
library(devtools)
devtools::install_github("lgatto/MSnbase", ref = "chromatogram")
devtools::install_github("sneumann/xcms", ref = "xcms3")
```

Actually, I would be very interested to add the SWATH analysis to `xcms` at some point.

**Comment by michaelwitting** [comment]
Hi.
Thanks I will test everything. I will go on with some test scripts around the SWATH project. We have some test data to look at and I would like to check if the scripts are doing what they should. Once we are sure about this we can maybe implement this into xcms. I'm using quite basic xcms functions for this, so I guess it should be not too complicated.

**Comment by michaelwitting** [comment]
It is working now with the MS2 data, but the Peak picking in this branch is somehow horrible slow and finds not a lot of peaks

**Comment by jotsetung** [comment]
That is strange. Can you print the output of your `sessionInfo`? I didn't make any changes to the peak picking algorithms so you should get the same peaks...

**Comment by michaelwitting** [comment]
R version 3.4.0 Patched (2017-06-13 r72789)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] grid      parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RColorBrewer_1.1-2  gridExtra_2.2.1     ggplot2_2.2.1       xcms_2.99.4         MSnbase_2.3.8       ProtGenerics_1.8.0  mzR_2.10.0          Rcpp_0.12.11       
 [9] BiocParallel_1.10.1 Biobase_2.36.2      BiocGenerics_0.22.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.0         BiocInstaller_1.26.0   plyr_1.8.4             iterators_1.0.8        tools_3.4.0            zlibbioc_1.22.0        digest_0.6.12         
 [8] MALDIquant_1.16.2      tibble_1.3.3           preprocessCore_1.38.1  gtable_0.2.0           lattice_0.20-35        rlang_0.1.1            foreach_1.4.3         
[15] Matrix_1.2-10          IRanges_2.10.2         S4Vectors_0.14.3       stats4_3.4.0           multtest_2.32.0        impute_1.50.1          XML_3.98-1.9          
[22] survival_2.41-3        RANN_2.5.1             limma_3.32.2           scales_0.4.1           pcaMethods_1.68.0      codetools_0.2-15       MASS_7.3-47           
[29] splines_3.4.0          mzID_1.14.0            MassSpecWavelet_1.42.0 colorspace_1.3-2       affy_1.54.0            doParallel_1.0.10      lazyeval_0.2.0        
[36] munsell_0.4.3          vsn_3.44.0             affyio_1.46.0

**Comment by jotsetung** [comment]
Eventually you might also try to update `mzR` to the most recent devel version.
```r
devtools::install_github("sneumann/mzR")
```
Regarding performance, it might also help to pre-register the *cluster*:
```r
library(BiocParallel)
## Use snow since you're on Windows
prm <- SnowParam()
## Use bpstart to initialize the cluster
register(bpstart(prm))
```

**Comment by michaelwitting** [comment]
mzR was somehow the problem,. Installed now version 2.11.3 and everything is fast again, but still finds only a low amount of peaks. I use the same file as above...

**Comment by jotsetung** [comment]
Would it be possible for you to provide me some more infos? Specifically, could you tell me with which version of `xcms` you found more peaks? Did you also use the *new* interface for that? I would like to dig into the code to see what might cause the identification of fewer peaks.

**Comment by sneumann** [comment]
Bonus points for providing code that provides more peaks via one route,
Vs. Code that only finds fewer.
Yours Steffen

---
I blame Android for the brevity and typos

**Comment by michaelwitting** [comment]
Sorry for the trouble, Looks like I mixed up my files. Checked now with the developmental Version of XCMS from Bioconductor (2.99.3) and the XCMS 3 branch. They deliver the same results. It was two different .mzML files that confused me.

Sorry once again...

**Comment by jotsetung** [comment]
:-) no problem.
