### ISSUE TITLE
Excessive memory use in fillPeaks

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#191]
I have observed now a number of times that fillPeaks seems to use an excessive amount of memory under some conditions.
I was processing 8 files for a total of ~400MB but fillPeaks gave up when it had exhausted my memory using 20+GB.

I tried in serial mode and that works. But it uses ~10GB for every file. So something funky is going on...

Any ideas? I can provide an xcmsSet object if you need.

I use `profparam = list(step=0.005)`. Was something changed in the profile matrix generation that could have made this more heavy?

**Comment by sneumann** [comment]
What about  step=1 ?  If that's OK, then the issue is indeed there, otherwise the culprit is elsewhere.

**Comment by stanstrup** [comment]
Good idea. Just tried that and indeed the memory usage is then minimal.

**Comment by jotsetung** [comment]
With `step = 0.005` the profile matrix will be very large - this coupled with parallel processing (depending on the numbers of cores) might indeed require massive memory.

Note that the `fillChromPeaks` of the new user interface will only create the profile matrix in case `matchedFilter` was used for peak detection (using the same `step` that was used in peak detection). For all other methods it integrates the signal from the original files. Memory demand should be lower there.

**Comment by stanstrup** [comment]
OK I tried to look into this to see how bad it really is.
While a rather large matrix is needed at least twice the needed memory is allocated. I actually thought it was worse than that; I guess I had shorter runs before since I never really had issues with this.

If I do 
`raw_fine <- xcmsRaw(settings$general$files[1], profparam = list(step=0.005), profstep = 0.005)`

`Memory usage: 3160 MB`

But real memory usage is twice that judging by task manager after the function is done.
`gc()` releases the "extra" used memory. 

But more than that I can see that while the function runs ~3 times that needed for the matrix is used at one point.

This "double" allocation is because the data needs to exist both in the C and R side at the same time, right?

Any idea why it seems to be allocated 3 times though?

**Comment by jotsetung** [comment]
On what system do you experience these problem? Is this on Windows?

**Comment by stanstrup** [comment]
Yes on windows.

**Comment by stanstrup** [comment]
I have now tracked this down and documented the behavior better.

Tracking the source of the issue goes like this:
xcmsRaw --> profStep --> profMat --> .createProfileMatrix --> binYonX

The root of the problem is that `binYonX` returns an object twice as large as the final profiling matrix.

This means that when you call .createProfileMatrix/profMat you use 3 times the memory required for the profiling matrix. the extra 2x (x == the size of the profile matrix) can be release by `gc()`. When you do this in parallel it becomes  lot of memory used at the same time.

It seems like R is smart about the extraction of data when generating binVals (in .createProfileMatrix). This does not use additional memory even if the returned object has size 1x.

is the 3x comes from the binRes object created by binYonX and the final profiling matrix (buf).

When I do fillPeaks it looks like one additional x is intermittently used somewhere judging from the memory usage. But I haven't tracked down the source of that.

**Comment by stanstrup** [comment]
Is the x vectors in binRes guaranteed to always be identical?
In my test seems so:
```
all(sapply(binRes, function(i) identical(i$x,binRes[[1]]$x)))
[1] TRUE
```

If so you could return 1 x vector and 1 y matrix instead of x/y pairs?

**Comment by jotsetung** [comment]
nice job @stanstrup . I'll look into that.

**Comment by jotsetung** [comment]
OK, I was able to reduce it by hacking the C routines. In fact, I was generating by default additional vectors that are not required for the profile matrix generation: one INTEGER vector, same length as number of bins, and a DOUBLE vector, same length as number of bins. The INTEGER vector is now no longer created, and creation of the latter is also disabled if the new argument `returnX = FALSE` in `binYonX`.
The impact on this on a test file:
before the fix:
![before_fix](https://user-images.githubusercontent.com/5506112/29664328-790ab1a2-88cf-11e7-8965-dce12421cecc.png)

after the fix:
![after_fix](https://user-images.githubusercontent.com/5506112/29664332-7ec68436-88cf-11e7-9cd8-5359fe7a7be0.png)

The fix reduced the memory demand from 4684MB to 2814MB. The result object has a size of 1.3 GB, unfortunately there is no way to get around the `do.call` that converts the `list` of `vectors` into the final `matrix`.

Hope that fixes also your problem in `fillPeaks` @stanstrup .

**Comment by stanstrup** [comment]
Thanks! I am sure this will help. Cutting the demand in half more or less is a big improvement allowing twice the number of parallel processes.

**Comment by jotsetung** [comment]
but be careful - since `fillPeaks` and others are reading data from disk the IO can become the bottleneck, not the number of parallel processes or required memory - learned my lessions on our cluster - not running more than 4-8 processes in parallel anymore.

**Comment by jotsetung** [comment]
Anyway - feel free to close if you're happy with the result.

**Comment by stanstrup** [comment]
Yeah thanks. I know not to go crazy with threads on this but I was at the point where I could basically only do one at a time on my workstation and ~6 on our server before maxing out all the memory...

Just a note since I guess it might break things down-stream but if you make a data.frame instead of a matrix it magically becomes a copy without using more memory keeping the total usage at the size of the profile matrix:

```buf <- base::do.call(cbind, lapply(binVals,function(x) as.data.frame(x = x)))```

Both binVals and buf would refer to same memory as binRes.

**Comment by jotsetung** [comment]
Thanks. To return a `data.frame` it would even be much simpler since a `data.frame` is in essence simply a `list`: `buf <- as.data.frame(binVals)`. Problem is that it could break downstream code and definitely will have an impact on performance - most operations on matrices are optimized in R.

**Comment by stanstrup** [comment]
Ah yeah. Should have thought of that. :(
Anyway, as you said probably don't mess with this as it is probably used in too many places to be sure not to break things.

Not sure about performance. Conversion to matrix and subsetting a matrix is not free either. So really depends if there are matrix operations downstream or not; or subsetting is a bottleneck.

**Comment by jotsetung** [comment]
You're right. `matrix` has its downsides too. If memory overhead of the `do.call(cbind` is acceptable I would prefer to keep it as a `matrix` to ensure we're not introducing a new bug/incompatibility.

**Comment by stanstrup** [comment]
Yeah sure; I agree.
Thanks again for the fix. I'll close this.
