### ISSUE TITLE
xcmsRaw parses no polarity data

### ISSUE THREAD

**Issue by lee-t** [sneumann/xcms#192]
Hello, 
I'm trying to process files converted from RAW into mzXML files. I seem to run into an issue in which xcmsRaw does not seem to find the polarity, which in these files is  written in "+" and "-" .

This issue is very similar to  #22 but instead of defaulting to "negative" it leaves the field blank.

As an example:

`
rawfile = xcmsRaw(mzXMLfile)
`
where "mzXMLfile" is this file https://github.com/vanmooylipidomics/PtH2O2lipids/blob/master/mzXML/Pt_H2O2_mzXML_ms1_pos/0_uM_H2O2/0uM_24h_Orbi_0468.mzXML

The resulting parse returns:
```

Browse[1]> rawfile@polarity
factor(0)
Levels: 
```
The entire row is completely empty. 
I'm using R version 3.4.0 and xcms 1.52

**Comment by jotsetung** [comment]
sorry for my late reply, but I was on holidays. I'll have to check it but AFAIK the `Ramp` backend that was used by default in `mzR` (the package used also by `xcms` to read raw data) to read `mzML` and `mzXML` files did not read polarity data from the files. Recently we changed the default backend in `mzR` to `pwiz` which does read the polarity properly.

Unfortunately all these changes are available only in the *devel* branch of Bioconductor and I'm not sure if you want to switch to that.

**Comment by jotsetung** [comment]
Indeed, polarity information was imported from *mzML* files, but not from *mzXML* files. Thanks for reporting this. 
I've fixed it in the *xcms3* branch and it will be included in future releases of `xcms`.
If you would give it a go already now you can install the most bleeding edge devel version from github:
```
library(devtools)
install_github("sneumann/xcms", ref = "xcms3")
```

**Comment by lee-t** [comment]
```
> packageVersion("xcms")
[1] ‘2.99.4’
```
This version runs without errors, thank you. Glad to be of use!
