### ISSUE TITLE
Expanding peakrange in fillpeaks

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#2]
Hi. I don't know if this is now the proper place to post suggestions but here it goes.

As have been noted previously (http://metabolomics-forum.com/viewtopic.php?f=25&t=148) the peak range for the initially picked peaks can be too narrow to allow proper re-integration for all samples.

I suggest that a parameter to expand peakrange in getPeaks is added to fillPeaks.chrom and passed on to fillPeaksChromPar.
I don't know the what the most appropriate way to pass the parameter would be so hence no pull request.

I suggest the multiplier is used like this:
you set M=0.1 if you want to increase the peakrange interval by 10%

the peakrange to use in getPeaks then becomes:

mzmax_new = mzmax   +    ((mzmax-mzmin)_M)/2
mzmin_new  = mzmin     -    ((mzmax-mzmin)_M)/2

**Comment by stanstrup** [comment]
I have reopened this. See the pull request here: https://github.com/sneumann/xcms/pull/3
What needs to happen to get this included?

**Comment by stanstrup** [comment]
I have reopened this. See the pull request here: https://github.com/sneumann/xcms/pull/3
What needs to happen to get this included?

**Comment by stanstrup** [comment]
Forgot to say that I would really like this included as soon as possible since the version the pull request was based on is no longer compatible with current versions of the dependencies, so I cannot use my fork.

**Comment by stanstrup** [comment]
Is it possible to use FillChromPeaksParam (so that you can use the ppm setting that sets a minimum width) in the old workflow?
I still consider this a pretty critical issue that current fillpeaks will try to integrate in an essentially 0 width m/z slice.

**Comment by jotsetung** [comment]
Unfortunately `FillChromPeaksParam` can not be used in the old workflow. The new `fillChromPeaks` uses completely different code, i.e. it *really* reads raw data to fill in peaks. In the old workflow, even if you used `centWave` and thus did never have the need for the `profile` matrix, the peaks are filled in from the profile matrix.

I'll check if and how I can include this parameter in the old workflow too.

**Comment by stanstrup** [comment]
Thanks. I did make a pull request for a minimum widths of mz and rt. Just used absolute widths instead of ppm. I think you also found a bug in my code though.
Right now there are only the expand options while the minimum options would be more helpful.

**Comment by jotsetung** [comment]
Closing this issue (the oldest one we've had still open!), because this feature is added in the new user interface functions: possibility to expand the are by a constant or relative value in both m/z and rt dimension.
