### ISSUE TITLE
Error in file(con, "w") : all connections are in use

### ISSUE THREAD

**Issue by tobigithub** [sneumann/xcms#20]
Hi,

This happens when snow is invoked by xcms with 128 threads under WIndows. Error output is different from R to R version.. XCMS library Bioconductor version: Release (3.1). 64 threads work fine. 
65 threads does start everything, but never finishes and then with higher numbers this. Rmpi is not installed and not used in this case.
````
Starting snow cluster with 128 local sockets.
Error in file(con, "w") : all connections are in use
Timing stopped at: 1.47 0.35 69.5 
>   sessionInfo()
Error in gzfile(file, "rb") : all connections are in use
````
Solution: None, its not a Windows threading limitation, not a memory limitation

[Source](https://github.com/tobigithub/R-parallel/wiki/R-parallel-Examples) for the current error, just ramping number of CPUs up from 32 to 64 to 128 and so on.

Currently not relevant for me, but there are a bunch with 256 or 512 CPUs under WIN or [many core systems] (https://www.google.com/search?q=windows%2Btask%2Bmanager%2Bmanycore&num=20&source=lnms&tbm=isch&sa=X).

Cheers
Tobias

**Comment by tobigithub** [comment]
Hi,
This is a native R limitations (as far as I know). See here in my [R-parallel WIKI] (https://github.com/tobigithub/R-parallel/wiki/R-parallel-Errors#snow-and-dosnow---all-connections-are-in-use). Basically in the R source (connections.c) there is a limitation: 
#define NCONNECTIONS 128 /* snow needs one per slave node */

Did not test it by recompiling R, but I think that is the culprit.
Cheers
Tobias

**Comment by sneumann** [comment]
Thanks for figuring out, so nothing xcms can do here.
Yours,
Steffen
