### ISSUE TITLE
Warnings: 'readMSData2' is deprecated.

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#201]
Hi, @lgatto has deprecated  `readMSData2` in MSnbase in this commit:
https://github.com/lgatto/MSnbase/commit/6e6062a722f88044b8dd70335b5744efafb5bcbd
and we get a WARNING:
```
* checking examples ... WARNING
Found the following significant warnings:
  Warning: 'readMSData2' is deprecated.
  Warning: 'readMSData2' is deprecated.
```

**Comment by jotsetung** [comment]
I'll fix that - am just some days without internet access...

**Comment by lgatto** [comment]
See PR #203
