### ISSUE TITLE
Metlin links returned by diffreport do not work

### ISSUE THREAD

**Issue by etrh** [sneumann/xcms#204]
It seems that the structure of the website has changed and therefore all the links returned by _diffreport_ only lead to a 404 error.

Example: http://metlin.scripps.edu/metabo_list.php?mass_min=200.9&mass_max=201.2

**Comment by sneumann** [comment]
Hi, can you try to give an example of a working URL on the metlin website
for the above query ? Then I can adapt the link. Thx, Steffen

**Comment by etrh** [comment]
Here is an example of a submitted query with the following attributes:

```
Mass: 200
Tolerance: 5 ppm
Charge: Positive
Adducts: M+H
```

https://metlin.scripps.edu/simple_search_result.php?mass_mid=200&mass_tol=5&mass_mode=1&AminoAcid=add&toxinEPA=add&adducts=M%2BH

Here's another one

```
Mass: 418.2931
Tolerance: 0.01 DA
Charge: Positive
Adducts: M+H and M+Na
```

https://metlin.scripps.edu/simple_search_result.php?mass_mid=418.2931&mass_tol=0.01&mass_mode=0&AminoAcid=add&toxinEPA=add&adducts=M%2BH,M%2BNa

**Comment by jotsetung** [comment]
Seems simply replacing `metabo_list.php` with `simple_search_result.php` should do the trick.

**Comment by jotsetung** [comment]
Thanks for the update @etrh . I updated the link.
