### ISSUE TITLE
Profparam step option in xcms3

### ISSUE THREAD

**Issue by adwolfer** [sneumann/xcms#206]
Hi all,

When running Centwave in xcms3 _(or xcms v1.52.0 with default step size)_ on some spiked compounds, the returned `mzmin`, `mzmax` are too tight and little to no data points fall into the m/z range _(equivalent to 5ppm)_, when passing the `rtmin`, `rtmax`, `mzmin`, `mzmax` values to `xcms::chromatogram`. 
Further tests in xcms v1.52 highlighted that reducing the step size greatly improved the m/z range returned by Centwave _(~80ppm)_, resulting in a well defined peak.

Is there a xcms3/MSnBase equivalent to "step size to use for profile generation" which is set in `xcmsRaw` as `profparam = list(step=0.005)` or `profstep = 0.005`?

`xcms v1.52.0, v2.99.6`
`MSnBase v2.3.9`

Thank you,
Arnaud Wolfer

**Comment by jotsetung** [comment]
Dear Arnaud,

could you please paste some example code on what you were doing? 

In xcms3 (and also older versions) centWave did never depend on the `profstep` parameter, peak detection is performed on the original data. The `getEIC` method on the other hand did extract the EICs from the profile matrix (= raw data binned in mz dimension by `profstep`). In xcms3 we are now extracting chromatograms also from the original data thus avoiding the additional generation of the profile matrix. Also, extracted chromatogram correspond now to the original data.

thanks, jo

**Comment by adwolfer** [comment]
Dear Jo,

Thanks for the quick reply. My bad, I can't reproduce the "improvement" with `profstep` so I must have mixed it up when testing in xcms 1.52.

I was originally chasing a problem where too little data points are present in the `mzmin` `mzmax` - `rtmin` `rtmax` range returned after `findChromPeaks`, when no ROI are provided:
In order to reproduce it, the following example is based on test sample with known spiked standards, and uses ROI as a reference. 
- First, I'm targeting the standard by providing a ROI and permissive Centwave parameters. The rt range covers the peak and m/z range returned is 197ppm wide. [(see here)](https://www.dropbox.com/s/7z573em5rpcyj3b/targeted_197ppm.png?dl=0)
- In the second case I employ the same Centwave parameters but don't provide a ROI. The standard is present in the found features, with identical rt range than in targeted, however the mz range (_8ppm_) is partly too tight resulting in dropped scans. [(see here)](https://www.dropbox.com/s/c8vevo8cnm9iuth/untargeted_8ppm.png?dl=0)

This "tighter" mz range is present for all features when looking for them without defining the ROI, it becomes problematic when I later use `chromatogram` to extract the intensity of features (not spiked). Is it an expected behaviour or due to the Centwave parametrisation passed?

The script used in this example is [available here](https://www.dropbox.com/s/68ibd1jj1i7ck46/minimal_example.R?dl=0), and the mzML file (215MB) [here](https://www.dropbox.com/s/87q1xt7m5rb3qx1/2fun_LTR.mzML?dl=0).

Thanks,
Arnaud

``` R
library(xcms)
print(packageVersion('xcms'))
# [1] '2.99.6'
library(MSnbase)
print(packageVersion('MSnbase'))
# [1] '2.3.9'
print(packageVersion('MzR'))
# [1] '2.11.7'

## Load ----
mzmlFile  <- './2fun_LTR.mzML'
rawSpec   <- MSnbase::readMSData(mzmlFile, centroided=TRUE, mode="onDisk")

## expected ROI ----
targetPeakList        <- data.frame(matrix(vector(), 1, 7, dimnames=list(c(), c("cpdName", "rtMin", "rt", "rtMax", "mzMin", "mz", "mzMax"))), stringsAsFactors=F)
targetPeakList[1,]    <- c("Std 1", 44.898, 50.4, 56.784, 115.9925, 116.0325, 116.0725)
targetPeakList[,2:7]  <- sapply(targetPeakList[,2:7], as.numeric)
#  cpdName  rtMin   rt  rtMax    mzMin       mz    mzMax
#1   Std 1 44.898 50.4 56.784 115.9925 116.0325 116.0725

ROIList   <- list(list(mz=targetPeakList$mz[1], mzmin=targetPeakList$mzMin[1], mzmax=targetPeakList$mzMax[1], scmin=which.min(abs(targetPeakList$rtMin[1]-MSnbase::rtime(rawSpec)))[[1]], scmax=which.min(abs(targetPeakList$rtMax[1]-MSnbase::rtime(rawSpec)))[[1]], length=-1, intensity=-1))
# [[1]]
# [[1]]$mz
# [1] 116.0325
#
# [[1]]$mzmin
# [1] 115.9925
#
# [[1]]$mzmax
# [1] 116.0725
#
# [[1]]$scmin
# [1] 260
#
# [[1]]$scmax
# [1] 331
#
# [[1]]$length
# [1] -1
#
# [[1]]$intensity
# [1] -1

## Targeted ----
CWParamTarg         <- xcms::CentWaveParam(roiList = ROIList, ppm = 20, snthresh = 3, noise = 400, prefilter = c(7,400), peakwidth = c(2,32), integrate = 1, verboseColumns = TRUE, fitgauss = TRUE)
resPeakSearchTarg   <- xcms::findChromPeaks(rawSpec, param = CWParamTarg)
# Detecting chromatographic peaks in 1 regions of interest ... OK: 1 found.
foundPeakTableTarg  <- data.frame(xcms::chromPeaks(resPeakSearchTarg))
#         mz    mzmin    mzmax     rt  rtmin  rtmax     into     intb     maxo    sn
# 1 116.0461 116.0314 116.0543 52.057 48.856 55.594 140220.3 140213.4 48517.44 48516
#       egauss       mu    sigma       h f dppm scale scpos scmin scmax lmin lmax sample
# 1 0.07503897 303.4667 6.467726 50481.7 1   35    10   304   294   314  284  324      1
#   is_filled
# 1         0

## Untargeted (no previous ROI) ----
CWParamUnTarg         <- xcms::CentWaveParam(ppm = 20, snthresh = 3, noise = 400, prefilter = c(7,400), peakwidth = c(2,32), integrate = 1, verboseColumns = TRUE, fitgauss = TRUE)
resPeakSearchUnTarg   <- xcms::findChromPeaks(rawSpec, param = CWParamUnTarg)
# Detecting mass traces at 20 ppm ... OK
# Detecting chromatographic peaks in 15214 regions of interest ... OK: 7439 found.
foundPeakTableUnTarg  <- data.frame(xcms::chromPeaks(resPeakSearchUnTarg))
## keep matching row
foundPeakTableUnTarg  <- foundPeakTableUnTarg[ (foundPeakTableUnTarg$rt > targetPeakList$rtMin[1]) & (foundPeakTableUnTarg$rt < targetPeakList$rtMax[1]) & (foundPeakTableUnTarg$mz > targetPeakList$mzMin[1]) & (foundPeakTableUnTarg$mz < targetPeakList$mzMax[1]), ]
#            mz    mzmin    mzmax     rt  rtmin  rtmax   into     intb     maxo  sn
# 2048 116.0321 116.0315 116.0324 52.057 48.856 55.594 139284 139096.7 48365.44 598
#          egauss       mu    sigma        h    f dppm scale scpos scmin scmax lmin
# 2048 0.07513889 303.4664 6.456133 50283.81 2874    1    10   304   294   314  272
#      lmax sample is_filled
# 2048  312      1         0

## Plot Feature ----
# Targeted, mzwidth:
(abs(foundPeakTableTarg$mzmax - foundPeakTableTarg$mzmin)/foundPeakTableTarg$mz)*1E6
# [1] 197.4307
plot(xcms::chromatogram(rawSpec, aggregationFun = "sum", rt = c(foundPeakTableTarg$rtmin, foundPeakTableTarg$rtmax), mz = c(foundPeakTableTarg$mzmin, foundPeakTableTarg$mzmax)))

# Untargeted, mzwidth:
(abs(foundPeakTableUnTarg$mzmax - foundPeakTableUnTarg$mzmin)/foundPeakTableUnTarg$mz)*1E6
# [1] 8.0218
plot(xcms::chromatogram(rawSpec, aggregationFun = "sum",  rt = c(foundPeakTableUnTarg$rtmin, foundPeakTableUnTarg$rtmax), mz = c(foundPeakTableUnTarg$mzmin, foundPeakTableUnTarg$mzmax)))
```

**Comment by jotsetung** [comment]
OK, so if I get it right you see that, providing a `ROIList` you find peaks that are broader in m/z dimension, while not providing it they are tighter. That is indeed interesting. I'll investigate that.

**Comment by jotsetung** [comment]
Here it helps to look at the complete raw data (mz, rt and intensity values):
```r
## Simpler extraction...
peak_1 <- chromPeaks(resPeakSearchTarg, mz = targetPeakList[1, c("mzMin", "mzMax")],
                       rt = targetPeakList[1, c("rtMin", "rtMax")])
peak_2 <- chromPeaks(resPeakSearchUnTarg, mz = targetPeakList[1, c("mzMin", "mzMax")],
                     rt = targetPeakList[1, c("rtMin", "rtMax")])

## Extract the mz, rt and intensity values
peak_data <- extractMsData(rawSpec, rt = targetPeakList[1, c("rtMin", "rtMax")],
                           mz = targetPeakList[1, c("mzMin", "mzMax")])[[1]]

par(mfrow = c(2, 1), mar = c(0, 4, 1, 1))
plot(peak_data$rt, peak_data$i, pch = 16, col = "grey", xaxt = "n",
     ylab = "intensity")
par(mar = c(4, 4, 0, 1))
plot(peak_data$rt, peak_data$mz, pch = 16, col = "grey", xlab = "rt",
     ylab = "m/z")

## highlight the region identified in the two peaks
rect(xleft = peak_1[1, "rtmin"], xright = peak_1[1, "rtmax"],
     ybottom = peak_1[1, "mzmin"], ytop = peak_1[1, "mzmax"], border = "#ff000080")
rect(xleft = peak_2[1, "rtmin"], xright = peak_2[1, "rtmax"],
     ybottom = peak_2[1, "mzmin"], ytop = peak_2[1, "mzmax"], border = "#0000ff80")
```

![rplot](https://user-images.githubusercontent.com/5506112/29447983-c1584ef4-83f4-11e7-82ad-41761378b752.png)

The peak identified by the *untargeted* approach (blue rectanble) looks actually better, the other (red rectangle) includes data points that seem to be relatively far of the m/z of your compound. Some data points at the beginning are still outside of the peak region (blue rectanble), but you could recover them by increasing the `ppm` parameter in the `CentWaveParam`.

Side note: as you can see above you can pass `mz` and `rt` values to the `chromPeaks` and `featureDefinitions` methods to extract only peaks/features that are overlapping with the provided ranges.

**Comment by adwolfer** [comment]
Hi Jo,

Thanks for the detailed answer.
If I get it right, the mz range provided in the `ROIList` is too permissive (in that case the `ppm` parameter is not employed). And in the _untargeted_ example the `ppm` provided is too small to recover the base of the peak (where the machine mass accuracy might be lower)

Cheers,
Arnaud

**Comment by jotsetung** [comment]
Correct - the `ppm` that you use as an parameter for centWave should be larger than the mass accuracy of the machine. I'm using `ppm = 50` for our ABI Sciex which (should) have a mass accuracy of 5-10ppm. I found the plot above quite useful to find the best setting for the `ppm` by looking at these plots for known compounds and spike ins.

Regarding the `ROIList`, I have to check that, but it could be that there is an issue with centWave not adjusting the mzrange properly (see issue #135).

cheers, jo

**Comment by adwolfer** [comment]
Thanks, we will adapt our parametrisation accordingly and follow the issue #135
Cheers,
Arnaud
