### ISSUE TITLE
Excessive amount of warnings from trimMz_Spectrum()

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#207]
Hi, as seen on https://travis-ci.org/sneumann/xcms/builds/265836488 ,
there is an excessive amount of Warnings from `trimMz_Spectrum()`
possibly in case of "mzmin==mzmax". 
Yours, Steffen
```
Applying retention time adjustment to the identified chromatographic peaks ... OK
Warning in trimMz_Spectrum(object, mzlim = mz, msLevel. = msLevel., ...) :
  No data points between 279 and 279 for spectrum with acquisition
number 131. Returning empty spectrum.
Warning in trimMz_Spectrum(object, mzlim = mz, msLevel. = msLevel., ...) :
  No data points between 279 and 279 for spectrum with acquisition
...
Warning in trimMz_Spectrum(object, mzlim = mz, msLevel. = msLevel., ...) :
  No data points between 279 and 279 for spectrum with acquisition
number 1278. Returning empty spectrum.
Requesting 176 missing peaks from wt15.CDF ... got 101.
```

**Comment by jotsetung** [comment]
That warning is kind of OK, since it's thrown if for a certain m/z range no values are present in the mzML file - I guess it comes from `chromatogram` calls, but am not sure. Have to investigate.

**Comment by jotsetung** [comment]
These warnings seem to be thrown in the vignette.

**Comment by jotsetung** [comment]
Should be fixed in the vignette now. Feel free to reopen if needed.
