### ISSUE TITLE
Allow keeping adjusted retention times in filterRt and filterMz

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#210]
Issue related to #208 
Add a parameter that allows to **keep** adjusted retention times even if the `XCMSnExp` object is sub-setted using `filterRt` or `filterMz`.

**Comment by jotsetung** [comment]
+ `filterMz` does not change or remove adjusted retention times (filtering is performed per spectrum).

**Comment by jotsetung** [comment]
+ `filterRt`: does not remove adjusted retention times. The function ensures that the correct adjusted retention times are kept.

**Comment by jotsetung** [comment]
+ `filterMsLevel`: as of now it does remove all pre-processing results (chromatographic peak detection, alignment and correspondence). This has to be changed to:
  - allow to keep adjusted retention times.
  - eventually keep chromatographic peaks for that MS level.

**Comment by michaelwitting** [comment]
What about `filterFiles` and `split`?

I use `split` to get the MS2 level splitted into the different SWATH pockets

```
# Use the fData method to access the "feature data" (i.e. the mzML header)
precursors <- fData(xrms_ms2)$precursorMZ

#split according to different SWATH windows
xrms_ms2_swath <- split(xrms_ms2, f = as.integer(precursors))```

**Comment by jotsetung** [comment]
`filterFile` has the argument `keepAdjustedRtime`, if that is set to `TRUE` (default is `keepAdjustedRtime = FALSE`) the adjusted retention times are kept.

Regarding `split`, is that the method for `xcmsSet`?

**Comment by michaelwitting** [comment]
yes it is the `split` for `XCMS`

**Comment by jotsetung** [comment]
OK, so eventually at some point I might implement one for `XCMSnExp` too.

**Comment by jotsetung** [comment]
Adjusted retention times are either not affected by the subsetting function (`filterRt`, `filterMz`), or an explicit parameter (`keepAdjustedRtime`) was allow to keep them (`filterFile`, `filterMsLevel`).
