### ISSUE TITLE
Filtering of functions derived from Waters DRE acquisitions

### ISSUE THREAD

**Issue by jaketmp** [sneumann/xcms#216]
Hi - we've run into an issue that seems to sit at an intersection between Waters multi-function raw data format, the way it's represented in mzML, and XCMS.

In short, we have data that is acquired with dynamic range extension - where the instrument acquires a full intensity and attenuated version of each scan, then stitches them together. In the `.raw` file these are represented much like the lock mass signal - as additional functions:

1) `_FUNC001.DAT` The stiched DRE function that combines 3 and 4)
2) `_FUNC002.DAT` The usual Waters lockmass
3) `_FUNC003.DAT` The high intesity scans
4) `_FUNC004.DAT` The low intesity scans

Currently ProteoWizard seems unable to generate mzML files correctly for this type of data  ([see here](https://sourceforge.net/p/proteowizard/bugs/16/)), and leaves us with an mzML file that contains function 2), 3), and 4).

On the XCMS side, it seems to make no distinction between functions when pulling out an EIC - resulting in a distinct sawtooth appearance where it interleaves the high and low intensity scans:
![pasted_image_at_2017_08_09_02_14_pm_720](https://user-images.githubusercontent.com/738903/29925658-e6dc14ee-8e58-11e7-9591-534fea1b0584.png)

Ideally we'd like to select only the relevant functions, either upon conversion to mzML, or on import into / initiating peak-detection  in XCMS - is this possible?

If you need any example data @adwolfer, @gscorreia89, or @nsadawi can help.

**Comment by jotsetung** [comment]
> Ideally we'd like to select only the relevant functions, either upon conversion to mzML, or on import into / initiating peak-detection in XCMS - is this possible?

This would be possible if each function is clearly indicated/labelled in the mzML - one could then subset the data to just that function. Would it be possible to get access to one of the mzML files?

Be aware that we are currently updating `xcms` to re-use base classes and I/O functionality from the `MSnbase`/`mzR` classes. So, changes might eventually be made to the `MSnbase` package too.

**Comment by jaketmp** [comment]
Thanks - this information seems to be encoded as `function=x` inside the `idRef=` atttribute of the `<offset>` elements under `<spectrum>` (though I couldn’t say if this is part of the mzML spec or specific to the proteowizard engine). 

    <index name="spectrum">
    <offset idRef="function=2 process=0 scan=1">9530</offset>
    <offset idRef="function=4 process=0 scan=1">47592</offset>
    <offset idRef="function=3 process=0 scan=1">176175</offset>
    <offset idRef="function=4 process=0 scan=2">187749</offset>
    <offset idRef="function=3 process=0 scan=2">308856</offset>
    <offset idRef="function=4 process=0 scan=3">319914</offset>
    <offset idRef="function=3 process=0 scan=3">441062</offset>
    <offset idRef="function=4 process=0 scan=4">451956</offset>
    <offset idRef="function=3 process=0 scan=4">573023</offset>

I’ll have the team dig out some example mzMLs and the source raws, where’s best to send them?

**Comment by jaketmp** [comment]
Also looks to be encoded similarly directly in the `<spectrum>` elements:

    <spectrum index="0" id="function=2 process=0 scan=1" defaultArrayLength="5873">

**Comment by jaketmp** [comment]
Example raw and mzML version [here](https://www.dropbox.com/sh/hw9tmaldoi155v7/AACJtZNXOhXFQrIUr_yn940fa?dl=0).

**Comment by jotsetung** [comment]
Thanks for the file. I checked now and as you mentioned above, at present the only way to relate a spectrum to a function is *via* its ID. It would be rather simple to split/filter an `OnDiskMSnExp` object if this information would be available.

I've thus filed an issue in `mzR`: https://github.com/sneumann/mzR/issues/124

**Comment by jotsetung** [comment]
OK, with the recent changes in mzR you can now split your data based on the function:
```r
## First ensure we have the most recent mzR
library(BiocInstaller)
useDevel()
biocLite("mzR")
## Also update MSnbase and xcms to be on the save side
biocLite(c("MSnbase", "xcms"))

## Read the file.
library(MSnbase)
full_data <- readMSData("./4fun_LTR.mzML", mode = "onDisk")

## Get access to the spectrum metadata:
head(fData(full_data))

## Can use $spectrumId to separate the spectra:
fun_2 <- grep(fData(full_data)$spectrumId, pattern = "^function=2")
fun_2_data <- full_data[fun_2]
fun_3 <- grep(fData(full_data)$spectrumId, pattern = "^function=3")
fun_3_data <- full_data[fun_3]
fun_4 <- grep(fData(full_data)$spectrumId, pattern = "^function=4")
fun_4_data <- full_data[fun_4]

## Extract a chromatogram
mzr <- c(398.2281, 398.2382)
rtr <- c(30, 37)
chr_2 <- chromatogram(fun_2_data, mz = mzr, rt = rtr)
plot(chr_2)
chr_3 <- chromatogram(fun_3_data, mz = mzr, rt = rtr)
plot(chr_3)
chr_4 <- chromatogram(fun_4_data, mz = mzr, rt = rtr)
plot(chr_4)
```

@jaketmp let me know if this works for you.

**Comment by adwolfer** [comment]
@jotsetung That works perfectly. We might also use it to remove the LockMass signal before processing.

Given the fields returned by `fData()` when loading files `inMemory`, it won't be possible to subset the data based on the functions?

**Comment by jotsetung** [comment]
Yes you are right - didn't realize that. The `MSnExp` objects (i.e. `"inMem"` mode) don't provide any additional spectrum header data. But don't be afraid to use `OnDiskMSnExp` :) 

Also, if you want to use methods from the `xcms` package you'll need to have an `OnDiskMSnExp`.
