### ISSUE TITLE
read from .mzdata.xml.gz files

### ISSUE THREAD

**Issue by colinbrislawn** [sneumann/xcms#217]
I'm importing data using the following command:

```
xcmsSet(c('./Example/C12/', './Example/C13/') ...)
```

This command works great on `mzdata.xml` files, but fails on `mzdata.xml.gz` files. 

I'm not sure if I should submit this as a bug report of a feature request. Or maybe there is a better way to use `gz` files, or a compelling reason not to.

Thank you for writing this software. I really appreciate your guidance.

**Comment by sneumann** [comment]
Hi, reading `*.gz' works in mzR, see
https://github.com/sneumann/mzR/blob/master/inst/unitTests/test_ramp.R#L69
and https://github.com/sneumann/mzR/blob/master/inst/unitTests/test_pwiz.R#L121
and indeed older xcms fails to read these:
```
> library(xcms)
> f <- system.file("proteomics/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz", package = "msdata")
> xr <- xcmsRaw(f)
Error in readChar(filename, 1024) : invalid UTF-8 input in readChar()
```
Good news is that the newer xcms (I am running 2.99.6) supports this:
```
> xr <- xcmsRaw(f)
Create profile matrix with method 'bin' and step 1 ... OK

> raw_data <- readMSData(f)
> raw_data
MSn experiment data ("MSnExp")
Object size in memory: 3.27 Mb
- - - Spectra data - - -
 MS level(s): 2 
 Number of spectra: 451 
 MSn retention times: 18:29 - 22:2 minutes
- - - Processing information - - -
Data loaded: Wed Sep  6 21:22:47 2017 
 MSnbase version: 2.3.9 
- - - Meta data  - - -
phenoData
  rowNames:
    TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01.mzML.gz 
protocolData: none
featureData
  featureNames: F1.S001 F1.S002 ... F1.S451 (451 total)
  fvarLabels: spectrum
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
```

Please close if that was helpful.

Yours, Steffen

**Comment by colinbrislawn** [comment]
Ah OK. I'm using the versions currently available on bioconductor:

```
>packageVersion("xcms")
[1] ‘1.52.0’
> packageVersion(c("mzR"))
[1] ‘2.10.0’
```

I guess I'll have to wait for full release of xcms3!
