### ISSUE TITLE
Error in (function (classes, fdef, mtable)  :    unable to find an inherited method for function ‘chromatogram’ for signature ‘"OnDiskMSnExp"

### ISSUE THREAD

**Issue by NebuchadnezzaraHardrada** [sneumann/xcms#218]
[SessionInfo.txt](https://github.com/sneumann/xcms/files/1289843/SessionInfo.txt)
 For an in-depth documentation of the problems, please look at the text file attached, which contains the output from the console.

Every time I create a character vector and then enter it as the first input for raw_data, a few lines of code down the line, R or the functions of xcms will not be able to find the file. The problem persists even if I reset the working directory or point R exactly where the files are.

Is there a convention on the kind of mzXML files that XCMS accepts ? At one point, my files were rejected by the findChromPeaks function because they were supposedly not centroided ? Are there specific rules for conversion of files via MSConvert(ProteoWizard) for XCMS functions ? Should files be mzML or mzXML, 32bit or 64bit ? With or withour zlib compression ? With or without Vendor picking ?
[XCMSErrors.txt](https://github.com/sneumann/xcms/files/1289837/XCMSErrors.txt)

**Comment by jotsetung** [comment]
Most (if not all of your problems) are related to the `xcms` version you are using. Most methods/functionality has been added very recently and is only available in the developmental branch of Bioconductor.
To use that either:
+ install selected packages from github:
```r
library(devtools)
install_github("sneumann/mzR")
install_github("lgatto/MSnbase")
install_github("sneumann/xcms")
```
+ Use the Bioconductor developmental branch:
```r
library(BiocInstaller)
useDevel()
biocLite()
```

Regarding your other questions: the centwave peak detection requires centroided data. You have convert profile-mode mzML (or vendor file format) to centroided data outside of R, using, e.g. proteowizard.
Regarding the type of mzML/mzXML files, there should not be any problem. The data is read using the `mzR` package that (in the recent, developmental, version) uses the proteowizard libraries to read mzML/mzXML files. So, no restriction regarding 32bit, 64 bit, compressed etc.

**Comment by NebuchadnezzaraHardrada** [comment]
[XCMSErrors2.txt](https://github.com/sneumann/xcms/files/1290873/XCMSErrors2.txt)
The problem is still persisting. I followed the instructions on the reinstallation of all the packages and  the MsnBase installation command failed. I also then tried running a few lines of code as you showed on  the tutorial page on bioconductor but could still not plot the chromatograms. I am still getting the same error. I have attached the output of my console as a text file for your review. The session info is the exact same as the last one.

**Comment by jotsetung** [comment]
`MSnbase` failed to update. You could try the second suggestion from above and switch to the Bioconductor developmental branch:
```r
library(BiocInstaller)
useDevel()
biocLite()
biocLite(c("MSnbase", "mzR", "xcms"))
```

All the new functionality (e.g. `chromatogram` method) will **only** work if you successfully updated the newest versions of the packages.

**Comment by NebuchadnezzaraHardrada** [comment]
I have tried following the instrunctions above but none of these solutions work. The code is just not installing the packages at all or is installing one but never all of them. The above code actually deleted all the versions of MSnbase, mzR and XCMS that I had and did not replace them. Is there another easier method ?  I have attached a text file with the errors that I am receiving.

[XCMSErrors3.txt](https://github.com/sneumann/xcms/files/1292349/XCMSErrors3.txt)

**Comment by jotsetung** [comment]
First of all it would be nice if you could just paste the error message in the form without attaching it as a txt.

I don't know your R setup and configuration but this seems to be a basic R package installation problem that is not directly related to `xcms` or `MSnbase`.
It would be nice if you provided the exact code you used and the output you got. It seems e.g. strange that `biocLite` or `install.packages` removes installed packages without installing them. AFAIK the functions first try to install the package and only remove the old version if the new version can be installed.

Regarding an easier method - this is already the easiest (and best) method that does also ensure that not only the package itself, but also all required dependencies are installed.

Please run:
```r
source("https://bioconductor.org/biocLite.R")
useDevel()
biocLite("mzR")
biocLite("MSnbase")
biocLite("xcms")
```
and paste its output in the comment (do not attach it as a txt file please)

**Comment by NebuchadnezzaraHardrada** [comment]
I just installed all three packages using the instructions above and all packages were successfully installed. I then tried running the following code to see if the function would work ( I used one file instead of many to make the workflow and example easier)
x<-"E:/Data/Kundai/RStudio/XCMS/Eta6.mzXML"
raw_data<-readMSData2(x)
bpis <- chromatogram(raw_data, aggregationFun = "max")

These are the following errors I got  : 
> raw_data<-readMSData2(x)
Warning message:
'readMSData2' is deprecated.
Use 'readMSData(..., mode = "onDisk")' instead.
See help("Deprecated")

bpis <- chromatogram(raw_data, aggregationFun = "max")
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’

I have to admit that I am no expert in R and so most of these errors might arise from my stupidity and lack of intricate understanding of the language. 

When I specifically use "chromatogram" function from  MSnBase, I get the following error:
> bpis <- Chromatogram(raw_data, aggregationFun = "max")
Error in subsetFeatureDataBy(featureData(x), index = i) : 
  Provided indices are outside of the allowed range.
In addition: Warning message:
In is.na(<S4 object of class "OnDiskMSnExp">) :
  is.na() applied to non-(list or vector) of type 'S4'

When I use the chromatogram function from xcms, the plot window freezes indefinitely whilst the console shows that it can accept more input.

**Comment by jotsetung** [comment]
To get rid of the deprecation warnings: use `readMSData(x, mode = "onDisk")`.

Regarding the message *Found more than one class "Chromatogram"*, that's a little disturbing. Please make sure: close R and restart it. Don't load any previous history or saved workspace. Make sure you don't have a `.RData` file in the working directory you load, these get usually autoloaded.

Note also that the function is called `chromatogram`, but the **object** `Chromatogram`. Use the `chromatogram` function to extract a `Chromatogram` object from the `OnDiskMSnExp` (`raw_data`).

What do you mean with *When I use the chromatogram function from xcms, the plot window...*? Calling `chromatogram` takes some time (because the raw data is read from the file) and yes, during that time all plot windows freeze. To speed up the process `MSnbase` reads data in parallel. Try to switch that off by calling (right after you started R and loaded the libraries):
```
library(MSnbase)
library(xcms)
register(SerialParam())
```

**Comment by NebuchadnezzaraHardrada** [comment]
Restarted R and deleted all the history files on my pc. The deprecation warnings are now gone. Here is the code that I used in R studio.
library(MSnbase)
library(xcms)
register(SerialParam())
x<-"E:/Data/Kundai/RStudio/XCMS/Eta6.mzXML"
raw_data<-readMSData(x, mode="onDisk")
bpis <- chromatogram(raw_data)
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’
Found more than one class "Chromatogram" in cache; using the first, from namespace 'MSnbase'
Also defined by ‘xcms’

Whenever one types in "chromatogram", multiple options come up which I suspect means that both packages (XMCS) and MSnBase have the function. Below is a documentation of the errors I receive whenever I use any one of them.
> bpis <- Chromatogram(raw_data)
Error in subsetFeatureDataBy(featureData(x), index = i) : 
  Provided indices are outside of the allowed range.
In addition: Warning message:
In is.na(<S4 object of class "OnDiskMSnExp">) :
  is.na() applied to non-(list or vector) of type 'S4'

> bpis <- Chromatograms(raw_data)
Error in as.vector(data) : 
  no method for coercing this S4 class to a vector

Do I need to load the S4 vector library as well ? I came across this script:
http://bioconductor.org/packages/devel/bioc/vignettes/xcms/inst/doc/new_functionality.html#12_new_naming_convention
and also have to mention that everytime I run code including "$" as a substitute to the chromatogram function, there is an error message on the use of the symbol and it says "80" is an unknown colour.

**Comment by jotsetung** [comment]
You are mixing things up. The **function** is called `chromatogram` (lower case), the class/object that contains the chromatogram data is called `Chromatogram` (and `Chromatograms`). While there is a constructor function `Chromatogram` and `Chromatograms`, you should not use them. What you want is to extract chromatographic data from `raw_data`. To do so, just use the `chromatogram` function you already used. There is no need for you to call `Chromatogram` or `Chromatograms` unless you want to create **new** objects.

Some details about the history of these functions/classes that might explain the `Found more than one class...`: I first implemented the `Chromatogram` class and `chromatogram` function in `xcms` because I needed it. I met then Laurent (the developer from `MSnbase`) at a workshop and we decided to move the function and class to the `MSnbase` package, to make it part of its common MS infrastructure. Now, you are still getting the messages which tells that you might have somewhere an older version of `xcms` installed. You could try to force installation of `xcms` from github (don't know if that's possible at all under Windows):
```r
library(devtools)
install_github("sneumann/xcms")

```
If that fails ensure again that the newest from the Bioconductor devel branch is installed:
```r
library(BiocInstaller)
biocLite("xcms")
```

In the end it should be OK even if the message still shows up.

**Comment by NebuchadnezzaraHardrada** [comment]
Thank you for the help and commitment to answering my questions. Everything now works perfectly, I managed to plot a chromatogram. Cheers

**Comment by jotsetung** [comment]
Great! good to hear! I'll close the issue then.
