### ISSUE TITLE
Error in CentWaveParam(snthresh = 20, noise = 1000) :    could not find function "CentWaveParam"

### ISSUE THREAD

**Issue by NebuchadnezzaraHardrada** [sneumann/xcms#219]
For some reason, the centwave function is no longer available. I tried it on the previous version of XCMS and it worked, but somehow now, R cannot find it.

> cwp <- CentWaveParam(snthresh = 20, noise = 1000)
Error in CentWaveParam(snthresh = 20, noise = 1000) : 
  could not find function "CentWaveParam"

Error in findChromPeaks(raw_data, param = cwp) : 
  could not find function "findChromPeaks"

Error in chromPeaks(xod, rt = rtr, mz = mzr) : 
  could not find function "chromPeaks"

**Comment by stanstrup** [comment]
Output of `sessionInfo()`?

**Comment by NebuchadnezzaraHardrada** [comment]
I have had the same exact problem for the last two days but it was instead with the "chromatogram" function. Two days ago, the version of xcms I had could easily find centwave function but not the chromatogram function. Johannes Rainer then fixed the issue but then unfortunately, it seems as if in fixing the issue, some of the functions were misplaced or something.

─ Session info ────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2017-09-13                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────
 package        * version  date       source                            
 affy             1.55.0   2017-05-01 Bioconductor                      
 affyio           1.47.1   2017-09-05 Bioconductor                      
 Biobase        * 2.37.2   2017-05-04 Bioconductor                      
 BiocGenerics   * 0.23.1   2017-09-04 Bioconductor                      
 BiocInstaller    1.27.4   2017-09-04 Bioconductor                      
 BiocParallel   * 1.11.6   2017-08-05 Bioconductor                      
 clisymbols       1.2.0    2017-05-21 CRAN (R 3.4.1)                    
 codetools        0.2-15   2016-10-05 CRAN (R 3.4.1)                    
 colorspace       1.3-2    2016-12-14 CRAN (R 3.4.1)                    
 digest           0.6.12   2017-01-27 CRAN (R 3.4.1)                    
 doParallel       1.0.10   2015-10-14 CRAN (R 3.4.1)                    
 foreach          1.4.3    2015-10-13 CRAN (R 3.4.1)                    
 ggplot2          2.2.1    2016-12-30 CRAN (R 3.4.1)                    
 gtable           0.2.0    2016-02-26 CRAN (R 3.4.1)                    
 impute           1.51.0   2017-05-01 Bioconductor                      
 IRanges          2.11.15  2017-09-08 Bioconductor                      
 iterators        1.0.8    2015-10-13 CRAN (R 3.4.1)                    
 lattice          0.20-35  2017-03-25 CRAN (R 3.4.1)                    
 lazyeval         0.2.0    2016-06-12 CRAN (R 3.4.1)                    
 limma            3.33.7   2017-07-31 Bioconductor                      
 MALDIquant       1.16.4   2017-09-01 CRAN (R 3.4.1)                    
 MSnbase        * 2.3.10   2017-09-08 Bioconductor                      
 munsell          0.4.3    2016-02-13 CRAN (R 3.4.1)                    
 mzID             1.15.0   2017-05-01 Bioconductor                      
 mzR            * 2.11.8   2017-09-09 Bioconductor                      
 pcaMethods       1.69.0   2017-05-01 Bioconductor                      
 plyr             1.8.4    2016-06-08 CRAN (R 3.4.1)                    
 preprocessCore   1.39.3   2017-09-05 Bioconductor                      
 ProtGenerics   * 1.9.0    2017-05-01 Bioconductor                      
 RColorBrewer   * 1.1-2    2014-12-07 CRAN (R 3.4.1)                    
 Rcpp           * 0.12.12  2017-07-15 CRAN (R 3.4.1)                    
 rlang            0.1.2    2017-08-09 CRAN (R 3.4.1)                    
 S4Vectors        0.15.7   2017-09-07 Bioconductor                      
 scales           0.5.0    2017-08-24 CRAN (R 3.4.1)                    
 sessioninfo      1.0.1    2017-09-08 Github (r-lib/sessioninfo@e813de4)
 tibble           1.3.4    2017-08-22 CRAN (R 3.4.1)                    
 vsn              3.45.2   2017-08-14 Bioconductor                      
 withr            2.0.0    2017-07-28 CRAN (R 3.4.1)                    
 xcms           * 1.47.2   2017-09-12 Github (sneumann/xcms@8614720)    
 XML              3.98-1.9 2017-06-19 CRAN (R 3.4.1)                    
 zlibbioc         1.23.0   2017-05-01 Bioconductor

**Comment by jotsetung** [comment]
well - you have `xcms` version 1.47.2 installed. Funny that this comes from github. My only explanation is that `install_github` installed the *master* branch, which is quite outdated. Sorry, that was my fault. You should ideally install the *devel* branch, or the *xcms3* branch:
```r
devtools::install_github("sneumann/xcms", ref = "xcms3")
```

**Comment by NebuchadnezzaraHardrada** [comment]
Solved, thanks for the quick response.

**Comment by NebuchadnezzaraHardrada** [comment]
Not really, I got this error, maybe its because I am actually not using any "groups", but instead, 3 files just to test out the whole software before expanding.

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘groupChromPeaks’ for signature ‘"XCMSnExp", "missing"’

**Comment by jotsetung** [comment]
you have to provide a parameter object as a second argument with the `groupChromPeaks` method. Check the help on the `groupChromPeaks` method.

**Comment by NebuchadnezzaraHardrada** [comment]
Thank you. You may now close the issue.
