### ISSUE TITLE
Problems with filterMsLevel 

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#222]
Hi,

I wanted to work on a multi-file solution for my SWATH/DIA data instead of processing every file individually and checked the retention time alignment.

Currently, I'm reading my data like this:

`xrms <- readMSData(c("Bruker.mzML", "Bruker2.mzML"), mode = "onDisk", centroided = TRUE)`

and afterwards I filter according to the MS Level

```
xrms_ms1 <- filterMsLevel(xrms, msLevel = 1)
xrms_ms2 <- filterMsLevel(xrms, msLevel = 2)
```

However, with this I'm loosing the link between MS1 and MS2 data and every retention time alignment for the MS1 does not apply for MS2. I performed peak picking and alignment and tried to split afterwards, but the correspoding XCMSnExp object is empty.

```
cwp <- CentWaveParam(snthresh = 5, noise = 100)
ms1data <- findChromPeaks(xrms, param = cwp)
ms1data_aligned <- adjustRtime(ms1data, param = ObiwarpParam(), msLevel = 1)
ms2data <- filterMsLevel(ms1data, msLevel = 2)
precursors <- fData(ms2data)$precursorMZ
```
Any ideas?

**Comment by jotsetung** [comment]
Performing the MS1 peak detection and alignment on the MSn data set (`xrms`) is correct, only that way you can ensure that the retention time correction (on MS1 in your case) is applied also on the MS2 spectra.

What do you mean with the `XCMSnExp` after `filterMsLevel` is empty? `filterMsLevel` does drop identified chromatographic peaks but should keep the adjusted retention times.

Note that so far `findChromPeaks` does only identify chromatographic peaks on one MS level and does also drop any previously identified peaks. For your example I would suggest:
```r
cwp <- CentWaveParam(snthresh = 5, noise = 100)
ms1data <- findChromPeaks(xrms, param = cwp)
ms1data_aligned <- adjustRtime(ms1data, param = ObiwarpParam(), msLevel = 1)
ms2data <- filterMsLevel(ms1data, msLevel = 2)
## Perform also peak detection on MS level 2:
ms2data <- findChromPeaks(ms2data, param = CentWaveParam())
```
the `ms1data` should thus contain the peaks in MS1 and the `ms2data` those on MS2.

Let me know if that does not work.

**Comment by michaelwitting** [comment]
Thanks for the answer. But the Problem is that the data is really empty:

```
> ms1data@featureData
An object of class 'AnnotatedDataFrame'
  rowNames: F1.S00001 F1.S00002 ... F3.S16039 (1917 total)
  varLabels: fileIdx spIdx ... spectrum (26 total)
  varMetadata: labelDescription
> ms2data@featureData
An object of class 'AnnotatedDataFrame': none
```

I used exactly the from you code above.

**Comment by jotsetung** [comment]
You are right - that's a bug in `findChromPeaks` that removes all MS2 spectra from the object and returns just the MS1.
I'll fix that. Thanks for reporting!

**Comment by michaelwitting** [comment]
Thanks. I guess with that fixed I'm quite close to a running SWATH/DIA workflow.

**Comment by jotsetung** [comment]
Should be fixed in the latest version in the `xcms3` branch. Let me know if it works (or not).

**Comment by michaelwitting** [comment]
I'm getting the follwing error:

```
> ms1data <- findChromPeaks(xrms, param = cwp, msLevel = 1)
Error: BiocParallel errors
  element index: 1, 2, 3
  first error: File Bruker.mzML not found.
```

Only with multiple files in the xrms object

**Comment by jotsetung** [comment]
That is strange! I'll try to reproduce...

**Comment by jotsetung** [comment]
Can not reproduce - you are on Windows and use `SnowParam`? Can only speculate that the R processes that are spawned by snow-based parallel processing have a different working directory (don't know why, however). I suggest that you provide the full path to the files, with that it must work.
```r
xrms <- readMSData(normalizePath(c("Bruker.mzML", "Bruker2.mzML")), mode = "onDisk", centroided = TRUE)
```
If that works I make a pull request in `MSnbase` to add the `normalizePath` call within `readMSData`.

**Comment by michaelwitting** [comment]
Looks like that was the problem. I started today with a fresh R session and loaded the `SnowParam` in my actual working directory and it worked.
Anyway it would be good to have the `normalizePath` call within `readMSdata` to prevent such things.

**Comment by jotsetung** [comment]
Cool! Thanks for testing! I'll make an issue/pull request then in `MSnbase`.
