### ISSUE TITLE
Exract all MS2 spectra from data dependent acquisition

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#229]
Hi,

I have a short question: Is there a fast way to get all MS2 spectra from a `XCMSnExp`, e.g. as list of `Spectrum2` objects? I like working with the `Spectrum2` objects since there is a Mgf writer and data is stored very organized.

Best regards,

Michael

**Comment by jotsetung** [comment]
Jup: `spectra(filterMsLevel(x, msLevel = 2))`. Eventually you should/would use also `keepAdjustedRtime = TRUE` (although that should be `TRUE` anyway if you performed retention time correction).

**Comment by michaelwitting** [comment]
Thanks! Works perfect.
