### ISSUE TITLE
Extract EIC from individual files

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#231]
Hi,

I would like to get all EICs from one particular file in my `XCMSnExp `object. 
Currently, I'm using this line, which generates all the EICs for all files in ms1data_swath.
`testChrom <- chromatogram(ms1data_swath, mz = workingList[,2:3], rt = workingList[,5:6])`
I can filter the individual `chromatogram` objects afterwards from which file they originate, but would be nice to safe time if there is a selection upfront. `filterFile` drops the `adjustedRtime` and is therefore no option.

Best regards,

Michael

**Comment by jotsetung** [comment]
Actually, the `filterFile` has the optional parameter `keepAdjustedRtime`. If you set that one to `TRUE` you can used `filterFile` up front and then call `chromatogram`:
`testChrom <- chromatogram(filterFile(ms1data_swath, file = 1, keepAdjustedRtime = TRUE), mz ...)`.

**Comment by michaelwitting** [comment]
Okay. That was not too obvious from the help. Thanks!

**Comment by jotsetung** [comment]
I know. I tried to extend the help pages on that (xcms version >= 2.99.10) (in `filterFile` there is now a mention of this argument) and I added a section (8.2) to the `xcms` vignette describing the subsetting of the `XCMSnExp` object.
