### ISSUE TITLE
Missing phenoData<-() function

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#245]
Hi, if I can obtain a phenoData, I should be able to assign one:
```
xmse <- new("XCMSnExp")
nadf <- phenoData(xmse)
phenoData(xmse) <- nadf
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘phenoData<-’ for signature ‘"XCMSnExp", "NAnnotatedDataFrame"’
```

or did I confuse that with `pData()` since the following works:
```
odmse <- new("OnDiskMSnExp")
nadf <- phenoData(odmse)
phenoData(odmse) <- nadf
```

Yours, Steffen

**Comment by sneumann** [comment]
This works:
```
ps <- new("MSnSet")
padf <- phenoData(ps)
phenoData(ps) <- padf
```

**Comment by jotsetung** [comment]
Indeed. A `pData` method that takes a `data.frame` is implemented, but the `phenoData` for `AnnotatedDataFrame` or `NAnnotatedDataFrame` is missing for `OnDiskMSnExp`. I created an issue over in `MSnbase` (https://github.com/lgatto/MSnbase/issues/299).

**Comment by jotsetung** [comment]
This has been fixed in `MSnbase`.
