### ISSUE TITLE
Code duplication and XCMSnExp2xcmsSet function

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#246]
Hi, the different `findChromPeaks()` in methods-OnDiskMSnExp.R
have quite some code duplication to handle different `return.type`s.
If there was a (common and exported) `pSet2xcmsSet()` or `XCMSnExp2xcmsSet()`,
then this would 1) reduce some code duplication and 2) be able to also convert
grouped and retention time adjusted `XCMSnExp`s to `xcmsSet`s.

For ease of implementation, this could be restricted to straight-forward 
use cases, and mainly to do all xcms processing in the "new" interface, 
and still be able to pass on the converted `xcmsSet` to CAMERA.

Yours, Steffen

**Comment by jotsetung** [comment]
Good point. I'll look into this. Note also that it is possible to coerce a `XCMSnExp` into `xcmsSet` using `xset <- as(x, "xcmsSet")` with `x` being an `XCMSnExp`. It is thus possible to perform all the preprocessing using the new methods/classes and in the end get the old result object.

In the long run I would also like to add support for `XCMSnExp` in `CAMERA`.

**Comment by sneumann** [comment]
Very good. I haven't checked results yet, but after `xs <- as(xmsnexp, "xcmsSet")` 
CAMERA is happy to process the resulting `xs`. With the most pressing problem already fixed, 
that leaves the code duplication somewhat on the back-burner. Thx, Steffen

**Comment by jotsetung** [comment]
All done (also reduced code duplication).

**Comment by jotsetung** [comment]
Closing now. Feel free to reopen if needed.
