### ISSUE TITLE
Concatenate XCMSnExp 

### ISSUE THREAD

**Issue by lecorguille** [sneumann/xcms#247]
Hi,

In XMCS3, is there an equivalent to 
```
xset = c(xset1, xset2, xset3, xset4)
```

The idea is to launch as many `findChromPeaks` as number of sample. Then merge the _n_ XCMSnExp into one before `adjustRtime`

**Comment by jotsetung** [comment]
No, at present there is no way to concatenate `XCMSnExp` objects. Note that if parallelization is the only reason you want to do this - `xcms` does now by default parallelize the chromatographic peak detection. See http://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html#83_parallel_processing for details on how to perform the parallel processing. I would however not make the parallel processing dependent on the number of samples, but rather on the number of CPUs you have - also, note that, while multiple files/samples can be processed in parallel, there will at some point be an I/O bottleneck, because `findChromPeaks` has to load the data for each file prior to peak detection, if you have thus e.g. 8 processes running in parallel, 8 files will be read at the same time which can have a negative impact on performance (also note that you will need more memory the more files you are processing in parallel).

**Comment by sneumann** [comment]
Hi, just for some background, Gildas is working on the Galaxy W4M, where xcms + CAMERA are used.
Current xcms parallelisation is either limited to a single computer, or an BiocParallel compatible cluster setup. 
In W4M parallelisation is handled by Galaxy, hence we had implemented the 'forearch (oneFile in allFiles)  oneFileXS <- xcmsSet(oneFile) ; xs <- c(list(oneFileXS))` logic. So `c(XCMSnExp)` would still be a good thing to have here.

@lecorguille you will also need the `mtbls2Set <- as(mtbls2groupedFilled, "xcmsSet")` from 
https://bioconductor.org/packages/devel/data/experiment/vignettes/mtbls2/inst/doc/MTBLS2-xcms3.html
as CAMERA is (not yet) upgraded to the XCMS3 interface.

**Comment by jotsetung** [comment]
I see - OK, I'll open an issue on that.

**Comment by lecorguille** [comment]
@sneumann Many thanks for your support. Because indeed, I'm using the trick you have shown me at Saclay.
So if it's not already implemented how to you solve this in the tool `xcms-collect-peaks Combine XCMS-Set objects into one collection used for further processing.` available within the Phenomenal Galaxy instance? Is it still some `xcmsset` objects behind?

**Comment by jotsetung** [comment]
Done. Now there's a `c` method for `XCMSnExp` objects. To use this please install the most recent `xcms` from github (`devtools::install_github("sneumann/xcms", "master")`.

@sneumann , any plans to push to the github `master` branch to bioconductor?

**Comment by lecorguille** [comment]
@jotsetung 
Impressive, you are really reactive!
I will test that ASAP :)

**Comment by jotsetung** [comment]
Let me know if you have other questions or run into problems.

**Comment by lecorguille** [comment]
Whouaw ... 
https://github.com/sneumann/xcms/blob/master/DESCRIPTION#L18
```
Imports:
    mzR (>= 2.13.1),
```

On which version of R do you manage to install that?
It seems to need [bioconductor-3.7](https://bioconductor.org/packages/3.7/bioc/html/mzR.html) which need [`R (>= 3.5.0)`](https://bioconductor.org/packages/3.7/bioc/html/BiocInstaller.html)

My concern is that for our Galaxy tools, we are using the recommended [Conda package](https://bioconda.github.io/recipes/bioconductor-xcms/README.html) for [our dependencies](https://github.com/workflow4metabolomics/xcms#dependencies-using-conda). 
Currently the last version of R supported by Bioconda and Conda-Forge is [`CONDA_R: "3.4.1"`](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml#L7)

So, _in fine_, do you know which version of R will be mandatory after your push of the `master` to bioconductor? I hope it won't be to high 😕

**Comment by sneumann** [comment]
Hi, I am running it on R-3.4.2, and don't see a reason why it shouldn't run on 3.4.1.
What *could* be difficult is that `biocLite()` won't install mzR-2.13.1 on R-3.4.x,
so we'd need to see how to "backport" (i.e. force) the package versions into CONDA_R: "3.4.1".
Yours, Steffen

**Comment by lecorguille** [comment]
The installation was a real pain 😕 
Indeed, I don't have any latitude with the compilers versions, we are stuck with old ones. I'm largely use Conda for that.
So for this specific testing purpose, I downgraded `mzR` to [`2.12.0`](https://github.com/lecorguille/xcms/blob/f59d5781d3f7a00f1ff229264928c365164b07d2/DESCRIPTION#L19) in my fork because it's already available in Conda.
```
Imports:
    mzR (== 2.12.0),
```

So FYI
```
conda create -n bioconductor-3.0.0b bioconductor-xcms==3.0.0 devtools
. activate bioconductor-3.0.0b
R
> devtools::install_github("lecorguille/xcms", "master")
```


But eventually ... the `c()` works very well
Many thanks!

**Comment by jotsetung** [comment]
I know, it's tricky with the required versions of `R` and Bioconductor. The xcms `master` branch is (and will always be) in line with the current developmental version of Bioconductor (3.7 at present, which depends on R 3.5 devel). Basically we should only add new features in the `master` branch and do bug fixes in the release branches (e.g. Bioconductor 3.6 release).

If needed (and @sneumann agrees) I can add certain stuff like the `c` function or the `groupnames` into the release branch - then it's up to Steffen to push that to Bioconductor.

**Comment by lecorguille** [comment]
I completely understand your point of view and the bioconductor workflow.
If I add to the date of bioconductor 3.7 release, the time for conda-forge to release R 3.5, the time for bioconda to rebuild every package for the 3.5... Hum, ... it should be ready for Xmas!

Note that `c` is somehow mandatory for me. Whereas `groupnames` isn't.

But to conclude, it's indeed up to you. I don't want to bother you.

**Comment by lecorguille** [comment]
Do you think that your [.concatenate_OnDiskMSnExp](https://github.com/sneumann/xcms/blob/fd50b0cc4b3c2c68303779ecbfe2cdc463339b5b/R/functions-XCMSnExp.R#L1448) is compatible with the release I'm using?

If so, forget my previous message.
Waiting for the availability of the bioconducto-3.7 XCMS version, I just have to copy/paste your [.concatenate_OnDiskMSnExp](https://github.com/sneumann/xcms/blob/fd50b0cc4b3c2c68303779ecbfe2cdc463339b5b/R/functions-XCMSnExp.R#L1448) in my script in the meanwhile. And remove it afterward.

Correct?

**Comment by jotsetung** [comment]
Yes it is compatible - you could also do the same with the `groupnames,XCMSnExp`.

**Comment by lecorguille** [comment]
I did but in first place I didn't think about do the same with `c`
Thanks again 👍
