### ISSUE TITLE
Gaps in scan time: cut scantime-vector at NA seconds.

### ISSUE THREAD

**Issue by cdinter** [sneumann/xcms#248]
Hi,

I am processing untargeted metabolomics data, collected in a QTOF. I am trying to align retention times based on MS1. Workflow, at the moment, is conversion of wiff files to mzML using proteowizard and then processing in xcms (using pretty much the vignette).

```
library(xcms)

mzMLs <- dir("data/IDA_ConvertedRawData_32bit", full.names = TRUE, recursive = TRUE)

pd <- data.frame(sample_names = sub(basename(mzMLs), pattern = ".mzML", replacement ="",
fixed=TRUE), sample_group = c(rep("fKpA", 10), rep("WT", 10)), stringsAsFactors=FALSE)

#Only loading the first couple files for faster testing
raw_data_4 <- readMSData(files = mzMLs[1:4], pdata = new("NAnnotatedDataFrame",pd), 
msLevel = 1, mode ="onDisk")

cwp <- CentWaveParam(ppm = 30, peakwidth = c(10,60),snthresh = 6, mzdiff = 0.01, prefilter = c(3,500), integrate = 2)
xdata <- findChromPeaks(raw_data, param = cwp)

xdata <- adjustRtime(xdata, param = ObiwarpParam(binSize = 0.5))
```

This gives me the following output in R

> Sample number 2 used as center sample.
> Aligning Delta_fKpA_SK1_Ext1.mzML against Delta_fKpA_SK1_Ext2.mzML ... Found gaps in scan times of the center sample: cut scantime-vector at NA seconds.
> Found gaps in scan time of file Delta_fKpA_SK1_Ext1.mzML: cut scantime-vector at NA seconds.
> OK
> Aligning Delta_fKpA_SK1_Ext4.mzML against Delta_fKpA_SK1_Ext2.mzML ... Found gaps in scan times of the center sample: cut scantime-vector at NA seconds.
> Found gaps in scan time of file Delta_fKpA_SK1_Ext4.mzML: cut scantime-vector at NA seconds.
> OK
> Aligning Delta_fKpA_SK1_Ext3.mzML against Delta_fKpA_SK1_Ext2.mzML ... Found gaps in scan times of the center sample: cut scantime-vector at NA seconds.
> Found gaps in scan time of file Delta_fKpA_SK1_Ext3.mzML: cut scantime-vector at NA seconds.
> OK
> Applying retention time adjustment to the identified chromatographic peaks ... OK
> Warning message:
> In `adjustedRtime<-`(`*tmp*`, value = list(c(0.273999989032745,  :
>   Adjusted retention times for file(s) Delta_fKpA_SK1_Ext1.mzML not sorted increasingly.

Looking at the plotAdjustedRtime and the exported rtime compared to adjustedRtime shows that only the first 200 scans or so (there are around 8000 scans/sample), of each file are now aligned. Any idea on what could tricker this behaviour and on how to fix it?

XCMSonline yields, using the same parameters, a aproper alignment.

Thank you very much,
Carl

 sessionInfo()
> R version 3.4.3 (2017-11-30)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 16.04.3 LTS
> 
> Matrix products: default
> BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
> LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C
> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C
> 
> attached base packages:
> [1] parallel  stats     graphics  grDevices utils     datasets  methods
> [8] base
> 
> other attached packages:
> [1] xcms_3.0.0          MSnbase_2.4.2       ProtGenerics_1.10.0
> [4] mzR_2.12.0          Rcpp_0.12.15        BiocParallel_1.12.0
> [7] Biobase_2.38.0      BiocGenerics_0.24.0
> 
> loaded via a namespace (and not attached):
>  [1] pillar_1.1.0           compiler_3.4.3         BiocInstaller_1.28.0
>  [4] RColorBrewer_1.1-2     plyr_1.8.4             iterators_1.0.9
>  [7] zlibbioc_1.24.0        MALDIquant_1.17        digest_0.6.15
> [10] preprocessCore_1.40.0  tibble_1.4.2           gtable_0.2.0
> [13] lattice_0.20-35        rlang_0.1.6            Matrix_1.2-11
> [16] foreach_1.4.4          S4Vectors_0.16.0       IRanges_2.12.0
> [19] stats4_3.4.3           multtest_2.34.0        grid_3.4.3
> [22] impute_1.52.0          survival_2.41-3        XML_3.98-1.9
> [25] RANN_2.5.1             limma_3.34.6           ggplot2_2.2.1
> [28] MASS_7.3-48            splines_3.4.3          scales_0.5.0
> [31] pcaMethods_1.70.0      codetools_0.2-15       MassSpecWavelet_1.44.0
> [34] mzID_1.16.0            colorspace_1.3-2       affy_1.56.0
> [37] lazyeval_0.2.1         munsell_0.4.3          doParallel_1.0.11
> [40] vsn_3.46.0             affyio_1.48.0

**Comment by jotsetung** [comment]
Hi Carl,

this might have to do with the messages that you get (`Found gaps in scan time of file Delta_fKpA_SK1_Ext3.mzML: cut scantime-vector at NA seconds`. obiwarp breaks alignment if the difference in the retention times of one file is larger than a certain threshold which is calculated based on the median difference of the observed retention times (indicating that some scans might be missing?). 
The code for that in the function is (with `cntr` being the center file and `z` one of the other files).
```r
        ## 1)Check the scan times of both objects:
        scantime1 <- unname(rtime(cntr))
        scantime2 <- unname(rtime(z))
        ## median difference between spectras' scan time.
        mstdiff <- median(c(diff(scantime1), diff(scantime2)))

        mst1 <- which(diff(scantime1) > 5 * mstdiff)[1]
        if (!is.na(mst1)) {
            scantime1 <- scantime1[seq_len((mst1 - 1))]
            message("Found gaps in scan times of the center sample: cut ",
                    "scantime-vector at ", scantime1[mst1]," seconds.")
        }
        mst2 <- which(diff(scantime2) > 5 * mstdiff)[1]
        if(!is.na(mst2)) {
            scantime2 <- scantime2[seq_len((mst2 - 1))]
            message("Found gaps in scan time of file ", basename(fileNames(z)),
                    ": cut scantime-vector at ", scantime2[mst2]," seconds.")
        }
```
There's unfortunately not much you can do - eventually use an alternative retention time adjustment?

Why it is working in XCMSonline I don't know - it is not clear to me on which `xcms` version the web app is based.

**Comment by cdinter** [comment]
Thank you!

I guess this being an IDA-experiment is the problem then. Roughly half of the scans in my experiment are MS2 scans, which I exlude for the processing. This should lead to bigger differences in between my MS1 scans and therefore break the alignment? I guess I will try another retention time adjustment.

Any idea on why the messages I receive say "at NA seconds"? This seems weird to me.

**Comment by jotsetung** [comment]
> Any idea on why the messages I receive say "at NA seconds"? This seems weird to me.

yes :) that's a bug I'll fix: it's first subsetting the scan time vector
```r
scantime1 <- scantime1[seq_len((mst1 - 1))]
```
and afterwards accessing elements that have been removed
```r
message("Found gaps in scan times of the center sample: cut ",
                    "scantime-vector at ", scantime1[mst1]," seconds.")
```
