### ISSUE TITLE
xcms1 To xcms3 - groupnames

### ISSUE THREAD

**Issue by lecorguille** [sneumann/xcms#250]
Hi,
Still with my conversion from xcms 1.x to xcms 3.0.0.

We used to export peakTable (equivalent to `featureDefinitions ` and `featureDefinitions `) with as IDs something like that `M598T3835`, `M598T4228_1`
We used to use: https://github.com/sneumann/xcms/blob/d3f47ca69474af4913ad8d1cc0cfe9420011ddda/R/methods-xcmsSet.R#L327
```R
groupnames(xset)
```

Is there something like that for XCMSnExp object?

Many thanks

**Comment by jotsetung** [comment]
The `DataFrame` returned by `featureDefinitions` has rownames and also `featureValues` uses the same. They are now simply called `"FT001"` etc, no encoding of mass or time into the name (which is anyway present in the `featureDefinitions` table. So, essentially, within the same experiment these feature names are unique (but not across experiments!).

**Comment by dsaidem** [comment]
Hi, but is there any option of exporting mass or time into the name? That would be very important to compare results with other softwares like metaboanalyst.

Thanks,
Daniel

**Comment by lecorguille** [comment]
My workaround largely inspired by xcms 1.x

```R
groupnamesW4M <- function(xdata, mzdec = 0, rtdec = 0) {
    mzfmt <- paste("%.", mzdec, "f", sep = "")
    rtfmt <- paste("%.", rtdec, "f", sep = "")

    gnames <- paste("M", sprintf(mzfmt, featureDefinitions(xdata)[,"mzmed"]), "T",
                    sprintf(rtfmt, featureDefinitions(xdata)[,"rtmed"]), sep = "")

    if (any(dup <- duplicated(gnames)))
        for (dupname in unique(gnames[dup])) {
            dupidx <- which(gnames == dupname)
            gnames[dupidx] <- paste(gnames[dupidx], seq(along = dupidx), sep = "_")
        }

    return (gnames)
}
```

**Comment by jotsetung** [comment]
I'll implement the `groupnames,XCMSnExp` method, so you can use the same interface.

**Comment by jotsetung** [comment]
Now you can use `groupnames` on an `XCMSnExp`. Grap the latest `xcms` with `devtools::github("sneumann/xcms", "master")`.

**Comment by lecorguille** [comment]
Thanks!
