### ISSUE TITLE
fillpeaks without imputing

### ISSUE THREAD

**Issue by JosieLHayes** [sneumann/xcms#254]
I am processing some metabolomics data using xcms and I have a question.

So far I have performed the following:
peakmatrix<-xcmsSet(method="centWave",peakwidth=c(2,60),ppm=10,snthresh=10,nSlaves=6)
ret<-retcor(peakmatrix,method="obiwarp",plottype=c("deviation”))

I would like to next get peaks with the corrected retention times but not impute peaks (so I can impute them myself). Is there a way of doing this? Or filtering the peaks after fillPeaks() so I don't have the imputed ones?

Thank you.

**Comment by jotsetung** [comment]
You can extract the identified chromatographic peaks using `peaks(ret)`, the retention times of these are already adjusted. 
You can also proceed with a correspondence analysis (i.e. group chromatographic peaks across samples). The method to do this is `group`. If you don't call `fillPeaks` on the resulting object you can simply extract the intensities of the grouped peaks with the `groupval` method.

**Comment by JosieLHayes** [comment]
Perfect, thank you so much for your help.


Best wishes


Josie

________________________________

**Comment by jotsetung** [comment]
I'm closing this issue - feel free to open it again, or open a new issue if you run into other problems.
