### ISSUE TITLE
Specify source files which fail to load

### ISSUE THREAD

**Issue by jaketmp** [sneumann/xcms#261]
When initialising from a directory of mzML files, one of which is corrupt, xcmsSet does not give us a useful error message:

> stop worker failed:
 'clear_cluster' receive data failed:
 reached elapsed time limit

 Necessitating bisecting the directory contents until we find the offending file.

This is the import command we are running:

`ds <- xcmsSet(method="centWave",  noise=600, ppm=25, prefilter=c(8, 6000), snthresh = 10, peakwidth=c(3, 12), mzdiff=0.01, mzCenterFun="wMean", integrate=2, lock=F, fitgauss=F,
  BPPARAM=SnowParam (workers = workers) )`

Is there a way to have XMCS specify which file is causing it problems?

**Comment by sneumann** [comment]
Hi, you could do an `xrs <- sapply(files, function(f) {cat("Reading ", f, "\n"); xcmsRaw(f)})`
(untested!) to read all files. Yours, Steffen

**Comment by jaketmp** [comment]
Thanks - shall give it a go.

**Comment by jotsetung** [comment]
Alternatively, the *new* xcms workflow might also help here. You'll have to first read in the files with `readMSData`, which *should* give you an error message if one of your files is corrupt:

```r
fls <- dir(".", pattern = "mzML", full.names = TRUE)
raw_data <- readMSData(fls, mode = "onDisk")
```

**Comment by jaketmp** [comment]
@jotsetung Unfortunately the error from your case is still non-specific:

```
Error in pwizModule$open(filename) : 
  [SpectrumList_mzML::create()] Bad istream.
```

@sneumann  This approach works for my test case.

it would be very good and save a lot of time to have this level of diagnostic reporting in the standard workflow though.

Thanks

**Comment by jotsetung** [comment]
IMHO this should be handled in the lower level packages. Since it's data I/O it should go to `mzR` and we should ensure that `mzR` throws a human understandable error. The `Error in pwizModule$open` comes actually from `mzR`, but we should ensure that the corresponding file name is shown.
