### ISSUE TITLE
New user interface and IPO

### ISSUE THREAD

**Issue by cdinter** [sneumann/xcms#269]
Hello,

I thought about using IPO and played around with it. Form what I can tell it still uses the old xcms interface, but I'm using the new one. 

My question now is; how much have centWave, Obiwarp and density-based grouping changed form the old to the new userinterface? Are they similar enough to justify using the same parameters?

kind regards
Carl

**Comment by sneumann** [comment]
Quick answer, parameters still have the same semantics and can be used. Yours Steffen

---
I blame Android for the brevity and typos
