### ISSUE TITLE
Error in R Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.

### ISSUE THREAD

**Issue by AndreaHobby** [sneumann/xcms#270]
raw_data <- readMSData(files = cdfs, pdata = new("NAnnotatedDataFrame", pd),
                mode = "onDisk")
Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.

What does this error mean?

**Comment by jotsetung** [comment]
This is not really an error, it's more a notification that polarity information can not be extracted from CDF files. AFAIK polarity information is only recorded in mzML and mzXML files. You can ignore that message.
