### ISSUE TITLE
msLevel with findChromPeaks-CentWaveParam

### ISSUE THREAD

**Issue by jsaintvanne** [sneumann/xcms#274]
Hi,

I try to obtain a xdata with a msLevel = 1. To do that I'm using "readMSData" from MSnBase and then "findChromPeaks" from xcms with CentWaveParam. 
My object after the first step have my two levels of MS (1 and 2) because I voluntary select no msLevel. The problem is when I make findChromPeaks on this object. I can read in the manual that msLevel for this function is 1 by default ("integer(1) defining the MS level on which the peak detection should be per-formed. Defaults to msLevel = 1").
But my output object has always the msLevel 1 and 2... When I perform the function findChromPeaks with a msLevel=1, I obtain the same result...

So can you help me with this please? 

This is my output : 
> xdata<-**readMSData**("myFile.mzML", mode="onDisk")
> xdata2<-**findChromPeaks**(xdata, param=cwp,**msLevel=1**)
Detecting mass traces at 25 ppm ... OK
Detecting chromatographic peaks in 2201 regions of interest ... OK: 77 found.
> xdata2
MSn experiment data ("XCMSnExp")
Object size in memory: 1.83 Mb
<- - - Spectra data - - -
 **MS level(s): 1 2** 
 Number of spectra: 6017 
 MSn retention times: 0:0 - 24:1 minutes
<- - - Processing information - - -
Data loaded [Thu Apr  5 13:34:54 2018] 
 MSnbase version: 2.4.2 
<- - - Meta data  - - -
phenoData
  rowNames: STD_MIX1_60stepped_1E5_Top5_msLevel1-2.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  STD_MIX1_60stepped_1E5_Top5_msLevel1-2.mzML 
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S6017 (6017 total)
  fvarLabels: fileIdx spIdx ... spectrum (28 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
<- - - xcms preprocessing - - -
Chromatographic peak detection:
 method: centWave 
 77 peaks identified in 1 samples.
 On average 77 chromatographic peaks per sample.

Sorry if I'm not clear enough !
Ask me if you don't understand please and thanks for the helpers!

Julien

**Comment by jotsetung** [comment]
Hi Julien,

so, you want an object with only MS1, right? There are several ways to do that:
```r
xdata <- readMSData("myFile.mzML", mode="onDisk", msLevel = 1)
```
This reads only MS level1 data and discards all MS2.

Alternatively, you could filter by MS level after you read the data:
```r
xdata <- filterMsLevel(xdata, msLevel = 1)
```
after that your `xdata` will contain only MS1 data (this will also work after `findChromPeaks`).

`findChromPeaks` will not remove MS2 spectra, with the `msLevel` parameter you can just specify whether you want to perform the peak detection on the MS1 or other level. By default, peaks are detected in MS1.

**Comment by jsaintvanne** [comment]
Hi jotsetung,

Thanks for this so quick answer !

Effectively, I obtained an object with specify the msLevel when I make readMSData, thanks !

And you have cleared this findChromPeaks function for me. I thought that it remove MS2 spectra when I precise the msLevel. 

So thanks a lot for this, I can now have my object correctly with 
```R
xdata <- readMSData(myFile.mzML, mode="onDisk")
xdata <- findChromPeaks(xdata, param=cwp)
xdata <- filterMsLevel(xdata, msLevel=1)
```
