### ISSUE TITLE
msdata needs updating

### ISSUE THREAD

**Issue by kasperdanielhansen** [sneumann/xcms#28]
The objects are too old:

```{r}
library(msdata)
data(xs)
validObject(xs) # Fails
updateObject(xs) # Fails
```

**Comment by sneumann** [comment]
Quick Q: what is the "proper" way to fix this ? Add to xcms a corresponding 
````
setMethod("updateObject", "xcmsSet",
         function(object, ..., verbose=FALSE)
         {whatever needed to update}
```` 
and save/commit the updated xs back to `msdata` ? 
Yours, Steffen

**Comment by jotsetung** [comment]
That would make sense. I could jump in here and implement the `updateObject` method since presently I do have some spare time.

**Comment by kasperdanielhansen** [comment]
Yes, this is what I would do
  - extend updateObject() to deal with this change in class structure
  - update the saved object in msdata.

I have often found it useful to the the raw data files included in data
packages so I can regenerate them with parsing, and so that users have some
examples of raw data.  But not sure about size etc. (the converse argument
also has value: including raw data tends to make package bigger).

Kasper

**Comment by jotsetung** [comment]
I've added the `updateObject` methods for `xcmsSet` in commit https://github.com/sneumann/xcms/commit/a4d09a15aab9fc0e1d9d957ed5709d263d927c93 in the *xcms3* branch.
Did also some other internal refactoring in that commit (roxygen2, put class definitions in a *DataClasses.R* file etc).

@sneumann are you going to merge the changes to the *devel* branch and bumping the package version (and submitting the changes to the Bioc svn)?

**Comment by jotsetung** [comment]
All merged (commit https://github.com/sneumann/xcms/commit/8e6439e1a6b88df86c6c99c10ed309ab83f99ffb) and pushed to Bioconductor; version 1.49.3 has an `updateObject` method for `xcmsSet` objects.

**Comment by sneumann** [comment]
msdata package is not yet updated. But with Jo's work easy to do by me.

**Comment by sneumann** [comment]
Updated xs.Rda in 
https://hedgehog.fhcrc.org/bioc-data/trunk/experiment/data_store/msdata/data/xs.rda
and bumped msdata to 0.12.1 in BioC SVN. Thanks for reporting, yours, Steffen
