### ISSUE TITLE
New result object extending Chromatograms

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#281]
Similar to the `XCMSnExp` object that extends `MSnbase`s `OnDiskMSnExp` and contains the peak detection results, we need a new object for purely chromatographic data (from MRM/SRM experiments).

This could extend the `Chromatograms` object and should contain:
- peak detection results. Most likely a single `matrix` with the peaks for all `Chromatogram` objects.
- correspondence results - something similar to the `featureDefinitions` of the `XCMSnExp` object.

**Comment by stanstrup** [comment]
The idea is that you can use this with downstream functions such as grouping?

**Comment by jotsetung** [comment]
In principle yes, should enable (or we could add) alignment and grouping.

**Comment by jotsetung** [comment]
Development is going on (sporadically I have to say) in branch *XChromatograms*.

**Comment by jotsetung** [comment]
`chromatogram,XCMSnExp` should then return a `XChromatograms` object. `plot,XChromatograms` should then implement a similar functionality than `highlightChromPeaks`, i.e. highlight/show peaks in the chromatogram. That would simplify plotting of EIC and peak detection results considerably.

**Comment by jotsetung** [comment]
Closing issue. The remaining functionality is discussed in issues #330, #331 and #332.

**Comment by stanstrup** [comment]
Any way to do grouping/alignment?

**Comment by jotsetung** [comment]
you're getting greedy :)
not yet. But feel free to open an issue and I will work on it when time permits.
