### ISSUE TITLE
Issue with boost or c++ or xcms

### ISSUE THREAD

**Issue by mayankmtg** [sneumann/xcms#285]
I am facing some issues installing the bioconductor R package for xcms. Is this an issue with my version of c++ or an xcms problem. 

1: In install.packages(pkgs = doing, lib = lib, ...) :
    installation of package ‘XML’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
    installation of package ‘mzID’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, ...) :
    installation of package ‘MSnbase’ had non-zero exit status
4: In install.packages(pkgs = doing, lib = lib, ...) :
    installation of package ‘xcms’ had non-zero exit status

```
In file included from ./boost/boost/bind/mem_fn.hpp:25:0,
                 from ./boost/boost/mem_fn.hpp:22,
                 from ./boost/boost/bind/bind.hpp:26,
                 from ./boost/boost/bind.hpp:22,
                 from ./boost/boost/thread/detail/thread.hpp:30,
                 from ./boost/boost/thread/thread_only.hpp:22,
                 from boost/libs/thread/src/pthread/thread.cpp:11:
./boost/boost/get_pointer.hpp: At global scope:
./boost/boost/get_pointer.hpp:27:40: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
 template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                        ^
In file included from /usr/include/c++/5/memory:81:0,
                 from ./boost/boost/config/no_tr1/memory.hpp:21,
                 from ./boost/boost/smart_ptr/shared_ptr.hpp:23,
                 from ./boost/boost/shared_ptr.hpp:17,
                 from ./boost/boost/date_time/time_clock.hpp:17,
                 from ./boost/boost/thread/thread_time.hpp:9,
                 from ./boost/boost/thread/lock_types.hpp:18,
                 from ./boost/boost/thread/pthread/thread_data.hpp:12,
                 from ./boost/boost/thread/thread_only.hpp:17,
                 from boost/libs/thread/src/pthread/thread.cpp:11:
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;

```

**Comment by sneumann** [comment]
Hi, which operating system and compiler is that?

---
I blame Android for the brevity and typos

**Comment by mayankmtg** [comment]
Linux Operating System Ubuntu 16.04.4
gcc g++ 5.4.0 -std=gnu++11

**Comment by mayankmtg** [comment]
@sneumann I could figure out the issue. I tried installing my first dependency with xml explicitly:

`sudo apt-get install libxml2-dev`

It worked

**Comment by sneumann** [comment]
Great, feel free to close the issue then. Yours Steffen

---
I blame Android for the brevity and typos
