### ISSUE TITLE
highlightChromPeaks boxes are not around the peaks

### ISSUE THREAD

**Issue by etrh** [sneumann/xcms#289]
From time to time, I encounter plots generated by `plot` and then `highlightChromPeaks` that look like this.

Does this mean my peak picking approach was flawed or is this a bug in `highlightChromPeaks`?

![plot](https://user-images.githubusercontent.com/29725715/41226729-ad440e4a-6d72-11e8-8a74-c057f7dac2ae.png)

**Comment by jotsetung** [comment]
This is indeed strange. Your m/z range for the chromatogram is however quite large (180.00 - 191.99). I assume that you have multiple peaks per sample in this window.

Now, the default of `chromatogram` is to create a total ion chromatogram (with `aggregationFun = "max"`, i.e. summing all the intensities per spectra within a given m/z range). That could be the reason why your peaks are higher than the rectangles (detected chromatographic peaks).

You could also use the code below to evaluate whether you have multiple signals/peaks in that m/z - rt area (assuming `data` is your result object and `mzr` and `rtr` your m/z and rt ranges:
```r
plot(filterMz(filterRt(data, rt = rtr), mz = mzr), type = "XIC")
```

Could you please try the following on this particular peak:
```r
chr <- chromatogram(data, mz = mzr, rt = rtr, aggregationFun = "max")
highlightChromPeaks(data, mz = mzr, rt = rtr, whichPeaks = "apex_within")
```

Also, what is the output of
```r
chromPeaks(data, mz = mzr, rt = rtr, type = "apex_within")
```

**Comment by etrh** [comment]
Thanks a lot for looking into this and devoting your time to it.

When I take a much smaller m/z interval, I indeed see the boxes placed correctly around the peaks. Here is an example:

![09 - identified_peaks_in_mz_291 1434-291 1444_rt_646-671](https://user-images.githubusercontent.com/29725715/41537586-3bfb8b22-7309-11e8-9348-72a965867833.png)

But getting back to plots with large m/z intervals, here's another one I came across today:

![09 - identified_peaks_in_mz_189-192_rt_600-700](https://user-images.githubusercontent.com/29725715/41537622-59521ec0-7309-11e8-9cb7-6d2f3304fddc.png)

So I followed your comments and did this:

```
mzr_new <- c(189,192)
rtr_new <- c(670,700)
table(chromPeaks(xdata, mz = mzr_new, rt = rtr_new)[,"sample"])
```

> 14 15 16 17 18 19 20 21 22 23 24 25 26 
>  2  2  2  2  2  2  2  2  2  2  2  2  2

`plot(filterMz(filterRt(xdata, rt = rtr_new), mz = mzr_new), type = "XIC")
`
> Warning message:
> In .local(object, ...) : Identified chromatographic peaks removed

I see this pattern for all of the samples in one of my groups:

![plot_zoom_png 2](https://user-images.githubusercontent.com/29725715/41538091-a5612832-730a-11e8-9548-a645f83c99f7.png)

And this for the other sample group:

![plot_zoom_png](https://user-images.githubusercontent.com/29725715/41538124-b9ba05b0-730a-11e8-82f5-bc873da3b309.png)

Then I ran this per your suggestion:

```
chr <- chromatogram(xdata, mz = mzr_new, rt = rtr_new, aggregationFun = "max")
plot(chr, col = group_colors[chr_raw$sample_group], lwd = 2)
highlightChromPeaks(xdata, mz = mzr_new, rt = rtr_new, whichPeaks = "apex_within")
```

![f](https://user-images.githubusercontent.com/29725715/41538218-0f0ea91c-730b-11e8-949c-9f7a69fdb974.png)

Finally, `chromPeaks(xdata, mz = mzr_new, rt = rtr_new, type = "within")` gives me 26 peaks; two peaks for samples 14-26:

`table(chromPeaks(xdata, mz = mzr_new, rt = rtr_new, type = "within")[,"sample"])`

> 14 15 16 17 18 19 20 21 22 23 24 25 26 
>  2  2  2  2  2  2  2  2  2  2  2  2  2

**Comment by jotsetung** [comment]
Thanks for updating! And sorry, but I don't understand if this solves now your problem or if you still have issues with it? 

Also, I'm no MS expert, but to me the data you see in the `type = XIC` plot suggests that you indeed have a peak from an ion with m/z ~ 190 in one sample group (the blue samples). The data in the red samples looks more like the signal from a background ion or salt or whatever to me; there is no clear peak signal and also the m/z is quite off from the peak in the blue samples. I would not group these signals together (e.g. into one feature). 

Another question: is this data centroided? There seem to be quite a lot of data points in your XIC plots that I would almost assume its profile-mode data. *centWave* should be applied to centroided, not profile mode data.

**Comment by etrh** [comment]
@jotsetung Yes, for the time being I can see that taking a small m/z range solves the problem and most probably that was also the problem with my first example.

You mentioned that you would not group those blue and red signals together into one feature. I am not sure I understand what you exactly mean. Which part of the process in xcms are you referring to by grouping? Are you in fact referring to `groupChromPeaks`?

Yes the data is centroided. I have on average 10-15 scans per peak.

**Comment by jotsetung** [comment]
> Which part of the process in xcms are you referring to by grouping? Are you in fact referring to `groupChromPeaks`?

Yes, I meant that. I know the nomenclature is a little confusing.
