### ISSUE TITLE
Using xcmsRaw and getEIC/plotEIC at MS1 and MS2 levels

### ISSUE THREAD

**Issue by manohar8** [sneumann/xcms#290]
Hello,
We wish to use xcmsRaw to get maximum information from a specific precursor-product pair. Basically we are looking for possibility of extraction and integration of MS1 and MS2 level peaks from raw data. getEIC and plotEIC have been very useful in this regard however the pattern of MS1 and MS2 peaks are quite different. Please see the image below, for MS1 we get a continuous Gaussian peak while MS2 peak (for the same precursor) is discontinuous. Is there any way to get a smooth EIC for MS2 fragments? Also we would like to know if peak areas can be integrated using xcms. 

Please give us your suggestions.

Thank you,
Manohar

![atp_ms1_ms2](https://user-images.githubusercontent.com/31764620/41410809-42b491e8-6ff8-11e8-881d-e9b7b39ba3cb.jpg)

[ATP_MS1_MS2.txt](https://github.com/sneumann/xcms/files/2102235/ATP_MS1_MS2.txt)

**Comment by jotsetung** [comment]
Dear Manohar,

sorry for the late reply. I never worked with MS1 and MS2 data in LCMS, but I still try to answer your questions. Now, for the first, I suggest that you use the *new* functionality in `xcms` that should simplify MS data handling (and extraction of EICs): in your case you would have to read the data with (note: this requires R version 3.5.0 and the recent xcms version 3.2.0):

```r
library(xcms)
## Reading the data like this you'll have MS1 and MS2 spectra
data <- readMSData("C:/Users/FARHAN AHMAD/Desktop/7002 flask_from lcms pc/ms level 1- wopeakpicking  040618/mzML", mode = "onDisk")

## Extract the MS1 EIC
atp_ms1 <- chromatogram(filterMsLevel(data, 1), mz = c(505.94, 506.04), rt = c(890, 950))
plot(atp_ms1)

## Extract the MS2 EICs
atp_ms2_1 <- chromatogram(filterMsLevel(data, 2), mz = c(407.95, 408.05), rt = c(890, 950))
plot(atp_ms2_1)

atp_ms2_2 <- chromatogram(filterMsLevel(data, 2), mz = c(158.87, 158.97), rt = c(890, 950))
plot(atp_ms2_2)
```

Would be nice if you could try the code above and provide feedback whether it worked (eventually including the plots generated).

With the new functions it is even possible to perform peak detection just on the extracted ion chromatograms, so yes, with that you have the possibility to calculated the peak area.

**Comment by manohar8** [comment]
Hi Johannes ,
Thanks for the suggestions. We tried new functionalities with suggested xcms and R versions.

`library(xcms)`

`setwd("C:/Users/FARHAN AHMAD/Desktop/new code for eic/ida mzml/mzml")`
`files <- list.files("C:/Users/FARHAN AHMAD/Desktop/new code for eic/ida mzml/mzml",recursive=FALSE, full.names=TRUE)`
```
## Reading the data like this you'll have MS1 and MS2 spectra
data <- readMSData(files, mode = "onDisk")
```
## data output
`data`
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 2.35 Mb
- - - Spectra data - - -
 **MS level(s): 1 2** 
 Number of spectra: 7240 
 MSn retention times: 0:0 - 24:59 minutes
- - - Processing information - - -
Data loaded [Fri Jun 22 16:10:06 2018] 
 MSnbase version: 2.6.1 
- - - Meta data  - - -
phenoData
  rowNames: 7002 WT 0 HR IDA1.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  7002 WT 0 HR IDA1.mzML 
protocolData: none
featureData
  featureNames: F1.S0001 F1.S0002 ... F1.S7240 (7240 total)
  fvarLabels: fileIdx spIdx ... spectrum (29 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'

## Extract the MS1 EIC
```
atp_ms1 <- chromatogram(filterMsLevel(data, 1), mz = c(505.94, 506.04), rt = c(890, 950))
plot(atp_ms1)
```
![atp_ms1](https://user-images.githubusercontent.com/31764620/41775683-96a6a994-7642-11e8-8ab4-8b29be6aeea2.png)

```
## Extract the MS2 EICs

atp_ms2_1 <- chromatogram(filterMsLevel(data, 2), mz = c(407.85, 408.15), rt = c(890, 950))
```

> Warning message:
> In .extractMultipleChromatograms(object, rt = rt, mz = mz, aggregationFun = aggregationFun,  :
>   No MS 1 data present.

Although “data” has both MS1 and MS2 peaks we get the above error.  Finally, with plot function we get an empty chromatogram.

Please comment.

Thank you,
Manohar

**Comment by manohar8** [comment]
Hello developers,
Any suggestions on .extractMultipleChromatograms in above issue. 
Waiting for your comments.

Thanks,
Manohar

**Comment by jotsetung** [comment]
Please try to use
```r
atp_ms2_1 <- chromatogram(filterMsLevel(data, 2), mz = c(407.85, 408.15), rt = c(890, 950), msLevel = 2)
```

i.e. the same call but with additionally specifying `msLevel = 2`. That should work, let me know if not.

**Comment by manohar8** [comment]
Thanks Johannes,
I tried this one. It worked fine. However, it still shows MS2 peak in discontinuous manner (somewhat similar to the first post in this thread).
We also tried this with other peaks and files to see if it is the data in this file a problem (even SWATH mode data was tried). There also the EIC for MS2 peaks looked same.  Is there a way to get a EIC at MS2 level like we see at MS1 level (clean and continuous)?


Manohar


![atp_ms2 2](https://user-images.githubusercontent.com/31764620/42154579-c85c88aa-7e03-11e8-8ee4-4e4c29f9a831.png)
![atp_ms2 1](https://user-images.githubusercontent.com/31764620/42154580-c89c028c-7e03-11e8-9c33-05c6c3cb8e8f.png)

**Comment by jotsetung** [comment]
Do you have many `NA` intensities? (i.e. what is `intensity(atp_ms2_1)`?).

Alternatively you could plot the data simply with the base `plot` function:
```r
plot(rtime(atp_ms2_1), intensity(atp_ms2_1), type = "l")
```

**Comment by manohar8** [comment]
From screenshots below you can see that it does show NA for MS2 peak intensities (at most places/picture 2) while MS1 had continuous values (picture 1). That is possibly the reason for sharp discontinuous signals in MS2. Can we bypass/filter NA values and use only positive values for forming a peak because at certain places it is in good intensity (picture 3). 

Thanks,
Manohar


![atp_ms_1 intensity1](https://user-images.githubusercontent.com/31764620/42163683-227ba48e-7e21-11e8-87b6-c837914a5314.JPG)
![atp_ms2_2 intensity2](https://user-images.githubusercontent.com/31764620/42163707-2e9c01d2-7e21-11e8-960b-744673b40f6b.JPG)
![atp_ms2_1 intensity2](https://user-images.githubusercontent.com/31764620/42163741-47288f2c-7e21-11e8-9c43-e49225285687.JPG)

Thanks,
Manohar
Finally this one showed error

Checked this one, 
``intensity(atp_ms_1)"

> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘intensity’ for signature ‘"Chromatograms"’

**Comment by jotsetung** [comment]
I see. Yes, the `NA` are the reason for the non-continuous line. You can call `clean` on a `Chromatogram` prior plotting. In your case you could do something like:

```r
plot(clean(atp_ms2_1[1, 1], na.rm = TRUE))
```

The `[1, 1]` is required to access the chromatogram in the first file. With `clean` and `na.rm = TRUE` you tell the function to remove all elements with an `NA` intensity.

Regarding your error: `at_ms2_1` is a `Chromatograms` object which is simply put a `matrix` with `Chromatogram` objects (one column per sample). There is no `intensity` function on this type of object available yet. `intensity` and `rtime` will only work on `Chromatogram` objects (without the `s`). Similarly to the `clean` call above you would have to use `intensity(atp_ms2_1[1, 1])` to get the intensities from the chromatogram of the first sample - I forgot to mention that before, sorry.

**Comment by manohar8** [comment]
Yes, the plots are now better than earlier, more clustered and continuous now, thanks. Now to integrate area for this ms2 peak can we join the top values in rt window to form a peak (excluding NA and reducing values in between). Is it possible to integrate this way to calculate peak areas so that we can relate this peak to its precursor (plots can overlap with precursor).

Thanks,
Manohar

![rplot01](https://user-images.githubusercontent.com/31764620/42204808-5baa1a7a-7ec0-11e8-88c1-ab8d18c12d7f.jpeg)
![rplot](https://user-images.githubusercontent.com/31764620/42204810-5bda5244-7ec0-11e8-9f39-eee20f62e95d.jpeg)

**Comment by jotsetung** [comment]
You could run a peak detection on these `Chromatogram` objects with `findChromPeaks` (passing e.g. a `CentWaveParam` along) similar how you would do that on the full data set. This will return you the identified chromatographic peak with the integrated peak area.

**Comment by manohar8** [comment]
Thanks Johannes, 
I tried this way

`ms1cwp <- CentWaveParam(snthresh = 5, noise = 100, ppm = 10, peakwidth = c(10,60), integrate = 1)`
`atp_ms1peak <- findChromPeaks(atp_ms1, param = ms1cwp)`

> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘findChromPeaks’ for signature ‘"Chromatograms", "CentWaveParam"’

and I hope integrate = 1 will work here. 

I also tried this with full msdata where it worked. So by itself findchrompeaks seems very informative at both ms1 and ms2 level. Separately it is possible to get list of precursors and products. With new functionalities is it possible to create a list of products associated with precursors?

Thanks,
Manohar

**Comment by jotsetung** [comment]
Sorry, forgot to mention that you need the most recent developmental version for this as I have implemented this only very recently:
```r
devtools::install_github("sneumann/xcms")
```

Regarding relating products to precursors: for spectrum data yes, for chromatographic peaks not yet. We are working on that.

**Comment by zizekw** [comment]
> You could run a peak detection on these `Chromatogram` objects with `findChromPeaks` (passing e.g. a `CentWaveParam` along) similar how you would do that on the full data set. This will return you the identified chromatographic peak with the integrated peak area.

@jotsetung, thanks for the insight within this thread, I've been able to learn a lot about some issues I was observing in my own work. 

Building off of what you described, I had performed `CentWave` peak detection and upon batch visualizing dozens of runs, I noticed I had some discontinuous lines on my chromatograms as was shown exactly as in above examples. However, going a little deeper, this discontinuity in my data is actually impacting my peak detection. Calling `clean` on my individual `Chromatogram` objects with `na.rm = TRUE` and then re-calling `findChromPeaks` solves my issue, but **are you aware of any way to remove these NA values (or 0s, I'm not sure which is causing my issues) _prior_ to an initial call of `findChromPeaks`?** I would ideally like to minimize the amount of calls to `findChromPeaks` and just detect these peaks outright since I am dealing with large amounts of data.

My `CentWaveParam` settings work for ~95% of my peaks (hundreds of runs), but upon visualization with the aid of `highlightChromPeaks`, the discontinuous peaks can not be detected no matter how much fiddling I did with the parameters. Calling `clean` and saving as a new `Chromatogram` object and then re-calling `findChromPeaks` which does indeed detect the peaks this second time around. However I am returned a `matrix` object and can not now utilize my existing batch plotting functions (including the use of `highlightChromPeaks`) as before.  Further, because I have to call it per file, I would have to add extra annotation steps to reincorporate these separately detected peaks with the rest of the experimental data. Let me know if I can provide any further information for context or clarify my comments.

**Comment by jotsetung** [comment]
@zizekw , I'll move this to a new issue.
@manohar8 , can we close this issue?

**Comment by lgatto** [comment]
@jotsetung - feel free to tag me if relevant.

**Comment by manohar8** [comment]
I am pleased to know that this issue is helping someone with their data. Please go ahead and use this issue as a base for further development. @zizekw and @ jotsetung - feel free to close or modify this issue, if possible then just keep me in the loop, that would be useful for me.
I will try suggestions from @zizekw, thanks for this.
