### ISSUE TITLE
Custom mgf export for GNPS

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#297]
Addition of linking between MS1 chromatographic peaks / features with MS2 spectra to use them with GNPS (MS2 spectra consolidation)

**Comment by michaelwitting** [comment]
Here is an example file.
[Bacillus_3_2-2_MSMS_manualy_checked_gap_filled_GNPS.zip](https://github.com/sneumann/xcms/files/2138894/Bacillus_3_2-2_MSMS_manualy_checked_gap_filled_GNPS.zip)

**Comment by jotsetung** [comment]
So, this means we need an explicit mgf export function in `xcms`, for `XCMSnExp` objects, eventually overwriting the one from `MSnbase` - or from `RMassBank`?

**Comment by michaelwitting** [comment]
We need the link between the MS1 and MS2 somehow... This means first we need a function to establish this link and then the export. So ideally, the function would take the <code>XCMSnExp</code> object together with some optional RT and m/z tolerance values for filtering.
I have some idea how such a function could look like... Let me see if I can hack some prototype down

**Comment by michaelwitting** [comment]
Just an idea for the filtering part:

```
exportPrototype <- function(XCMSnExp) {
  
  # get chromPeaks
  chromPeaks <- chromPeaks(XCMSnExp)
  
  for(i in 1:nrow(chromPeaks)) {
    
    # get current peak
    chromPeak <- chromPeaks[i,]
    
    # get sample
    sample <- chromPeak[11]
    
    # get all MS2 spectra from DDA experiment
    ms2spectra <- xrms %>%
      filterFile(sample) %>%
      filterRt(rt = chromPeak[5:6]) %>%
      filterMsLevel(msLevel = 2) %>%
      spectra
    
    # filter out only MS2 spectra
    filteredMs2spectra <- list()
    for(spectrum in ms2spectra) {
      if(spectrum@precursorMz > chromPeak[2] & spectrum@precursorMz < chromPeak[3]) {
        filteredMs2spectra <- c(filteredMs2spectra, spectrum)
      }
    }
    
    # add here lines of code for export
    # TODO
    
  }
}
```

**Comment by jotsetung** [comment]
OK, if I get it correctly one mgf file will contain all MS2 spectra associated with identified chromatographic peaks in one sample.

The trick will then be to select one MS2 spectrum from all those that are associated with the chromatographic peak. Here we could use the `combineSpectra` function from `MSnbase` that would also allow to generate an average spectrum from a list of input spectra.

**Comment by jotsetung** [comment]
Should be implemented by now, here and in `MSnbase`.
