### ISSUE TITLE
Extract MS2 information of a feature

### ISSUE THREAD

**Issue by Muiiki** [sneumann/xcms#302]
Hi,

The featureDefinitions function returns the data matrix of a detailed information of detected feature. It seems the feature index in featureDefinitions are different from returned ID of"featureNames", and there is no direct link between this feature index with associated MS2 spectra? 

Is there any method returns the MS2 spectra information of a specific feature rather than checking the rt and mz?

Thanks,

**Comment by jotsetung** [comment]
The `featureNames` function returns the names of the `Spectrum` objects, while the `featureDefinitions` defines the chromatographic peaks grouped across samples. This is indeed confusing; `featureNames` should be ideally called `spectrumNames`.

The spectra are also not directly linked to the chromatographic peaks and the related *features*. The only way (at present) to get e.g. MS2 spectra for a feature is to use the the retention time and mz of the feature and use the `filterRt` (and eventually `filterMz`) function.

**Comment by Muiiki** [comment]
Hi Johannes,

I've checked the returned the information of featureDefinitions, every feature is consisted of several peakidx. Is the peakidx equal to spectrumNames? If so, can we return the MS2 information of features by checking the peakidx? Coz when we process large number of features, checking the RT and m/z is quite time-consuming. 

By the way, can way extract EICs through the feature IDs rather than filtering to RT and m/z?

Thank you.

**Comment by Muiiki** [comment]
Got the idea from@michaelwitting
https://github.com/michaelwitting/metabolomics2018/blob/master/XCMS_Witting.pdf

We can get the MS2 scan of a specified feature by defining a function as following:

ms2spectra <- spectra(filterMsLevel(xdata, msLevel = 2))

getfeatureMS2 <- function(xdata, featureID, ms2spectra) {
  
  filteredms2spec <- list() #create an empty list for ms2 spectra
  mzmin <- xdata@msFeatureData[["featureDefinitions"]]@listData[["mzmin"]][featureID]
  mzmax <- xdata@msFeatureData[["featureDefinitions"]]@listData[["mzmax"]][featureID]
  
  rtmin <- xdata@msFeatureData[["featureDefinitions"]]@listData[["rtmin"]][featureID]
  rtmax <- xdata@msFeatureData[["featureDefinitions"]]@listData[["rtmax"]][featureID]
  
  for(i in 1:length(ms2spectra)){
    ms2spectrum <- ms2spectra[[i]]
    
    if(ms2spectrum@rt <= rtmax & ms2spectrum@rt >= rtmin & ms2spectrum@precursorMz <= mzmax & ms2spectrum@precursorMz >= mzmin) {
      filteredms2spec <- c(filteredms2spec, ms2spectrum)            
    }
  }
  
  return(filteredms2spec)
}

But after obtaining MS2 spectra, many of returned MS/MS showed a 0 precursor charge? I tried to find a way to visualize the mass spectrum and isotope of their corresponding precursor, but failed.

**Comment by fxd1106** [comment]
Dear Muiiki, 
    Thank you for sharing the code.

    For DDA data, I have another solution:

`raw_data_mem <- readMSData(files,pdata= new("NAnnotatedDataFrame")) #readMSData from packagee MSnbase, read the files using in memory mode
results_dt <- ldply (raw_data_mem@assayData, data.frame)
results_dt=data.table(results_dt)#Transfer results from list to data.table

add.mz.rt<-function(x){
  id=as.character(x[1])
  rt=raw_data_mem@assayData[[id]]@rt
  precursorMz=raw_data_mem@assayData[[id]]@precursorMz
  x["rt"]=rt
  x["precursorMz"]=precursorMz
  return(x)
}
MS2=apply(results_dt, 1, add.mz.rt)# for each line get the mz and rt according to .id, and add as a new column
MS2=data.table(t(MS2))
MS2[,precursorMz:=(as.numeric(precursorMz))]
MS2[,rt:=(as.numeric(rt))]
MS2[,mz :=(as.numeric(mz))]
MS2[,i:=(as.numeric(i))] #intensity
MS2_u=MS2[i>5,] #to make MS2 smaller 
MS2_u=unique(MS2_u,by=c("mz","rt","precursorMz"))`

For DIA data, your code will be a better solution, as the PrecursorMZ doesn't exist in DIA data.

**Comment by jotsetung** [comment]
@Muiiki the filtering you're performing shouldn't remove precursor charges - are you sure that these spectra do have precursor charges in the original files?

Generally, I think it would be better to get `MS2` spectra for each peak in each sample (rather then for a feature). The reason is that `rtmin` and `rtmax` in the `featureDefinitions` is the minimum and maximum rt of the apexes of all chromatographic peaks in all samples. I think it would be better to collect all MS2 spectra measured within the retention time span of each chromatographic peak (which is provided in the `chromPeaks` matrix). Please correct me if I'm wrong.

Eventually you find more helpful code in @michaelwitting's repo (that you did already find), specifically in the https://github.com/michaelwitting/metabolomics2018/blob/master/ms2dda.Rmd and https://github.com/michaelwitting/metabolomics2018/blob/master/ms2ida.Rmd files.

In any rate, the DIA/DDA MS2 support in `xcms` will be implemented - it's just a question when I find the time for that. Would be happy if you could then also test the new functions.

**Comment by jotsetung** [comment]
I haven't had the chance yet to put hands on DDA/DIA data so I can not say which way is better.

Regarding selection of a single representative MS2: it would also be possible to *combine* spectra with the `combinSpectra` method.

**Comment by jotsetung** [comment]
Development is now going on - see issue #321

**Comment by jotsetung** [comment]
@Muiiki , I've implemented the `featureSpectra` and `chromPeakSpectra` functions to extract MS2 spectra for features/peaks.

**Comment by jotsetung** [comment]
Closing this issue because it is discussed in issue #321.
