### ISSUE TITLE
Performance difference between NetCDF and mzML

### ISSUE THREAD

**Issue by Gronnesby** [sneumann/xcms#304]
I've been running and profiling the `xcmsSet` function to see how long it takes to do peak detection with xcms. However, the results vary greatly dependent on which format is used. 

For NetCDF peak detection, `xcmsSet` can use up to 30-40 seconds (single LCMS file ~133 MB), while the same data converted to mzML runs in about 10-14 seconds. It is quite clear that there is something I'm missing here. Does the mzML format contain a list of peaks? Or additional information that speeds up peak detection?

**Comment by sneumann** [comment]
Hi, so what was the solution, just for the record ?

**Comment by Gronnesby** [comment]
The problem seemed to be with conversion of the files rather than with XCMS.
Converting proprietary Agilent formats on UNIX based platforms seems to have some side-effects causing the .CDF files to be poorly formatted. So it seems that XCMS used an excessive amount of time reading the file, however not failing, but I don't really have the proper R expertise to get to the root of the problem. Reconverting the files on a windows platform seemed to solve the problem.
