### ISSUE TITLE
RT correction for xcmsSet 

### ISSUE THREAD

**Issue by manohar8** [sneumann/xcms#306]
Hello developers,
I wish to do retention time correction during grouping stage of xcmsSet generation. I could not find example/demo code for this step in xcms package. Please give a hint about how should be the parameters set for retcor obiwrap function except for profstep (xset2 below) and how to validate retention time correction. Can you provide some examples for rt correction of xcmsSet object?

`xset<-xcmsSet(method="centWave", ppm=5, peakwidth=c(10,60))`

`sampclass(xset) <- c(rep("C12_Data",2), rep("C13_Data",2))`

`**xset2<- retcor(xset,method="obiwarp", profStep=0.1)**`

Thank you,
Manohar

**Comment by jotsetung** [comment]
I strongly suggest you to use the most recent `xcms` version (R version 3.5.1, `xcms` version 3.2.0) and the *new* user interface. You should no longer use the `xcmsSet` function and objects. For details and examples you can check the `xcms` vignette: http://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html

It might also not hurt to have a look at https://jotsetung.github.io/metabolomics2018/xcms-preprocessing.html for some more details and hints how to best choose parameter settings.

For obiwarp alignment settings please have a look at the corresponding help page (i.e. type `?ObiwarpParam` in the R terminal after loading `xcms` with `library(xcms)`).

**Comment by jotsetung** [comment]
Closing the issue; feel free to re-open if needed.
