### ISSUE TITLE
xcmsSet problem 

### ISSUE THREAD

**Issue by bernt-matthias** [sneumann/xcms#308]
I'm trying to call `xcmsSet(method="centWave")` using the latest xcms from bioconda (3.0.0) on https://github.com/workflow4metabolomics/xcms/files/2289951/Sihumi_IPP_A1.mzML.gz but I get: 

```
Error in seq.default(object@scanindex[scan] + 1, min(object@scanindex[scan +  : 
  'from' must be of length 1
```

Is there something wrong with my data? 

Actually I try to run the galaxy tool (which uses version 1.4.8) which gives a similar error: 

```
Error in seq.default(object@scanindex[scan] + 1, min(object@scanindex[scan +  : 
  'from' must be of length 1
Calls: do.call ... .local -> getScan -> getScan -> .local -> seq -> seq.default
In addition: Warning message:
In `[<-`(`*tmp*`, "object", value = <S4 object of class "xcmsRaw">) :
  implicit list embedding of S4 objects is deprecated
Execution halted
```

https://github.com/workflow4metabolomics/xcms/issues/94

**Comment by jotsetung** [comment]
Indeed, the file you have has only a single spectrum in it, and apparently the *old* xcms user functions and classes struggle with that.

```r
> library(xcms)
> xcmsSet(files = "Sihumi_IPP_A1.mzML", method = "centWave")
Error in seq.default(object@scanindex[scan] + 1, min(object@scanindex[scan +  : 
  'from' must be of length 1
> 
> ## Using the new functions, read the data first
> raw_data <- readMSData("Sihumi_IPP_A1.mzML", mode = "onDisk")
> raw_data
MSn experiment data ("OnDiskMSnExp")
Object size in memory: 0.03 Mb
- - - Spectra data - - -
 MS level(s): 1 
 Number of spectra: 1 
 MSn retention times: 0:0 - 0:0 minutes
- - - Processing information - - -
Data loaded [Wed Aug 22 13:09:35 2018] 
 MSnbase version: 2.7.3 
- - - Meta data  - - -
phenoData
  rowNames: Sihumi_IPP_A1.mzML
  varLabels: sampleNames
  varMetadata: labelDescription
Loaded from:
  Sihumi_IPP_A1.mzML 
protocolData: none
featureData
  featureNames: F1.S1
  fvarLabels: fileIdx spIdx ... spectrum (29 total)
  fvarMetadata: labelDescription
experimentData: use 'experimentData(object)'
```

Note also that methods like `centWave` perform peak detection along the retention time dimension. With a single spectrum (i.e. only one time point) this is not possible.
For the newer user functions and workflow have a look at http://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html and eventually http://bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms-direct-injection.html that describes the analysis of single spectrum, direct injection data.

**Comment by bernt-matthias** [comment]
Thanks a lot. We will check the links that you provided.
