### ISSUE TITLE
Documentation: roxygen'ified documentation

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#31]
Would it make sense to add all forthcoming documentation 
in roxygen format ?

**Comment by jotsetung** [comment]
Yes, definitely; eventually `roxygen2`.

**Comment by stanstrup** [comment]
In case you didn't know it there is a package that should be able to copy classical man pages to the right place in the .R files. --> Rd2roxygen

The package crashed when I tried to use it on a whole package but one Rd file at a time worked. http://yihui.name/Rd2roxygen/#parse-a-single-rd-file

When there are aliases you probably want to put @rdname in the right places manually though.

**Comment by jotsetung** [comment]
thanks, I'll have a look at it. In the worst case I will just use roxygen for new functions/methods.

**Comment by jotsetung** [comment]
Closing this because all new documentation is added as roxygen.
