### ISSUE TITLE
mzTab to xcmsSet

### ISSUE THREAD

**Issue by tsufz** [sneumann/xcms#316]
Hi,
We would need a mzTab to xcmsSet importer for some purposes. So far this is not implemented in xcms, if I am correct? Are there an plans to do so and pros / cons? We could commit some time for implementation.

Best
Tobias

**Comment by jotsetung** [comment]
AFAIK there is an mzTab *exporter* but no importer in `xcms`. Note however that `MSnbase` does have an mzTab importer (`MzTab`) - before implementing redundant code in `xcms` I would suggest that you check first if that would suffice?

**Comment by tsufz** [comment]
Okay, yes, this might work! We will checkout.
