### ISSUE TITLE
Bounding functions

### ISSUE THREAD

**Issue by ivaihn** [sneumann/xcms#319]
I would like to point out, that the lower_bound and upper_bound functions as well as lowerBound and upperBound functions are essentially equal - both contions and if-else branches are reversed.  The only exception is the equality of m/z values which is very unlikely in mass spectromery experiments.

**Comment by sneumann** [comment]
Hi, that is indeed true for high-resolution measurements, 
but I have also seen nominal mass data with integer values, 
where identical m/z is not too uncommon. I'd like to close as wontfix,
unless someone re-opens and convinces me otherwise. Yours, Steffen
