### ISSUE TITLE
Improvement suggestion: highlightChromPeaks by filling the area of the detected peaks

### ISSUE THREAD

**Issue by etrh** [sneumann/xcms#324]
Would it be possible to add a new functionality to `highlightChromPeaks` that would fill the area of the detected peaks instead of drawing rectangles around them? It is sometimes difficult to understand what is exactly being picked as a peak by looking at the rectangles. 

An example of the feature I am requesting is implemented in `Agilent MassHunter`:

![agilent_masshunter_example_detected_peaks](https://user-images.githubusercontent.com/29725715/47555197-72482b00-d90b-11e8-8c8e-ea57c04d9143.png)

**Comment by jotsetung** [comment]
Yup, that would look definintely better - I'll think of a way to do that. If you have already an idea in mind you are also welcome to implement that and create a pull request.

**Comment by stanstrup** [comment]
If you are using ggplot2 this is probably what you need to implement that: 
http://www.sthda.com/english/wiki/ggplot2-area-plot-quick-start-guide-r-software-and-data-visualization#coloring-under-density-curve-using-geom_area

To avoid the warnings that gives (because they put zero height) I assume you can create an appropriate matrix for each segment instead that only contains the segment.

**Comment by stanstrup** [comment]
I was curios so I wrote something. Here it is in case it is helpful. I apologize for the tidyverse syntax. I can't really think in standard R terms anymore...



```r
library(ggplot2)
library(dplyr)
library(purrr)
library(tidyr)


df <- data.frame(
  sex=factor(rep(c("F", "M"), each=200)),
  weight=round(c(rnorm(200, mean=55, sd=5),
                 rnorm(200, mean=65, sd=5)))
  )



dat <- with(density(df$weight), data.frame(x, y)) %>% 
        filter(x>30 & x< 80)



intervals <- data.frame(start = c(40,65, 47), end = c(50,70, 60)) %>% 
             mutate(interval = as.factor(1:nrow(.))) %>% 
             mutate(interval_dat = map2(start,end, ~dat %>% filter(x>..1 & x<..2))) %>% 
             select(interval,interval_dat) %>% 
             unnest



ggplot(data = dat, mapping = aes(x = x, y = y)) +
    geom_line() + 
    geom_area(data=intervals, aes(fill = interval), position = "identity", alpha=0.5)
```

**Comment by jotsetung** [comment]
@stanstrup for your input! For basic R plotting it can be done with `polygon`. Only thing is that the actual chromatogram data has to be read also within `highlightChromPeaks`.

**Comment by jotsetung** [comment]
OK, implementation was easier than expected. @etrh if you want to use it you'll have to install the latest version from github. There is now the possibility to select `type = "polygon"` in `highlightChromPeaks`. Peaks will be filled with the color defined with argument `col` and drawn with `border` (set to `NA` to not draw any borders).

**Comment by etrh** [comment]
Thanks for being so quick with this! Much appreciated. It works very well and I will continue using it and report any bugs that might arise later on. Thanks again. A very useful feature.

**Comment by jotsetung** [comment]
So I'm closing this issue for now. Feel free to re-open if you encounter problems.
