### ISSUE TITLE
Align only a subset of samples in a data set and align the remaining based on interpolation

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#335]
This picks up the idea from issue #234: assumption is that samples are measured sequentially, and that the rt-shift from one measurement to the next is rather small.
Given we have a data set that includes some samples that can not be nicely aligned together with the other samples (e.g. are *blanks*), align only samples defined with a parameter `subset` with each other. Samples that were left out (i.e. are not part of `subset`) should then be adjusted based on the alignment vector (difference raw-adjusted retention time) of the closest sample in the dataset (in terms of injection index).

Example:
Data set consists of 7 files: *blnk1*, *smpl1*, *smpl2*, *blnk2*, *smpl3*, *smpl4*, *blnk3*
- initial alignment with `subset = c(2, 3, 5, 6)` will align the samples and leave the blanks out.
- blanks will then be aligned based on the adjustment performed on the next non-blank sample (or on the previous non-blank sample in case that the blank is the last file in the dataset.

For the example this means that *blnk1* is adjusted based on *smpl1*, *blnk2* on *smpl3* and *blnk3* on *smpl4*.

We leave it to the user to have the samples arranged in a way that makes sense.

**Comment by jotsetung** [comment]
We do have already the `.applyRtAdjustment` function in place. This takes numeric values, raw and adjusted retention times and adjusts the numeric values based on the latter two.

**Comment by jotsetung** [comment]
Note: interpolating the adjustment of samples based on adjusted samples left and right of an unadjusted sample would only be possible if we would find a way to generate "reference" raw and adjusted retention times by aggregating the raw and adjusted retention times of the surrounding samples. 

The immediate solution is to simply adjust the unadjusted sample based on the adjustment of the closest adjusted sample (closest in injection index).

**Comment by jotsetung** [comment]
The method implemented so far (`"previous"`) adjusts a non-subset sample based on the closest previous subset sample and results in most instances in identical adjusted retention times for the non-subset sample and the subset sample that was used for normalization.

We might also want to have an alternative approach with an interpolated alignment using the previous and next subset sample.

**Comment by jotsetung** [comment]
All implemented now.

**Comment by stanstrup** [comment]
This is great! Really opens the door to better use of blanks. Thanks!

**Comment by gmhhope** [comment]
I am going after #232, #234 and #335 and finally reach here. That is a long journey to dig out. @jorainer

**Comment by jorainer** [comment]
I know :) - also, I tend to forget github issues after some time. Anyway, many of the information *should* be provided in the `xcms` package vignettes and documentation - I hope at least.
