### ISSUE TITLE
group/alignment of XChromatograms objects

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#336]
Now that there is all the functionality to do peak peaking on arbitrarily created Chromatograms it would be really nice to be able to also do grouping. You can basically use XCMS on any data where you can extract chromatograms. I am trying to do this for LC-UV data.

Could an XChromatograms be coerced to an XCMSnExp? Then the rest could just go from there.

**Comment by jotsetung** [comment]
Nope, a `XChromatograms` can not be coerced into an `XCMSnExp` - but it should be straight forward to do the sample grouping on the `XChromatograms` (the `plotChromPeakDensity` does already simulate the grouping). I'll have a look into it. 

The tricky thing is that the `XChromatogram` has *m* rows and *n* columns, with *m* being m/z (rt) slices and *n* being the samples. We want to group only across *n*, separately for each row.

**Comment by jotsetung** [comment]
Having a look at it this is what has to be done:
- [ ] add a slot `featureDefinitions` to `XChromatograms`
- [ ] the `featureDefinitions` `DataFrame` will have an empty `mz` column, but we need a column `row` to know in which row of the `XChromatograms` the feature was grouped/defined.
- [ ] implement `hasFeatures,XChromatograms` method.
- [ ] implement a `.group_chrom_peaks_density` function that bases on the code of `do_groupChromPeaks_density` (the inner `while` loop). Ideally, this function would then also called by the `do_group...`.
- [ ] the `[,XChromatograms` method should ensure that `featureDefinitions` is correctly subset. For rows subset it to the `row` column matches the index, for columns drop the `featureDefinitions` alltogether.
- [ ] implement a `featureValues,XChromatograms` method.

**Comment by jotsetung** [comment]
Hell yes. That might be a thing too. We can add an issue on that to not forget it - but let's first finish this thing here :)

**Comment by jotsetung** [comment]
It's done!
