### ISSUE TITLE
Multithreading of findChromPeaks on Chromatograms object

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#337]
`findChromPeaks` doesn't seem to be multithreaded when working on `Chromatograms`.

`findChromPeaks` has the BPPARAM paramenter but it seems to be ignored for `Chromatograms`.
`bpparam()` says:

```r
class: SnowParam
  bpisup: FALSE; bpnworkers: 30; bptasks: 0; bpjobname: BPJOB
  bplog: FALSE; bpthreshold: INFO; bpstopOnError: TRUE
  bptimeout: 2592000; bpprogressbar: FALSE
  bpRNGseed: 
  bplogdir: NA
  bpresultdir: NA
  cluster type: SOCK
```

**Comment by jotsetung** [comment]
Yup, you're right. I did not add the `BPPARAM` parameter to `findChromPeaks,Chromatograms`. Somehow that slipped through, thanks for spotting @stanstrup !

**Comment by jotsetung** [comment]
Done.

**Comment by stanstrup** [comment]
Thanks! Works.
