### ISSUE TITLE
Consider moving MassSpecWavelet from Suggests to Imports

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#34]
Was there any reason for putting *MassSpecWavelet* into DESCRIPTION's *Suggests* instead of *Imports*?
Actually this applies also to *multtest*, *RANN* packages.
I would find it cleaner to put all the packages that are required for data analysis methods into *Imports.* That way these packages will also be installed and all analysis methods will work without errors.

**Comment by sneumann** [comment]
IIRC one motivation was to have less required dependencies, 
which are only required for very rarely used functionality. 
Let's go for the clean way. This also allows to remove the  
convoluted way of calling library(RANN) to avoid that R CMD check
detects that RANN is not in Depends/Imports :-)

**Comment by jotsetung** [comment]
Done in https://github.com/sneumann/xcms/commit/72f8d6d69fb9b41f77ad6875a40766bbaa429b07

For now there is still some internal `require` for packages `rgl` `Rgraphviz` `XML` and `ncdf4`. I would keep them for now, since they are not used in the actual analysis methods, and I know that some of them can be painful to install and might break package installation on some systems.
