### ISSUE TITLE
chromatogram,XCMSnExp should extract full blown XChromatograms objects

### ISSUE THREAD

**Issue by jorainer** [sneumann/xcms#342]
The `chromatogram,XCMSnExp` method to extract ion chromatograms should extract an `XChromatograms` object with identified chromatographic peaks (`chromPeaks`), feature definitions (`featureDefinitions`) and processHistory (`processHistory`), if they are present in the `XCMSnExp` object.

This will simplify many visualization tasks on the EICs and will be big fun in general.

**Comment by jotsetung** [comment]
`chromatogram,XCMSnExp` returns already chromatographic peaks and features within the specified m/z rt range - if present in the `XCMSnExp`.

**Comment by jotsetung** [comment]
I just have to update the vignette on that.

**Comment by jorainer** [comment]
All done
