### ISSUE TITLE
Data structures for SWATH data

### ISSUE THREAD

**Issue by michaelwitting** [sneumann/xcms#346]
To start to work on SWATH data we would need some tweeks for the data structures. Currently, I perform alignment etc on the MS1 level, which is fine. MS2 data is shifted accordingly.
However, to work with the SWATH data and to perform peak picking for the individual SWATH pockets I'm splitting the data like this:

```
xrms <- readMSData(files, mode = "onDisk", centroided = TRUE)

xrms_ms1 <- filterMsLevel(xrms, msLevel = 1)
xrms_ms2 <- filterMsLevel(xrms, msLevel = 2)

precursors <- fData(xrms_ms2)$precursorMZ

xrms_ms2_swath <- split(xrms_ms2, f = as.integer(precursors))
```
Then I'm performing peak picking on the individual levels.

```
ms1data <- findChromPeaks(xrms_ms1, param = cwp, msLevel = 1)

ms2data <- lapply(xrms_ms2_swath, FUN = findChromPeaks, param = cwp, msLevel = 2)
```

Working with real data sets this might lead to confusion to have different lists etc.

It would be good if we can have methods and results for a single object. E.g. picked peaks can flagged with the MS level and the precursor mass or the index of the SWATH pocket.

**Comment by jotsetung** [comment]
Can you share one file and some code - workflow? We can then think of what would have to be implemented.

**Comment by michaelwitting** [comment]
Examples can be found in my repository for the Metabolomics 2018:

[https://github.com/michaelwitting/metabolomics2018](url)

Hope that helps...

**Comment by jotsetung** [comment]
OK, I'll have a look at it and come back with some questions ;)

**Comment by michaelwitting** [comment]
Anytime :-D
I could think of a peak picking function, which selects one SWATH pocket and makes peak detection and adds some flags. With the current workflow I have for each pocket a single peak list. That is not very nice...

**Comment by michaelwitting** [comment]
Ooppsss... Wrong button... sorry

**Comment by jotsetung** [comment]
I think it's now finally time to work on this. My first thoughts on that are:
- the `chromPeaks` table now has already a columns `ms_level` that allows to discriminate between peaks detected in MS1 and in MSn.
- Question is if we want to add also a precursor_mz to the `chromPeaks` table. If possible I would like to avoid that, because the matrix will get pretty large (or we make the column `optional`, but probably it's better to store that as an additional variable somewhere, something like `chromPeakData` that might contain additional annotations for a chromatographic peak. Something only MS2 peaks will have at present. The link could be made with the peak IDs (i.e. rownames of the `chromPeaks` matrix).

**Comment by jotsetung** [comment]
Actually, thinking it over I like the idea. It would be something like `featureData` that has additional annotations for the spectra (i.e. spectrum header). `chromPeakData` could also be a `DataFrame` with annotations for the `chromPeaks`.

**Comment by michaelwitting** [comment]
For SWATH data we actually not only need the info if a `chromPeak` came from MS1 or MS2, but also from with MS2 isolation window (aka SWATH pocket) it came from.
precursor_mz is not known (data independent fragmentation)

**Comment by jotsetung** [comment]
Even better for a *generic* chromatographic peak annotation data frame then.

**Comment by jotsetung** [comment]
Extracting isolation window from mzML is going on: https://github.com/sneumann/mzR/issues/193

**Comment by jotsetung** [comment]
PR is in `mzR`.

**Comment by jorainer** [comment]
The data structures to store and identify chromatographic peaks found in SWATH pockets are in.
