### ISSUE TITLE
do_groupChromPeaks_nearest does not accept data frame

### ISSUE THREAD

**Issue by DWgit** [sneumann/xcms#359]
The doc for `do_groupChromPeaks_nearest` says
> peaks: A ‘matrix’ or ‘data.frame’ with the mz values and retention ...

but the type-checking code in `do_groupChromPeaks-functions.R` is:
```   
   if (!is.matrix(peaks) | is.data.frame(peaks))
        stop("Peaks has to be a 'matrix' or a 'data.frame'!")
```
The `!` operator has higher precedence than `|`, so a data frame hits the stop. An obvious fix is to add parens `if (! (... | ...))`

**Comment by jotsetung** [comment]
Good point! I'll fix.

**Comment by jotsetung** [comment]
It is fixed in the current developmental version (*master* branch) and also in the branch matching the version from Bioconductor version 3.8. To install the latter:

```r
devtools::install_github("sneumann/xcms", ref = "RELEASE_3_8")
```

**Comment by DWgit** [comment]
Thanks for the speedy fix!

**Comment by jotsetung** [comment]
I'm closing the issue now. Feel free to re-open if needed.
