### ISSUE TITLE
XCMSnExp to xcmsSet object

### ISSUE THREAD

**Issue by jsaintvanne** [sneumann/xcms#362]
Hi,

I'm using XCMS 3.x to do my peakpicking with my files. After this peakpicking, I use the following function : 
```
xset <- as(xobject, 'xcmsSet'))
```
And I obtain this error : 
```
Error in asMethod(object) : 
  Coercing an XCMSnExp with MS level > 1 is not yet supported!
```
My problem is that I have datas with also MS2 level and I can find that this error come from here : 
```
#' Convert an XCMSnExp to an xcmsSet.
#' 
#' @noRd
.XCMSnExp2xcmsSet <- function(from) {
    if (any(msLevel(from) > 1))
        stop("Coercing an XCMSnExp with MS level > 1 is not yet supported!")
```

So is there a way to select MS1 datas after a peakpicking ? Because I tried `filterMsLevel` function and it erase the peakpicking... Am I right ?

Thanks for the answer :)

Julien

**Comment by jotsetung** [comment]
Indeed - at present preprocessing results are removed by `filterMsLevel`. This should however be changed - I still have to think about is.

For now the only way is to call `filterMsLevel` *before* running the peak detection.

**Comment by jotsetung** [comment]
I'm working on it... but this will go into the current developmental version.

**Comment by jsaintvanne** [comment]
Thanks for your answer @jotsetung  !

Effectively, I'm doing it with this `filterMSLevel` parameter for the moment.

Good luck with it and thanks again for the answer !

Julien

**Comment by jotsetung** [comment]
OK. It is now in the `master` branch. I will also backport that to the `RELEASE_3_8` branch.

**Comment by jotsetung** [comment]
I've also updated the `RELEASE_3_8` branch. You can install that version with
```r
devtools::install_github("sneumann/xcms", ref = "RELEASE_3_8")
```

`filterMsLevel` keeps now detected chromatographic peaks and features if `msLevel = 1`.

**Comment by jsaintvanne** [comment]
Whaou really really effective !! :)

I will try this of course ! I just ask myself if I was clear enough in my question because this answer puts me in doubt... 
> filterMsLevel keeps now detected chromatographic peaks and features if msLevel = 1.

I would like that after a peakpicking without msLevel selected, I can select only MS1 datas and keep the peakpicking that correspond to it. I will look at your changes to be able to tell you !

In all cases thanks a lot for your really fast and effective answer !

**Comment by jotsetung** [comment]
Assume you have mzML files with MS1 and MS2 levels, and your data objects contains spectra of both MS levels. You did now peak detection and all other processing (alignment, peak grouping) in MS1 (the default). Now you want to subset your object to contain just MS1 spectra: `filterMsLevel(data, msLevel = 1L)`. After the update/fix this will return an `XCMSnExp` that contains only MS1 spectra, but **also** all identified chromatographic peaks, adjusted retention times and features. I hope this is clearer now.

**Comment by jsaintvanne** [comment]
Hi,

Sorry I can't tested it yesterday but I have just done it and it looks great !!
Thanks for your explanations and your disponibility !!

Hope this update will be useful for a lot of people.

Thanks you

**Comment by jotsetung** [comment]
Thanks for posting the issue - I always wanted to implement it properly, but completely forgot about it ;)

Closing the issue, feel free to reopen if needed.
