### ISSUE TITLE
Diffreport-how to adjust EIC m/z step ?

### ISSUE THREAD

**Issue by CLechaplais** [sneumann/xcms#371]
Hi Steffen,
I got another problem with the diffreport function, that's about adjusting the m/z step for EIC generation.
Before XCMS3, I was using "profparam" inside the xcmsSet() function.
Example : 
`xset<-xcmsSet(datafiles, method="centWave", ppm=4.4,profparam=list(step=0.005),peakwidth=c(11.2,24.5), snthresh=3, prefilter=c(3,100), mzdiff=-0.0009, integrate=1, noise=1000 ,BPPARAM=bpparam())`  

With XCMS3, using "readMSData()" and "findChromPeaks()"... until "as(..., "xcmsSet")" then doing the diffreport(), I have tried many ways to adjust this m/z step but I can't find how to do.
Needing some help please.
Thanks.

Kind regards,

Christophe

**Comment by CLechaplais** [comment]
Hi,
ok, I have found how to edit step for binning while creating the diffreport.
`xset@profinfo$step=(numeric)`

Kind regards
Christophe

**Comment by sneumann** [comment]
Thanks for reporting the solution.

Closing #371


I blame Android for the brevity and typos
