### ISSUE TITLE
NetCDF not closing again? 

### ISSUE THREAD

**Issue by drupadt** [sneumann/xcms#373]
We had this issue earlier in March and new version fixed it. I think it may be the case again with newer version of R. I am again getting the same error for NetCDF as in this issue thread:

"https://github.com/sneumann/xcms/issues/363#issue-423654604"

The only thing that's changed is, I recently updated from R 3.5.2 to R 3.5.3. I am going to roll back and work on 3.5.2 but thought will post this hear since it may be a recurring issue with each update of R?

**Comment by sneumann** [comment]
Hi, the issue should be independent of the version of R. 
Can you provide `sessionInfo()` to check that you have the version 
with the fix installed ? Yours, Steffen

**Comment by drupadt** [comment]
Not sure why, but somehow, mzR was failing to load rather than xcms. It was looking for rcpp 1.0.0 but after installing developmental version, things have gone back to normal.

**Comment by sneumann** [comment]
Great, closing then. Yours, Steffen
