### ISSUE TITLE
Potential problem with .align_chromatogram due to approx

### ISSUE THREAD

**Issue by jorainer** [sneumann/xcms#378]
Hi @michaelwitting , would like to get your thoughts on this:
we are using `approx` to align chromatograms which, however, can also interpolate intensity values and thus add additional data points, that might not be there in the original chromatogram:

```r
rt1 <- 1:10
rt2 <- c(3, 4, 6)
int2 <- c(5, 1, 7)

approx(rt2, int2, rt1)
$x
 [1]  1  2  3  4  5  6  7  8  9 10

$y
 [1] NA NA  5  1  4  7 NA NA NA NA

``` 

So, after aligning the second chromatogram has 4 intensities, while before it had only 3. I think the interpolation that is going on for the data point between rt 4 and 6 is not correct. What do you think?

**Comment by michaelwitting** [comment]
True, but I don't have another solution yet. Binning on the same rt scale maybe? I talked with Steffen some time ago on what would be the best. With thought that the interpolation might be the best solution.

**Comment by jorainer** [comment]
Thinking it over - for that particular application interpolation is OK, because we're later anyway correlating them. Just for a *general purpose* application it would not work. I'll think of a possible solution to this - should be doable, even using the `approx` function, but I'll also have to define more unit tests to see whether we always get what we want.

**Comment by jorainer** [comment]
Ahg, no, seems to be tricky in the end. `approx` is nice and fast - but does a lot of interpolation... let's see if we get around that.

**Comment by jorainer** [comment]
After some more thoughts - interpolation makes sense in our use case as the chromatograms are measured in the same run. So, intensities should be adjusted also based on the retention time differences between the chromatograms.

Still, would like to have an alternative that assigns data points between chromatograms to each other based on similarity of their retention times.

**Comment by michaelwitting** [comment]
In SWATH the difference between the MS1 and MS2 retention time of a data point is given by the multiple of the dwell time, the first MS2 comes directly after the MS1, the next one after one MS2 dwell time, then two times, etc...
We will never get the real intensity value of the MS2 mass at the RT of the MS1 Therefore, I think interpolation is the best way.

**Comment by jorainer** [comment]
Agree. 

In addition, I've implemented also a `.match_closest` function that would allow to match intensity values between chromatograms based on similarity of their retention times. So, we can decide which method to use. I'll add an option `interpolate` to `.align_chromatogram` that allows to choose how to align them.

**Comment by jorainer** [comment]
So, for SWATH the `approx` approach should be OK.
