### ISSUE TITLE
Extract ROIs for specific rt-mz windows from mzML

### ISSUE THREAD

**Issue by YasinEl** [sneumann/xcms#392]
Hello,

is there a way to extract ROIs for specific rt-mz windows from mzML files, without performing any peak detection? I cannot find a function to do it in the XCMS package. Is there non or am I just missing it?

Thank you a lot in advance!
Yasin

**Comment by jorainer** [comment]
Sure - but it is then functionality from the `MSnbase` package: after reading the data with `readMSData` the `chromatogram` function can be used to extract an ion chromatogram with the data from the specified retention time (parameter `rt`) and m/z range (parameter `mz`). See the `xcms` vignette for details on this.

Alternatively, it is possible to use the `filterRt` and `filterMz` functions to restrict the data to the specified retention time and m/z range (which will not calculate/convert the data into chromatographic representation). In that case it is possible to extract the spectrum data. Have also a look at https://jorainer.github.io/metabolomics2018/xcms-preprocessing.html (or the corresponding *xcms-preprocessing.Rmd* in https://github.com/jorainer/metabolomics2018) for an introduction of MS data handling with `MSnbase`/`xcms`.

**Comment by YasinEl** [comment]
Thank you a lot for the quick response!

with the `chromatogram()` function I can extract a chromatogram via binning. I would prefer to get an XIC like it is done prior to centwave-peak detection, meaning that XICs are created by "following" real mass peaks.

**Comment by jorainer** [comment]
the `chromatogram` function does not use any binning, it *aggregates* the intensities within each spectrum (i.e. for one retention time) across the m/z range. The parameter `aggregationFun` allows to specify how the intensities are aggregated (either summed or using the maximum...).

If this is not what you want you can use the second option with the `filterRt` and `filterMz`. This firstly reduces the data set to the spectra within the retention time range and then reduces each spectrum to the provided m/z range. With `mz` and `intensity` you could extract the m/z and intensity values from the such reduced data set. Or, even better, use `spectrapply(data, as.data.frame)` with `data` being your sub-setted object, to extract the spectra data as `data.frame`s. That way you have really the raw data, m/z and intensity value pairs.

**Comment by YasinEl** [comment]
My problem with that approach is that I have to know the mz range I want to extract in advance. I would rather like to find the mz traces which are there without more prior assumptions.  e.g. for mz 120 to 121 and rt 1150 to 1180 I would like to have all mz traces there. If I would do that with the approaches named before I could potentially split chromatograms into two different traces.

Thank you a lot for your time again!

**Comment by jorainer** [comment]
In that case I suggest that you filter your object first by retention time and then simply plot the data, per spectrum:

```
data <- readMSData(<files>, mode = "onDisk")
data_sub <- filterMz(filterRt(data, rt = c(1150, 1180)), mz = c(120, 121))
## With this plot you could actually see all the individual data points
plot(data_sub, type = "XIC")

## Alternatively, extract the spectra and plot them
sps <- spectra(data_sub)
## Plot the first spectrum, you should be able to see the mass peaks, e.g.
## if you have a single signal in that m/z range 
plot(sps[[1]])
```

**Comment by YasinEl** [comment]
Thank you, that absolutely makes sense for looking at a specific case. However, I would rather need a automated extraction of different XIC traces. 
I assume the function `findmzROI()` should do this job? However it seems like it is not a part of XCMS anymore? At least I can not access it.

**Comment by jorainer** [comment]
`findmzROI` should still be there - it is however not exported or maintained anymore (but should still be working). You can access it with `xcms:::findmzROI`

**Comment by YasinEl** [comment]
Works perfectly,  thank you a lot for your time and patience!
