### ISSUE TITLE
Installation ERROR: configuration failed for package ‘Rhdf5lib’

### ISSUE THREAD

**Issue by sorenwacker** [sneumann/xcms#394]
I am trying to install xcms locally with `BiocManager::install("xcms")`. The installation process stops with the following output:
```
...
checking if zlib is wanted... yes
checking for inflateEnd in -lz... no
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
checking zlib in /usr... failed
configure: error: either specify a valid zlib installation with --with-zlib=DIR or disable zlib usage with --without-zlib
ERROR: configuration failed for package ‘Rhdf5lib’
```

**Comment by sneumann** [comment]
Hi, which operating system / distribution is that ? The error indicates that you need 
the developer files for zlib, On Ubuntu that's `apt install zlib1g-dev`, on Redhat it'll be different. 
Yours, Steffen

**Comment by soerendip** [comment]
It is Ubuntu and `sudo apt-get install zlib1g-dev` returns: 

```
> zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
> 0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
```

**Comment by jorainer** [comment]
Could you please provide the output of `sessionInfo()`. 
Also, it seems that `Rhdf5lib` is the culprit, please try to install it directly with `BiocManager::install("Rhdf5lib")`.

**Comment by soerendip** [comment]
```
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS/LAPACK: /home/swacker/miniconda3/envs/py3/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.1
```

I tried installing Rhdf5lib on its own and it gave the same error message.

**Comment by MikeHala** [comment]
Hello,

I have similar problem

conda install -c anaconda zlib
# All requested packages already installed.
# packages in environment at /exports/igmm/eddie/bioinfsvice/mhalache/anaconda/envs/scEyeMap:
#
zlib                      1.2.11               h7b6447c_3    anaconda


> BiocManager::install("Rhdf5lib")
Bioconductor version 3.9 (BiocManager 1.30.4), R 3.6.0 (2019-04-26)
Installing package(s) 'Rhdf5lib'
trying URL 'https://bioconductor.org/packages/3.9/bioc/src/contrib/Rhdf5lib_1.6.0.tar.gz'
.....
checking if zlib is wanted... yes
checking for inflateEnd in -lz... no
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking zlib in /usr... failed
configure: error: either specify a valid zlib installation with --with-zlib=DIR or disable zlib usage with --without-zlib
ERROR: configuration failed for package ‘Rhdf5lib’

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Scientific Linux 7.5 (Nitrogen)

Matrix products: default
BLAS/LAPACK: /gpfs/igmmfs01/eddie/bioinfsvice/mhalache/anaconda/envs/scEyeMap/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.6.0

Thanks,
Mike

**Comment by sneumann** [comment]
I think those errors should be reported to https://github.com/grimbough/Rhdf5lib
Yours, Steffen

**Comment by grimbough** [comment]
There's an open issue for this error at https://github.com/grimbough/Rhdf5lib/issues/21
