### ISSUE TITLE
findmzROI() - adaptation

### ISSUE THREAD

**Issue by YasinEl** [sneumann/xcms#396]
Hello,

I am trying to implement the findmzROI() function in some code but would need rtmax and rtmin rather than scmax and scmin in the output.  Therefore I wanted to adapt your function a bit. However I can't find the source code. More specifically:

`getMethod("findmzROI", "xcmsRaw")`

is giving me: 

```
function (object, ...) 
{
    .local <- function (object, mzrange = c(0, 0), scanrange = c(1, 
        length(object@scantime)), dev, minCentroids, prefilter = c(0, 
        0), noise = 0) 
    {
        scanrange[1] <- max(1, scanrange[1])
        scanrange[2] <- min(length(object@scantime), scanrange[2])
        if (!is.double(object@env$mz)) 
            object@env$mz <- as.double(object@env$mz)
        if (!is.double(object@env$intensity)) 
            object@env$intensity <- as.double(object@env$intensity)
        if (!is.integer(object@scanindex)) 
            object@scanindex <- as.integer(object@scanindex)
        ROIs <- NULL
        withRestarts(tryCatch({
            ROIs <- .Call("findmzROI", object@env$mz, object@env$intensity, 
                object@scanindex, as.double(mzrange), as.integer(scanrange), 
                as.integer(length(object@scantime)), as.double(dev), 
                as.integer(minCentroids), as.integer(prefilter), 
                as.integer(noise), PACKAGE = "xcms")
        }, error = function(e) {
            if (grepl("m/z sort assumption violated !", e$message)) {
                invokeRestart("fixSort")
            }
            else {
                simpleError(e)
            }
        }), fixSort = function() {
            for (i in 1:length(object@scanindex)) {
                scan <- getScan(object, scan = i)
                if (is.unsorted(scan[, "mz"])) {
                  message("Scan ", i, " is unsorted. Fixing.")
                  o <- order(scan[, "mz"])
                  start <- object@scanindex[i] + 1
                  end <- start + nrow(scan) - 1
                  object@env$mz[start:end] <- scan[o, "mz"]
                  object@env$intensity[start:end] <- scan[o, 
                    "intensity"]
                }
            }
            ROIs <<- .Call("findmzROI", object@env$mz, object@env$intensity, 
                object@scanindex, as.double(mzrange), as.integer(scanrange), 
                as.integer(length(object@scantime)), as.double(dev), 
                as.integer(minCentroids), as.integer(prefilter), 
                as.integer(noise), PACKAGE = "xcms")
        })
        return(ROIs)
    }
    .local(object, ...)
}
<bytecode: 0x0000000039bdaad0>
<environment: namespace:xcms>

Signatures:
        object   
target  "xcmsRaw"
defined "xcmsRaw"
```

This does not seem to include the actual ROI detection. Is it possible to access the code somewhere to make those adaptions? 
Sorry if the question is strange, I am a bit of beginner to that whole programming thing. Also would you like to have those kind of questions be submitted somewhere else, since it is not really an issue of your software, but me,..

Yasin

**Comment by jorainer** [comment]
This function is calling C code with `.Call("findmzROI")`. The corresponding C code is in https://github.com/sneumann/xcms/blob/master/src/mzROI.c

problem is that the function (like many functions in the *old* xcms code) does not consider retention times but works only with scan indices. It should however be possible to get from the scan index to the retention time, as the scan index and retention time vectors should be aligned. so if you have the scan index, you can use this to get the corresponding retention time in the retention time vector.

**Comment by YasinEl** [comment]
Thank you, you are of course right! However, I would also like to "test" the claim of the original centWave paper that the ROI algorithm can be adapted to be more gap tolerant:

> Otherwise, in case of samples which might show this phenomenon more often, the algorithm can easily be modified to be even more "gap-tolerant".

**Comment by jorainer** [comment]
I've not tried that extensively, but could the massifquant peak detection work better on that kind of data? It does an initial peak/ROI detection using kalman filters and runs then centWave on them.

**Comment by YasinEl** [comment]
hmm I really only want the mz-boundaries of present mz traces. Apparently massifquant is using a t-test to combine mz traces which are separated by missing scans which sounds interesting. I think I will rather stay with the centwave-ROI algorithm and then use this or another approach to combine those traces.
Thank you for the idea!
