### ISSUE TITLE
Implement/fix getEIC method

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#40]
The current `getEIC` method implementation in _xcms_ causes repeatedly problems (see issues #39 and #7). We should replace it with a more stable version (i.e. without the _buffer_).
The method should also allow to return the raw values instead of just the data from the _profile_ matrix (e.g. when argument `step = 0`). The new implementation should thus combine both the `xcmsRaw` and `getEIC` methods.

The method should take arguments
- `mzrange`
- `scanrange`
- `rtrange`(which is internally translated to `scanrange`).

Some additional notes/properties:
- If `mzrange` is equal to the total M/Z range `getEIC` returns the _TIC_.
- Should have the possibility to choose between the sum of intensities across M/Z or the max (thus also enabling to extract the base peak chromatogram _BPC_).

It will however be pretty tricky to not break any existing functionality.

**Comment by stanstrup** [comment]
Is there even a need for rawEIC? Wouldn't it be better to have one function and if step = 0 pull from the raw data?
rawEIC also seems like a very limited function now in that you can only get one EIC at a time.
You could also get rid of TIC functions that are just EICs on the full mz range.
And have an TIC/BPI option.

**Comment by jotsetung** [comment]
I was even thinking of always pulling from the raw data and do the binning if `step != 0`. There would be no need for the profile matrix; it will however all be a question of performance.

**Comment by stanstrup** [comment]
You probably already know this but the C function getEIC is extremely fast (and uses the raw data) and I think you can easily wrap a very simple R function around it to get what you want. All that is missing is a BPI switch in the C function.

**Comment by jotsetung** [comment]
Digging into the C-code of the `profBin` function used by `getEIC` I'm a little concerned now (see issue #42, i.e. the bins being slightly overlapping).
Obviously, we want to keep the `getEIC` functionality *as-is* to not break compatibility. I will however also implement a binning function that uses non-overlapping bins which will be used for future functionality.

**Comment by jotsetung** [comment]
The `profBin` method is fine (no overlapping bins, see issue #42). Still, I will implement a *general purpose* binning function that allows more customizations than the `profBin` etc methods (and as of now seems to be considerably faster too).

Concerning the `getEIC` method, I would avoid using that method to extract (raw) data. I prefer the alternative way to first extract the raw data and, if needed, do the binning on the extracted data. Seems to be more intuitive (and cleaner) to me.

**Comment by jotsetung** [comment]
What about a single base function that extracts a subset of m/z, intensity and scanindex/retention time from the full data?
This could then be re-used in the `getEIC`, `rawEIC` and `rawMat` methods removing the redundant code in each of them.

**Comment by stanstrup** [comment]
From my playing around with making fast EICs returning a vector/matrix to R of raw data is really slow. Too much memory writing. Much better performance if you keep the summing on the C side for EICs/TICs.

**Comment by jotsetung** [comment]
All will be implemented in C in the end: extraction of the data. For summing, binning etc there are already nicely performing functions in C available (see `binYonX` function).

**Comment by jotsetung** [comment]
Note: in the new user interface, this method is replaced by the `extractChromatograms` method. This method extracts a chromatogram based on the specified `mz` and `rt` range from the *raw* files. The result is a `list` of `Chromatogram` objects, one for each file. For now it does not support providing a matrix of rt and mz values.

**Comment by WMBEdmands** [comment]
Sorry to butt in but I am trying to find a way to pre-emptively output PNGs of all EICs for our final diffreport in an efficient way. The problem we face is when we have a large number of mzXML files on our server we cannot delete them (and free up space) until we are sure we have visualized any and all statistically relevant EICs. With 30k+ peak groups this is not very easy or efficient with `getEIC`. I cannot readily find the `extractChromatograms` method in my xcms package version (v1.50.1)? Is this an in-development function? Thanks in advance.

**Comment by jotsetung** [comment]
Yes, `extractChromatograms` is a devel function. It is in the current Bioconductor 3.6 devel version (xcms version >= 2.99.0).
Eventually you could try installing/using that also from github:
```r
library(devtools)
install_github("sneumann/xcms", ref = "devel")
```
Also, to use the `extractChromatograms` method you have to use the new user interface. Have a look at the *new_functionality* vignette in the xcms package.

**Comment by jotsetung** [comment]
Obsolete because users should by now use the new `chromatogram` function to extract ion chromatograms.
