### ISSUE TITLE
Changing mzML/data file paths after XCMSMSnExp Object is generated

### ISSUE THREAD

**Issue by Gscorreia89** [sneumann/xcms#403]
Hi,

I am currently assembling some xcms based pipelines for processing large datasets (1000 - 4000 injections) on our local HPC system. In order to make the most out of the system, I made some small tweaks to the way xcms is run (run peak picking as array jobs, concatenate individual centWave results into a single dataframe, etc).

After an XCMSSet object is obtained (with or without grouping performed), is it possible on the newer XCMSMsnExp object to change the raw/mzML file path locations? The use case would be to take objects generated on the HPC environment to my local workspace and perform some debugging/benchmarking.

I have seen the mentions on the vignette about it not being recommended, but just asking in case there is any way (don't mind how experimental/ugly it is :D ).

Cheers,
Gonçalo

**Comment by sneumann** [comment]
Main reason we discourage that is that people need to know what they're doing (tm),
and indeed there can be cases where this is necessary.
```
str(xdata)
[...]
  ..@ processingData        :Formal class 'MSnProcess' [package "MSnbase"] with 10 slots
  .. .. ..@ files            : chr [1:6] "/.../solvent-1.mzML" 
```
Thus you can probably (untested!) use `xdata@processingData@files`.
It would be great if you could report back if that works.
Yours, Steffen

**Comment by Gscorreia89** [comment]
Dear Steffen,

Thank you very much for the pointer. 
`xdata@processingData@files <- new_paths` did it for me, and after changing I was able to start fillPeaks as usual. Didn't try other methods, but if I ever come across a problem I will let you know.

Thanks for this,
Gonçalo

**Comment by sneumann** [comment]
Thanks for the feedback, yours, Steffen

**Comment by jorainer** [comment]
Note that there is also the `dirname` methods implemented in `xcms` that allows to change the file path of an `OnDiskMSnExp`. In principle this function does the same as you do, just with some additional checks (normalizing path, checking that file exist).
