### ISSUE TITLE
panel.cor function

### ISSUE THREAD

**Issue by akreutzmann** [sneumann/xcms#405]
Dear Steffen, 

I found the function panel.cor and we are using the function in our package. Since I have not written the function and I would like to cite it I am searching for a good reference. 

I find the name of the function but not the code here: https://www.rdocumentation.org/packages/xcms/versions/1.48.0/topics/panel.cor

And I see that you have an updated package version but I cannot find the function in here anymore: https://github.com/sneumann/xcms/tree/master/R

So, is the below written function from you and how would you like to be cited for it?

Best, 
Ann-Kristin 

panel.cor <- function(x, y, digits=2, prefix="", cex.cor) 
{
    usr <- par("usr"); on.exit(par(usr)) 
    par(usr = c(0, 1, 0, 1)) 
    r <- abs(cor(x, y)) 
    txt <- format(c(r, 0.123456789), digits=digits)[1] 
    txt <- paste(prefix, txt, sep="") 
    if(missing(cex.cor)) cex <- 0.8/strwidth(txt) 
 
    test <- cor.test(x,y) 
    # borrowed from printCoefmat
    Signif <- symnum(test$p.value, corr = FALSE, na = FALSE, 
                  cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
                  symbols = c("***", "**", "*", ".", " ")) 
 
    text(0.5, 0.5, txt, cex = cex * r) 
    text(.8, .8, Signif, cex=cex, col=2) 
}

**Comment by sneumann** [comment]
Hi, thanks for asking. I think the code is still in there, and was last touched by @jorainer :
https://github.com/sneumann/xcms/blame/master/R/functions-xcmsSet.R#L654

Going back to the beginning of time, this was really added by the very first XCMS author Colin:
https://github.com/sneumann/xcms/blame/439aaa7457ebbcbee8b018f9dd052c4ee87aa240/R/xcmsSet.R

So the citation is Smith 2006: https://github.com/sneumann/xcms/blob/master/inst/CITATION#L3

Yours, Steffen

**Comment by akreutzmann** [comment]
Hi Steffen,

thanks for the information. I will use citation as a reference in the
function where I use the code.

Best,
Ann-Kristin

Am Mi., 11. Sept. 2019 um 05:25 Uhr schrieb Steffen Neumann <
notifications@github.com>:
