### ISSUE TITLE
Build error on BioC macOS

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#406]
Hi, we currently have a build error on macOS:

http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/merida1-checksrc.html
```
Running the tests in ‘tests/runTests.R’ failed.
Last 13 lines of output:
  1 Test Suite : 
  mzR RUnit Tests - 39 test functions, 1 error, 0 failures
  ERROR in test_writeMSData: Error in object@backend$getPeakList(x) : 
    [MSData::Spectrum::getMZIntensityPairs()] Sizes do not match.
  Test files with failing tests
     test_write.R 
       test_writeMSData 
```
Let's monitor if that also happens on other arches. Or on other arches that use clang.
Yours, Steffen

**Comment by jorainer** [comment]
I guess that's something temporary.

**Comment by sneumann** [comment]
Indeed. Must've been wrong moon phase. Steffen
