### ISSUE TITLE
xcms as dependency not compatible with CRAN

### ISSUE THREAD

**Issue by cbroeckl** [sneumann/xcms#408]
Hello all, 

I have a had a brief email exchange with @sneumann about this issue, but then remembered that this is exactly what the 'Issues' section of Github is for.   

I am author of the RAMClustR package, which I finally go onto CRAN about a year ago.  All was well, for a while.  However, now I am making edits, pushing to github, and when I go to submit the new version to CRAN, the package is being rejected due to the issues CRAN has had with mzR.  I have a listed dependency on XCMS::groupval and/or XCMS::featureValues functions. Given this, I opted to just add XCMS as a dependency.  XCMS is dependent on mzR, and mzR causes CRAN errors.  As such, any CRAN packages (as far as I can tell) that have dependency on XCMS are going to have to find a different solution.  

I have considered: 
1. extracting groupval and featureValues from XCMS and putting them (redundantly) in RAMClustR.  
2. suggesting an 'xcmsLite' package that contains these, and maybe a few other, data extraction functions.  
3. staying off CRAN.  

I don't know what the best approach is and am asking for guidance from the XCMS and R crowd on this.  
Corey

**Comment by tsufz** [comment]
Hi Corey and all,
I was also trying to compile it several times on my Windows system and I failed everytime. @sneumann, maybe it is the best to solve the issues wiht with mzR before we start to shuffle other packages? Is it possible to collect the issues with mzR and try to find solutions? Just an opinion.

Best wishes
Tobias

**Comment by cbroeckl** [comment]
@tsufz - it sounds like there are some serious challenges in making mzR CRAN-happy.  I can't explain what they are, but I am fairly certain it isn't an easy fix.

**Comment by jorainer** [comment]
What exactly is it that `R CMD check --as-cran` is complaining about @cbroeckl ? Generally, I would also opt against copying functions between packages and I agree with @tsufz that we need to fix the problems in `mzR` - it's mostly compiler-dependent things if I recall.

On the long run we're working on sort of *replacement* packages for `MSnbase`: https://RforMassSpectrometry.org . There are the `Spectra` and `Chromatograms` packages that will provide basic MS data infrastructure and these no longer depend on `mzR` but have it listed in *Suggests*. At some point `xcms` will also only depend on these packages and the problems *should* be gone - but that's future music of course.

**Comment by jorainer** [comment]
Another possibility could be to move `xcms` to *Suggests* and have the code lines 
```r
if (!requireNamespace("xcms", quietly = TRUE))
    stop("The use of this function requires package 'xcms'. Please ",
             "install with 'Biobase::install(\"xcms\")'")

```
in the functions using `xcms` code and call the `xcms` function like `xcms::groupval` in the function body. CRAN *should* accept this.

**Comment by sneumann** [comment]
Just as background: earlier in 2019 mzR failled on `clang-8` compiler, and while I had fixed the issue, I hadn't pushed the fixes and Brian Ripley and the CRAN team pulled all packages depending (transitively) on mzR.

**Comment by cbroeckl** [comment]
@jorainer - I will try the 'suggests' option for now and try to update as CRAN expresses its (their?) opinion.  Thanks for the feedback.

**Comment by cbroeckl** [comment]
FYI, for posterity sake: 
1.  I removed all references to xcms in @importFrom
2.  added the contingency if the input is an xcms object:     
      if (!requireNamespace("xcms", quietly = TRUE)) {
         stop("The use of this function requires package 'xcms'. Please ",
           "install with 'Biobase::install(\"xcms\")'")
    }
3.  kept function calls to xcms in the function, explicitly referring to xcms:  xcms::groupval()
4.  listed xcms in the "Suggests:" section of the DESCRIPTION

At this point I am passing CRAN check with a note, which seems to reflect the fact that RAMClustR has been banished previously.   devtools::check_rub still fails due to a failure to install xcms, unless R_CHECK_FORCE_SUGGESTS_ = FALSE, which then passes with the same note.  

I will try to update when I receive approval (or not) of the package suitability for CRAN, but this seems to be a feasible by-pass for now.

**Comment by cbroeckl** [comment]
Had a question arrive from the CRAN team - asking whether i REALLY didn't need to have xcms as a required package.  I told them that I have two forms of input - either csv or xcms - hopefully this helps.  Waiting for (dis)approval.

**Comment by jorainer** [comment]
Honestly, I don't think that an R package always has to require all packages that it uses code. If you have a function (that is not represent the main functionality of your package) that is not very frequently used it's IMHO OK to have the respective package in *Suggests* and load it via namespace - this will also have a quite big impact on package loading time. You can even cite Hadley on that [here](http://r-pkgs.had.co.nz/description.html) 😉

**Comment by cbroeckl** [comment]
I also pointed out that anyone trying to use an xcms object as input is likely to have successfully installed and run xcms.  Still waiting on a final verdict.

**Comment by cbroeckl** [comment]
Just cleared the CRAN submission.  Looks like we have a solution.  Thanks for the guidance.

**Comment by jorainer** [comment]
Good to hear! So I'm closing the issue now - feel free to reopen if needed.
