### ISSUE TITLE
Usage of MSnbase objects in xcms3

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#41]
This issue discusses inclusion/usage of objects and functionality from the https://github.com/lgatto/MSnbase package in _xcms3_. Ideally we should re-use as much as possible to reduce the complexity (i.e. number of methods etc). Methods, functionality and concepts shared by both packages might even go into a third package providing just low level functionality.

**Comment by jotsetung** [comment]
`OnDiskMSnExp`: this object might replace the `xcmsRaw` object. It combines all raw data from a whole MS experiment (reading the data on-demand from the disk). The data itself is organized in spectra, one spectrum for each scan/retention time. Extraction of spectra data is thus straight forward. Extraction of chromatogram data might be more complicated (time consuming).

Some notes:
+ Use a `as.matrix` or `as.data.frame` method on the `Spectrum1` classes to get the M/Z - intensity value pairs from each scan in one call, `cbind` that data and pass it to the low level `do_` low level methods.
+ `getEIC` or similar methods: is there something available for `MSnExp`/`OnDiskMSnExp`?

**Comment by hpbenton** [comment]
just want to chime in on this…

Over the years xcms has had many functions removed from it sometimes even becoming whole packages themselves, mzR is one example. I would feel that unless OnDiskMSnExp from msnBase has huge benefits over xcmsRaw in terms of reading data faster, compressing on storage etc that we stick with xcmsRaw. Many developer use this structure in their packages both public and private. I think we want to avoid xcms becoming a wrapper of mzR and msnBase.

Also happy to lend a hand in xcms3 re-write if I can be of any help, just let me know.

**Comment by jotsetung** [comment]
Dear Paul I really appreciate discussions on this! There are no plans to remove `xcmsRaw` immediately.

For me the obvious advantage of `OnDiskMSnExp` would be in the following use-case:
+ Features are identified (we have an `xcmsSet`) and we want to get the EIC for these across multiple samples. Currently we would call e.g. `getEIC`, which will then however read the whole raw data from each file. With the `OnDiskMSnExp` on the other side, only the required data will be extracted from the raw files. So there will be a huge performance gain here. Also, the `OnDiskMSnExp` class keeps track of any data manipulations that have been performed (also such as baseline correction etc).

**Comment by jotsetung** [comment]
Using the `OnDiskMSnExp` object in `xcms` as a container for the raw data and the `XCMSnExp` (defined in`xcms` and extending the `OnDiskMSnExp`) has proven to be useful. Biggest advantages are the direct link to the raw data, all already implemented and reusable subsetting and filter methods.
