### ISSUE TITLE
Strange behavior with findChromPeaks for a single Chromatogram object

### ISSUE THREAD

**Issue by wkumler** [sneumann/xcms#410]
Hi all,
I've been using xcms for a while now and really loving it, but have only recently started to look into the methods behind the magic. 

One thing I'm noticing is that xcms struggles to identify peaks if there's only a single local maximum present in the entire spectrum. For example:

```r
library(xcms)

scans <- 201:400
# Generate a nice Gaussian distribution for our peak
peak_template <- as.numeric(table(cut(rnorm(10000), breaks = 20)))
# Buffer the peak on both sides with zeros (could be any small number, though)
single_peak_ints <- c(rep(0, 90), peak_template, rep(0, 90))

chrom <- Chromatogram(rtime = scans, intensity = single_peak_ints, mz = 250)

findChromPeaks(chrom, param = CentWaveParam())
```

returns the following output:

> Object of class: XChromatogram
> length of object: 200
> from file: 
> mz range: [250, 250]
> rt range: [201, 400]
> MS level: 1
> Identified chromatographic peaks (0):
>  rt	rtmin	rtmax	into	maxo	sn (1 more column(s))
> Warning message:
> In peaksWithCentWave(int = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  :
>   No peaks found!

implying that there are no peaks in the model spectrum.

Some additional digging turned up the reason for this. `findChromPeaks` calls `peaksWithCentWave` calls `.getRtROI`, which in turn uses MALDIquant's `.localMaxima`  to identify local maxima. These local maxima are then used to determine the scan numbers of the regions of interest, which are passed to the prefilter check.

However, if there's only a single local maxima identified, then the prefilter check changes its behavior and iterates over each data point individually, rather than the peak as a whole:

```r
# Use the single peak spectrum from above
int <- single_peak_ints
# Manually add in parameters from CentWaveParam()
peakwidth <- c(20, 50)
prefilter <- c(3, 100)
noise <- 0
# Manually add parameters produced by call to .getRtROI()
rt_step <- 1 # Assume each scan takes exactly one second
up_bound <- ceiling(peakwidth[2]/rt_step)

# Find local maxima
pk_idx <- which(MALDIquant:::.localMaxima(int, floor(peakwidth[1]/rt_step)))
scmin <- sapply(pk_idx - up_bound, max, y = 1)
scmax <- sapply(pk_idx + up_bound, min, y = length(int))
roi_idxs <- mapply(scmin, scmax, FUN = seq)
ok <- vapply(roi_idxs, FUN = function(x, k, I) {
  sum(int[x] >= I) >= k
}, FUN.VALUE = logical(1), k = prefilter[1], I = prefilter[2], 
USE.NAMES = FALSE)
print(ok)
```

returns the following output:

> [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
> [18] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
> [35] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
> [52] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
> [69] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
> [86] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

with one `FALSE` for each row in the roi_idxs matrix, rather than one `TRUE` for the column as a whole. This behavior is because `mapply` simplifies the result into a single-column matrix, and then `vapply` applies the prefilter check to each individual data point, rather than the scan as a whole. I checked this by replacing the call to `mapply` with one to `lapply` to preserve the list structure that `vapply` is expecting.:

```r
int <- single_peak_ints
pk_idx <- which(MALDIquant:::.localMaxima(int, floor(peakwidth[1]/rt_step)))
scmin <- sapply(pk_idx - up_bound, max, y = 1)
scmax <- sapply(pk_idx + up_bound, min, y = length(int))
roi_idxs <- lapply(scmin, scmax, FUN = seq)
ok <- vapply(roi_idxs, FUN = function(x, k, I) {
  sum(int[x] >= I) >= k
}, FUN.VALUE = logical(1), k = prefilter[1], I = prefilter[2], 
USE.NAMES = FALSE)
print(ok)
```

which returns the expected

> [1] TRUE

In fact, we get weird behavior from `.getRtROI` every time `mapply` is able to simplify the output to a matrix. Below is an illustration of several good peaks going unfound for this reason:

```r
# Create a sample EIC with several good peaks
many_peak_ints <- c(rep(0,100), peak_template/5, peak_template, peak_template*2, rep(0, 100))
scans <- seq_along(many_peak_ints)+200
chrom <- Chromatogram(rtime = scans, intensity = many_peak_ints, mz = 250)
# Check that findChromPeaks fails to find all of them
findChromPeaks(chrom, param = CentWaveParam())
```

> Identified chromatographic peaks (0):
> rt	rtmin	rtmax	into	maxo	sn (1 more column(s))
> Warning message:
> In peaksWithCentWave(int = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  :
>   No peaks found!

```r
# Check that these peaks are missed because mapply was able to simplify to a matrix
int <- many_peak_ints
pk_idx <- which(MALDIquant:::.localMaxima(int, floor(peakwidth[1]/rt_step)))
scmin <- sapply(pk_idx - up_bound, max, y = 1)
scmax <- sapply(pk_idx + up_bound, min, y = length(int))
plot(int)
roi_idxs <- mapply(scmin, scmax, FUN = seq)
print(class(roi_idxs))
```

> [1] "matrix"

Now, `mapply` is able to simplify to a matrix whenever each of its outputs has the same dimensions. This will happen

1. Whenever there's a single peak found in an ROI

2. Whenever there are no ROIs found close to the edges of the EIC, where "close" is the user-provided max peakwidth.

This second one happens because the ROI is extended by `ceiling(peakwidth[2]/rt_step)` in each direction to find the maximum plausible edges of the scan (scmin/scmax), but if the ROI is within that distance from the edge, it's truncated and `mapply` is no longer able to simplify the resulting list into a matrix.

**I understand that the ROI finder used to handle MSnExp objects is different - for one, it's written in C/C++ so I'm unable to check out what exactly it's doing. Is it implementing an identical algorithm with the same odd behavior, and if so should I be wary of spectra that are unusually smooth and without multiple maxima OR have no maxima close to the edges?**

sessionInfo():
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xcms_3.6.1           MSnbase_2.10.1       ProtGenerics_1.16.0  S4Vectors_0.22.0     mzR_2.18.0          
[6] Rcpp_1.0.1           BiocParallel_1.17.18 Biobase_2.44.0       BiocGenerics_0.30.0 

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5       purrr_0.3.2            splines_3.6.0          lattice_0.20-38       
 [5] colorspace_1.4-1       yaml_2.2.0             vsn_3.52.0             XML_3.98-1.20         
 [9] survival_2.44-1.1      rlang_0.3.4            pillar_1.4.1           glue_1.3.1            
[13] affy_1.62.0            RColorBrewer_1.1-2     affyio_1.54.0          foreach_1.4.4         
[17] plyr_1.8.4             mzID_1.22.0            robustbase_0.93-5      zlibbioc_1.30.0       
[21] munsell_0.5.0          pcaMethods_1.76.0      gtable_0.3.0           codetools_0.2-16      
[25] IRanges_2.18.1         doParallel_1.0.14      MassSpecWavelet_1.50.0 preprocessCore_1.46.0 
[29] DEoptimR_1.0-8         scales_1.0.0           BiocManager_1.30.4     limma_3.40.2          
[33] RANN_2.6.1             impute_1.58.0          ggplot2_3.1.1          digest_0.6.19         
[37] dplyr_0.8.1            ncdf4_1.16.1           grid_3.6.0             tools_3.6.0           
[41] magrittr_1.5           lazyeval_0.2.2         tibble_2.1.3           crayon_1.3.4          
[45] pkgconfig_2.0.2        MASS_7.3-51.4          Matrix_1.2-17          assertthat_0.2.1      
[49] rstudioapi_0.10        iterators_1.0.10       R6_2.4.0               MALDIquant_1.19.3     
[53] multtest_2.40.0        compiler_3.6.0  
```

**Comment by wkumler** [comment]
Small update:

All that should be required to resolve this if it is indeed a bug is adding the SIMPLIFY = F argument to the call to `mapply`. I've been testing this on my own and it seems to preserve all the proper behavior of `.getRtROI` while preserving the peaks that would have been removed.

**Comment by jorainer** [comment]
Hey @wkumler ! That is a very very nice and clear description of the error and, even better, proposal of a solution to it! This sounds totally reasonable to me.

In fact, the noise estimation for peak detection on `MSnExp` and `Chromatograms` is quite different because for `Chromatograms` we usually have only a limited retention time range while in the other case we're usually having the full retention time range of the run.

The ideal solution to this: fork `xcms` (master branch), make the changes you propose and create a PR. That way we would have your contribution *tracked*.

**Comment by wkumler** [comment]
@jorainer Glad it's a useful addition! I've established the pull request with the discussed modification, as shown above.

I didn't think that the ROI detection process was influenced by the noise estimation - as far as I can tell, the ROIs are picked well before noise estimation happens. I'm more curious about the ROI detection for the `MSnExp` object because it's written in C and I can't check to see whether this bug pops up there as well. If the ROI detection essentially identical for `Chromatogram`s and `MSnExp` objects, this bug will need to be squashed there separately and by someone more familiar with C/C++ than I am.

**Comment by sneumann** [comment]
I wonder whether we'd want to avoid two separate implementations of getROI in the long run ?

**Comment by wkumler** [comment]
@sneumann That's something I was wondering about myself. You've got the speedy C/C++ code written to handle the `MSnExp` object, so it may make more sense to build that into the `Chromatogram` processing rather than fiddling with the `getRtROI` function separately.

**Comment by jorainer** [comment]
I think there is no way around the two ROI detection functions as the data is different: for chromatographic data we actually have just a single vector of consecutive intensities while the data in `OnDiskMSnExp`/`MSnExp` is spectral data and the ROIs have to be identified in the 2 dimensional plane m/z against rt. So it is like looking for a potential signal in a one dimensional vs two dimensional space.
