### ISSUE TITLE
Saved mzXML file doesn't include chromPeaks data

### ISSUE THREAD

**Issue by joannawolthuis** [sneumann/xcms#413]
Hi team! 

I'm currently building an xcms-focused pipeline and have been making some great progress. 
As I am running on a cluster, I wrote the scripts to seperately process each source file until the point where I want to do peak grouping - but I just noticed that if I progress through the following steps (direct infusion mass spec data):

```
summed_file <- readMSData(files = mzdata_file,
                       mode = "onDisk")
x = c(7,
      1,
      500,
      16,
      2077) # replace with other settings if needed : - ) 

msw <- MSWParam(scales = seq(1,x[1],1), 
                nearbyPeak = if(x[2]==1) T else F, 
                winSize.noise = x[3],
                SNR.method = "data.mean", 
                snthresh = x[4],
                ampTh = x[5]/1e4)

summed_peaks <- findChromPeaks(summed_file, param = msw)

calib = CalibrantMassParam(mz = mzlist, mzppm = 2)
summed_peaks_msw = calibrate(summed_peaks, param=calib)

fn = file.path(filedir, "results", "peaks", basename(mzdata_file))

xcms::writeMSData(summed_peaks_msw, file = fn)

```

The resulting file does not contain the info from the wavelet peak calling that I need for the grouping step. Is there any way to include that in the writeMSData call?
If I missed something obvious in the documentation about this, my apologies, but I've been looking for a while and I was wondering if it wasn't a feature yet to save this info seperately per file =O

Kind regards and thank you,

Joanna

--- edit: once fixed, I foresee the below to be possible issues: ---

```
> summed_files <- readMSData(files = fns[1:3],
                           mode = "onDisk")
> first_file <- filterFile(summed_files, file = 1)
> hasChromPeaks(first_file)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘hasChromPeaks’ for signature ‘"OnDiskMSnExp"’
> chromPeaks(first_file)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘chromPeaks’ for signature ‘"OnDiskMSnExp"’
> mzc_prm <- MzClustParam(sampleGroups = 1:3,
                        ppm = 2,
                        minSamples = 2)
> summed_grouped <- groupChromPeaks(summed_files, param = mzc_prm)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘groupChromPeaks’ for signature ‘"OnDiskMSnExp", "MzClustParam"’

```

**Comment by sneumann** [comment]
Hi, the approach to process *.mzML separately on a cluster and collect the results for merging 
is also followed by the W4M team, see conversation at https://github.com/sneumann/xcms/issues/247
I would suggest to write the R object to disk, not an XML representation. Yours, Steffen
