### ISSUE TITLE
which version to install for SWATH

### ISSUE THREAD

**Issue by ricoderks** [sneumann/xcms#420]
Hi all,

I would like to play with some swath data in xcms. Which version of xcms should I install? 

Cheers, Rico

**Comment by jorainer** [comment]
You should install the latest version of R (3.6.1) and Bioconductor developmental version:

```r
install.packages("BiocManager")
library(BiocManager)
BiocManager::install(version = "3.10")
BiocManager::install("xcms")
```

**Comment by jorainer** [comment]
It's now the *official* `xcms` version that is installed with Bioconductor version 3.10 (see above for how to install).

Closing issue - feel free to re-open if needed.
