### ISSUE TITLE
Different amount of features in XCMSset and XCMSnExp?

### ISSUE THREAD

**Issue by pvervliet** [sneumann/xcms#425]
I updated the R-code I had for feature picking with XCMS to go from XCMSset object to a XCMSnExp object in order to be able to work with some newer functionalities. 
I noticed that the number of peaks at the end of my workflow is lower with the XCMSnExp than with the old XCMSset object (same 15 data files in a folder, allocated 'datadir').

The code I had for the XCMSset is: 
```
xcmsPeaks <- xcmsSet(files=datadir, 
                     method="centWaveWithPredictedIsotopeROIs", 
                     ppm=15, 
                     peakwidth=c(5,40), 
                     mzdiff=0.01, 
                     prefilter=c(3,5000),
                     integrate = 1, 
                     snthresh=10, 
                     noise =500)

xcmsGroups = group(xcmsPeaks, method="density", bw=10, mzwid = 0.015, minfrac=0.20, max=100, minsamp = 2)

xcmsRetcor <- retcor(xcmsGroups, 
                     method="loess",
                     plottype = "deviation", col = kleuren, ty = 1)

xcmsGroups = group(xcmsRetcor, 
                   method="density", 
                   bw=5, 
                   mzwid = 0.015, 
                   minfrac=0.20, 
                   max=100, 
                   minsamp = 2)

xcmsFilled <- fillPeaks(xcmsGroups)

features_XCMSset = groupval(xcmsFilled, value = "into", method = "medret")
```
The resulting features_XCMSset has around 3000 lines.

The code for the XCMSnExp is as following:
```
raw_data <- readMSData(files, mode = "onDisk")

cwp <- CentWavePredIsoParam(ppm =15,
                            peakwidth = c(5, 40),
                            snthresh = 10, 
                            noise = 500, 
                            mzdiff = 0.01,
                            prefilter = c(3,5000),
                            integrate = 1)

res <- findChromPeaks(raw_data, param = cwp)

grpdens <- PeakDensityParam(sampleGroups = rep(1, length(fileNames(res))), bw = 10,
                            minFraction = 0.20, minSamples = 2, maxFeatures = 100,
                            binSize = 0.015)
res <- groupChromPeaks(res, grpdens)

fgp <- PeakGroupsParam(minFraction = 0.5)
pkGrps <- adjustRtimePeakGroups(res, param = fgp)
res <- adjustRtime(res, param = fgp)

res <- groupChromPeaks(res, grpdens)

res <- fillChromPeaks(res)

features_XCMSnExp <- featureValues(res, method = "medret", value = "into")
```
The resulting features_XCMSnExp has only around 2000 features, although I tried to keep every parameter equal to the original code I had.
I don't know if there is an underlying reason for this difference?

Fyi, the data are 15 .mzML files were acquired in DDA and converted from .d (Agilent) to .mzML using ProteoWizard MSConvert. 

My sessionInfo:
```
sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] xcms_3.4.4          MSnbase_2.8.3       ProtGenerics_1.14.0 S4Vectors_0.20.1    mzR_2.16.2         
[6] Rcpp_1.0.2          BiocParallel_1.16.6 Biobase_2.42.0      BiocGenerics_0.28.0

loaded via a namespace (and not attached):
 [1] tidyselect_0.2.5       purrr_0.3.2            splines_3.5.2          lattice_0.20-38       
 [5] colorspace_1.4-1       vsn_3.50.0             XML_3.98-1.20          survival_2.44-1.1     
 [9] rlang_0.4.0            pillar_1.4.2           glue_1.3.1             affy_1.60.0           
[13] RColorBrewer_1.1-2     affyio_1.52.0          foreach_1.4.7          plyr_1.8.4            
[17] mzID_1.20.1            robustbase_0.93-5      zlibbioc_1.28.0        munsell_0.5.0         
[21] pcaMethods_1.74.0      gtable_0.3.0           codetools_0.2-16       IRanges_2.16.0        
[25] doParallel_1.0.15      MassSpecWavelet_1.48.1 preprocessCore_1.44.0  DEoptimR_1.0-8        
[29] scales_1.0.0           BiocManager_1.30.4     limma_3.38.3           RANN_2.6.1            
[33] impute_1.56.0          ggplot2_3.2.1          digest_0.6.21          dplyr_0.8.3           
[37] ncdf4_1.16.1           grid_3.5.2             tools_3.5.2            magrittr_1.5          
[41] lazyeval_0.2.2         tibble_2.1.3           crayon_1.3.4           pkgconfig_2.0.3       
[45] MASS_7.3-51.4          Matrix_1.2-17          assertthat_0.2.1       rstudioapi_0.10       
[49] iterators_1.0.12       R6_2.4.0               MALDIquant_1.19.3      multtest_2.38.0       
[53] compiler_3.5.2  
```

**Comment by jorainer** [comment]
Thanks for the detailed description @pvervliet .

Now, first things: would it be possible to update to a more recent R version? The current version is 3.6.1 and with that you would get Bioconductor 3.10 (and the most recent `xcms` version). Could be that there was something fixed between the version you use and the newer one.

Secondly, could you please check the number of identified chromatographic peaks in your `xcmsSet` and `XCMSnExp` objects? Would be good to know if the difference starts already there or comes at some of the later stages.

**Comment by pvervliet** [comment]
Hi,

I've updated to R to 3.6.1 and xcms is now up to 3.8.0
```
other attached packages:
[1] xcms_3.8.0          MSnbase_2.12.0      ProtGenerics_1.18.0 S4Vectors_0.24.0    mzR_2.20.0         
[6] Rcpp_1.0.2          BiocParallel_1.20.0 Biobase_2.46.0      BiocGenerics_0.32.0
```
I've checked the number of chromatographic peaks in the xcmsPeaks object (34424) and the XCMSnExp @msFeatureData[["chromPeaks"]] (22597) so a clearly lower number of with the XCMSnExp.
I then checked how the number of chromatographic peaks was between the two objects: 

![image](https://user-images.githubusercontent.com/38757650/68209305-6047a080-ffd3-11e9-9e53-6f2f0ac7d891.png)

I don't think the lower number of features in the XCMSnExp is related to a specific sample (datafiles)/subset of datafiles.

**Comment by jorainer** [comment]
OK, so there is some difference right from the start. This is somewhat strange, because both methods use the same code basis.

**Comment by jorainer** [comment]
Now, after initial inspection there is something strange at a much lower level:
```r
> library(xcms)
> fl <- "HLM-0h-REP1.mzML"
> xraw <- xcmsRaw(fl)
Create profile matrix with method 'bin' and step 1 ... OK
> xdta <- readMSData(fl, mode = "onDisk", msLevel = 1L)
> length(xraw@scantime)
[1] 567
> length(rtime(xdta))
[1] 644
```
So, for whatever reason we have a different number of spectra depending on how we import the data.

**Comment by jorainer** [comment]
What makes is even more puzzling is that the number of m/z values is the same:
```r
> length(xraw@env$mz)
[1] 188665
> length(unlist(mz(xdta)))
[1] 188665
```

**Comment by jorainer** [comment]
OK, apparently these files contain quite some spectra without any peaks (thus the difference in the number of spectra - `xcmsRaw` does silently remove empty spectra - whether that's good or not I can't say).

To fix the issue just call
```r
raw_data <- filterEmptySpectra(raw_data)
```

before performing the peak detection. Might also worthwhile to check where and why you have empty spectra. To get this info you can use
```r
which(peaksCount(raw_data) == 0)
```

**Comment by jorainer** [comment]
Closing the issue now. Feel free to re-open if needed.
