### ISSUE TITLE
Undocumented S4 method: generic '[' and siglist 'xcmsSet,ANY,ANY,ANY'

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#43]
Happened in 1.49.3 http://bioconductor.org/checkResults/devel/bioc-LATEST/xcms/zin1-checksrc.html

````
* checking for missing documentation entries ... WARNING
Undocumented S4 methods:
  generic '[' and siglist 'xcmsSet,ANY,ANY,ANY'
````

**Comment by jotsetung** [comment]
Done in https://github.com/sneumann/xcms/commit/b67dc45a54203a4acf529da5f32aaa35e143d128
