### ISSUE TITLE
Split Unit tests between daily and weekly

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#431]
@hpages has links how to split checks long/short to stay below time limits

**Comment by jorainer** [comment]
That's good news! Will you post the info here once you have it?

**Comment by hpages** [comment]
Hi guys,

See this page for a link to the "long tests" builds: https://bioconductor.org/checkResults/

These builds have been up and running for a couple of years now. I announced them on bioc-devel in Nov 2017: https://stat.ethz.ch/pipermail/bioc-devel/2017-November/012326.html Also mentioned them recently: https://stat.ethz.ch/pipermail/bioc-devel/2019-September/015534.html

Following our conversation from yesterday's Bioconductor Developers' Forum I'm preparing a short document that explains how to subscribe to these builds. I'll put the document on our website later today and announce on bioc-devel.

Note that we only run the "long tests" builds on Linux at the moment but it would be easy to run them on all platforms.

H.

**Comment by hpages** [comment]
I just put the new "Long Tests" document on the website: https://bioconductor.org/developers/how-to/LongTests/

It's not linked from any other page yet.

Will announce it on the bioc-devel mailing list in the next few days, after I add tokay2 (Windows) to the Long Tests builds (I added celaya2 (Mac) yesterday).

Feedback/suggestions welcome.

**Comment by jorainer** [comment]
This was implemented. Thus closing issue.
