### ISSUE TITLE
chromatogram equivalent for xcmsSet

### ISSUE THREAD

**Issue by pvervliet** [sneumann/xcms#440]
When working with a XCMSnExp type object, I can plot check the integration of a feature using plot(chromatogram(object, ...)). Example:

![image](https://user-images.githubusercontent.com/38757650/71006118-22b35880-20e5-11ea-9351-75c8a18e7a80.png)

I wonder if there is an equivalent for a xcmsSet object?
I would like to plot the EIC of a feature, with its integration as shown in the XCMSnExp example. Using tutorials online/... I can do a getEIC from the xcmsSet object (with a mzrange and rtrange), but the integration is not present.

Thank you in advance for your help.

**Comment by sneumann** [comment]
I am afraid I am not aware of anything equivalent in `xcmsSet`. Yet another reason to switch to the xcms3 interfaces. Yours, Steffen

**Comment by jorainer** [comment]
Closing the issue now. Feel free to re-open if needed.
