### ISSUE TITLE
SWATH: reconstructChromPeakSpectra: Error in x$.self$finalize() : attempt to apply non-function

### ISSUE THREAD

**Issue by korseby** [sneumann/xcms#441]
Hi @jorainer , @michaelwitting , @sneumann 

Just before christmas I decided why not play around with feeding some SWATH data into xcms...

The data is available as MTBLS851. The dataset is still private. Access token is available upon request.

Related issues: #375 , #427  

Here's my code:

```R
# Import raw data as MSnbase object
raw_data <- readMSData(files=mzml_files, pdata=new("NAnnotatedDataFrame", mzml_pheno), mode="onDisk", centroided=TRUE)

# Get base peak chromatograms
chromas <- chromatogram(raw_data, aggregationFun="max")

# Peak detection in MS1 data
ms1_params <- CentWaveParam(ppm=35, mzCenterFun="mean", prefilter=c(0, 0), peakwidth=c(10, 50), snthresh=2, # mzdiff=-0.001, noise=0, integrate=1, #peakwidth=c(10, 25), snthresh=10, prefilter=c(3, 100),
                            firstBaselineCheck=TRUE, verboseColumns=FALSE, fitgauss=FALSE, roiList=list(), roiScales=numeric())
ms1_data <- findChromPeaks(raw_data, param=ms1_params)

# RT correction
ms1_data <- adjustRtime(ms1_data, param=ObiwarpParam(binSize=1.2))

# Group peaks
ms1_data <- groupChromPeaks(ms1_data, param=PeakDensityParam(sampleGroups=ms1_data$sample_group, minFraction=0.6, bw=20))

# Peak picking in all isolation windows (buckets) of SWATH data
ms2_params <- CentWaveParam(ppm=45, peakwidth=c(10, 60), snthresh=0, prefilter=c(0, 0), mzCenterFun="mean", #mzdiff=-0.001, noise=0, integrate=1,
                            firstBaselineCheck=TRUE, verboseColumns=FALSE, fitgauss=FALSE, roiList=list(), roiScales=numeric())
ms2_data <- findChromPeaksIsolationWindow(ms1_data, param=ms2_params)

# Filter MS2 spectra
swath_data <- filterRt(ms2_data, rt=c(20,1020))

# Define an MS2 spectra for each MS1 peak
swath_spectra <- reconstructChromPeakSpectra(swath_data, minCor=0.5)
```

`reconstructChromPeakSpectra` produces the following error:
```
Reconstructing MS2 spectra for 4857 chrom peaks ...Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in approx(rtime(x), intensity(x), rtime(y)) : 
  need at least two non-NA values to interpolate
```

my sessionInfo():
```R
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] C/C/C/C/C/en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] doParallel_1.0.15   iterators_1.0.12    foreach_1.4.7      
 [4] lme4_1.1-21         Matrix_1.2-18       gplots_3.0.1.1     
 [7] multcomp_1.4-11     TH.data_1.0-10      MASS_7.3-51.4      
[10] survival_3.1-8      mvtnorm_1.0-11      vegan_2.5-6        
[13] lattice_0.20-38     permute_0.9-5       CAMERA_1.42.0      
[16] xcms_3.9.1          BiocParallel_1.20.0 MSnbase_2.12.0     
[19] ProtGenerics_1.18.0 S4Vectors_0.24.1    mzR_2.21.0         
[22] Rcpp_1.0.3          multtest_2.42.0     Biobase_2.46.0     
[25] BiocGenerics_0.32.0 RColorBrewer_1.1-2 
```

Another related question: I'm doing some fancy statistics on the MS1-matrix produced with `featureValues(ms1_data, method="medret", value="into")` and in the end, some rownames of features will pop up. What is the best way to associate these features (which have some mz/rt in the MS1 matrix) with the corresponding MS2 spectra? Well, I wanted to use reconstructChromPeakSpectra for that... 

In the vignette, there is a method mentioned how to do this for a single feature. How can I do this for hundreds of features at once?

What kind of MS2 spectra are returned? Raw spectra? Merged spectra?

What about RT corrections made during the peak picking in the MS1 run?

In the past, for DDA I extracted the raw spectra using MSnBase and merged them afterwards... But that was not the optimal solution.

Merry christmas and a happy new year.

*Kristian

**Comment by jorainer** [comment]
Hi @korseby, nice that you give `xcms` a shot here. Now regarding the errors and questions:

> Error in approx(rtime(x), intensity(x), rtime(y)) : 
  need at least two non-NA values to interpolate

we're using the `approx` function to align the chromatograms of the MS1 (chrom) peak and each MS2 (chrom) peak. From the error I guess that for some of the *peaks* you have to few non-NA data. To really understand what happened and how to fix I would need to look into the data - and now it's a pretty bad time of the year to do that :)

> Error in x$.self$finalize() : attempt to apply non-function

You can ignore these - these errors pop up randomly and have to do (IMO) with the garbage collection of R. Unfortunately I did not yet find a way to avoid these.

> In the vignette, there is a method mentioned how to do this for a single feature. How can I do this for hundreds of features at once?

For SWATH data it is the `reconstructChromPeakSpectra` that does all the *magic* in one go. In your case that function however unfortunately fails... But this also returns you the reconstructed MS2 spectrum for each MS1 **chrom peak**, not *feature*.

> What kind of MS2 spectra are returned? Raw spectra? Merged spectra?

For each MS1 chromatographic peak a *reconstructed* MS2 spectrum is returned, i.e. m/z and *maxo* values of all MS2 chromatographic which a high enough peak shape correlation with the MS1 chromatographic peak are reported as mass peaks in the MS2 spectrum.

> What about RT corrections made during the peak picking in the MS1 run?

Retention times of all MS2 spectra are also adjusted according to the MS1 alignment.

> In the past, for DDA I extracted the raw spectra using MSnBase and merged them afterwards... But that was not the optimal solution.

Would be nice if you could suggest an improved way to do that. We're currently working on a `Spectra` package that does a *slightly* better merging of MS2 spectra - I hope - but in the end it's the same approach that we used in `MSnbase`.

Merry christmas!

jo

**Comment by korseby** [comment]
Hi @jorainer,

Hope all is fine with you and you got a great start into the new year.

I'll send you an email with access to the dataset.

What we need is to associate each picked feature with an MS2 spectrum:
- peak picking with xcms, result is the MS1 feature matrix obtained via `featureValues`. This is the matrix we do all the fancy statistics on.
- associate an MS2 spectrum with each of the features in the MS1 feature matrix. The MS2 spectrum is likely merged from several MS2 spectra. This is, of course, the tricky part.

I think, the merging of MS2 spectra was originally done by Christoph Ruttkies as part of MetFRag quite some time ago, see here: https://github.com/korseby/container-msnbase/blob/develop/scripts/functionsMergeFilterMS2.r
I implemented that in a converter, see here: https://github.com/korseby/container-msnbase/blob/develop/scripts/mzml-to-msp.r
But that needs improvements and it uses still the old xcms... So it would be awesome to have this in XCMS3 built-in somehow.

**Comment by jorainer** [comment]
One question regarding the merging of the MS2 spectra: we have the `combineSpectra` method that allows to combine/merge sets of spectra to create a representative or *consensus* spectrum. That's mostly used for DDA data because there we have more than one MS2 spectrum for one MS1 chromatographic peak. Maybe this function could be improved based on what you and Christoph did - or eventually they are already doing the same? Could you briefly explain how you merge the spectra?

**Comment by korseby** [comment]
I will have a look at `combineSpectra` once we get `reconstructChromPeakSpectra` to work with our data. Maybe it does only need a few modifications to work with our SWATH spectra. I will surely send a pull request. There are different ways to merge spectra. So it may be better to contribute in the planned separate package... But let's take one step after the other. :)

**Comment by jorainer** [comment]
Update on your error above (`need at least two non-NA values to interpolate`). the extracted ion chromatogram of an MS2 chrom peak has in fact to few data points to do a correlation. Which is funny is that centWave found a chrom peak at that region in the first place, but I guess that is also related to your peak detection settings to pick up as many peaks as possible. I'd suggest (also to reduce run time) to use `prefilter = c(3, 50)` or similar.

In any rate, I've added a fix that catches this error.

**Comment by korseby** [comment]
Thanks @jorainer ,

I am testing it out right now with different parameters.

Will checkout your branch (jomaster) to test the changes later today.

**Comment by korseby** [comment]
Besides that `reconstructChromPeakSpectra` run for two days I now managed to run the function successfully.

When now looking at the `reconstructChromPeakSpectra` object, I find many empty Spectra2's which may have something to do with either the settings or the `minCor`-value.

I now want to find the according MS2 spectra for my MS1 "peak of interest".

So basically I'm doing this:

`ms1_matrix <- featureValues(ms1_data, method="medret", value="into")`

some fancy statistics follow on the matrix and some rownames like `FT0123` drop that indicate a feature of importance.

I now gather the information on that feature using `featureDefinitions(ms1_data)`, which gives me an approximative `mz` and `rt` value and try to find the MS2 spectra for that particular "feature of interest".

```R
feature_of_interest <- ms1_def[123, "mzmed"]
peaks_of_interest <- chromPeaks(swath_data, msLevel=1, mz=feature_of_interest, ppm=5)
swath_spectrum_of_interest <- swath_spectra[which(mcols(swath_spectra)$peak_id %in% rownames(peaks_of_interest))]

nonempty_spectra <- NULL
for (i in 1:length(swath_spectrum_of_interest@listData)) {
	if (length(swath_spectrum_of_interest@listData[[i]]@precursorMz) > 0) nonempty_spectra <- c(nonempty_spectra, i)
}
```

However, all of the `swath_spectra` returned for my features of interest are empty.

Is it my parameters or must I lower `minCor`? Or is there may be another reason?

```R
ms1_params <- CentWaveParam(ppm=35, mzCenterFun="mean", prefilter=c(3, 50), peakwidth=c(10, 50), snthresh=2, 
                            firstBaselineCheck=TRUE, verboseColumns=FALSE, fitgauss=FALSE, roiList=list(), roiScales=numeric())

ms2_params <- CentWaveParam(ppm=45, peakwidth=c(10, 60), snthresh=0, prefilter=c(3, 50), mzCenterFun="mean", 
                            firstBaselineCheck=TRUE, verboseColumns=FALSE, fitgauss=FALSE, roiList=list(), roiScales=numeric())

swath_spectra <- reconstructChromPeakSpectra(swath_data, minCor=0.5)
```

**Comment by jorainer** [comment]
AFAIK the function always returns a spectrum, even if no MS2 chrom peaks correlate. That might be the case here. What I would do is 1) increase `snthresh` to some positive value bigger than `0` - I have the uneasy feeling that that might find peaks where in fact there are none (I just found some strange things but didn't have the time to go deeper into it. 2) I would expand the `expandRt` a bit. The default is `expandRt = 1`. This will include more signal left and right of the actually identified peak. Something like `3` or so might eventually be better. Also, maybe use a larger `diffRt`? The default is `diffRt = 2`.
Another thing you could try is to use `integrate = 2` in centWave - at least for our data that identifies better peak boundaries...

**Comment by korseby** [comment]
I did some more testing and now use the following settings for MS1 and MS2:

```R
ms2_params <- CentWaveParam(ppm=50, mzCenterFun="mean", prefilter=c(2, 35), peakwidth=c(10, 50),
              snthresh=2, integrate=2, firstBaselineCheck=TRUE, verboseColumns=FALSE, fitgauss=FALSE, roiList=list(), roiScales=numeric())
```

Doing peak picking and assigning spectra to each of the MS1 peaks, which takes a week on my computer (i7 from 2012, 4-cores):

```R
ms2_data <- findChromPeaksIsolationWindow(ms1_data, param=ms2_params)
swath_data <- filterRt(ms2_data, rt=c(20,1020))
swath_spectra <- reconstructChromPeakSpectra(swath_data, minCor=0.5)
```

The last file takes ages to complete and finally produces an error message:

```R
Error: BiocParallel errors
  element index: 33
  first error: task 33 failed - "BiocParallel errors
  element index: 1
  first error: task 1 failed - "Can not open file data/dry_Pla1_neg.mzML! Original error was: Error in pwizModule$open(filename): bad lexical cast: source type value could not be interpreted as target
```

I'm in neg-mode. But that shouldn't make a difference.

Maybe I should try without parallelization? (see issues https://github.com/sneumann/xcms/issues/419 and https://github.com/lgatto/MSnbase/issues/383).

**Comment by ricoderks** [comment]
Hi @jorainer,

I've got the same error and currently playing around with the settings to avoid getting this error. I also would like to install the version with your fix. I assume I have to install xcms with devtools::install_github(), but which branch should I install?

Cheers, Rico

> Update on your error above (`need at least two non-NA values to interpolate`). the extracted ion chromatogram of an MS2 chrom peak has in fact to few data points to do a correlation. Which is funny is that centWave found a chrom peak at that region in the first place, but I guess that is also related to your peak detection settings to pick up as many peaks as possible. I'd suggest (also to reduce run time) to use `prefilter = c(3, 50)` or similar.
> 
> In any rate, I've added a fix that catches this error.

**Comment by jorainer** [comment]
@korseby the error you get seems to be related to this one file. Seems that proteowizard has a problem opening/reading this file. Could you just check this one file a little closer, i.e. read it with `readMSData`, check how many MS1 or MS2 spectra are in it...

Regarding the quantification of MS-DIAL - I have no idea. We do the quantification (so far) only on the MS1 chrom peaks, the MS2 signal is *just* used to create/reconstruct the MS2 spectra.

@ricoderks all the fixes should be in the current master branch. Install that with `devtools::install_github("sneumann/xcms")`.

I hoped to find some more time to look into the swath data myself but I couldn't, sorry for that.

**Comment by korseby** [comment]
@jorainer I'm currently investigating the issue further. It took a while as we needed to re-generate the mzML from the vendor raw files, which we only could do at the institute... I'm having tremendous issues with parallelization. My computer just crashed out of a sudden. And it seems now that every time a different file is affected, which makes testing rather complicate... What is the preferred parallelization method for xcms? I'm using:

```R
library(BiocParallel)
library(doParallel)
registerDoParallel(6)
register(DoparParam(), default=TRUE)
```

**Comment by jorainer** [comment]
Parallel processing can easily cause you to run out of memory. What OS are you using and how many (physical) CPU and what memory (RAM) do you have available?

**Comment by korseby** [comment]
I'm on macOS (10.15, latest updates). I also updated to R 4.0.1, latest BioC + latest xcms-github and deleted the session and local RData to have a clean environment. 64 G of RAM should be sufficient I think and I never noticed that they are filled...

Yesterday evening I noticed that when using RStudio the error occurs. At some point `rsession` hangs at some random mzML file when doing

```R
raw_data_neg <- readMSData(files=mzml_files_neg, pdata=new("NAnnotatedDataFrame", mzml_pheno_neg), mode="onDisk", centroided=TRUE)
```

When I choose `inMemory` it is even worse. In case it successfully completes, it will hang later all of a sudden.

Over night I tested on Linux with the same code. No problems.

And now it comes. Back on macOS, I tested it with the barebone R in the terminal. So far, no problems.... (Please insert angry emoticon or facepalm here.) So, I guess it is somehow related to a messed-up RStudio. On macOS, it ships it's own `rsession`. Maybe it has something to do with it. I'm really tired now with testing, switching back to Linux... Maybe you noticed something like this before?

**Comment by korseby** [comment]
Okay. As this is clearly not related to XCMS and the testing on the pure R console works, no need to have this issue open anymore.

**Comment by jorainer** [comment]
What I realized is that macOS somehow does no longer use *forked* processes in parallel processing but fails back to *sock*-based parallel processing (same as in Windows) and that will create a new R process for each worker and has to copy the whole memory content over to that new process. So instead of shared memory as with fork-based parallel processing (on unix) you end up with multiple copies of your data - that way you run out of memory much faster.
