### ISSUE TITLE
Reducing "minimum peakwidth" parameter removes peaks during wavelet transform

### ISSUE THREAD

**Issue by wkumler** [sneumann/xcms#445]
XCMS seems to be highly sensitive to the minimum peak width when finding peaks without a lot of data outside of the peak itself. If the minimum peakwidth is set too low, the peaks themselves are dropped without warning.

It looks like this happens because the `scales` argument used by `.centWave_orig` function is determined by the minimum peakwidth, but the scales themselves are only applied to a chromatogram of a certain length.

From `xcms:::centwave_orig()`:

``` r
peakwidth <- c(20, 50) #or whatever the user set the CentWaveParam() to

# A few lines later...
scalerange <- round((peakwidth)/2)

# A few lines beyond that...
# Assuming that a min and max were provided, as seems to be the typical usage
scales <- seq(from = scalerange[1], to = scalerange[2], by = 2) 
```

Now, `scales` is passed directly to the wavelet function `MSW.cwt()`:

`wCoefs <- MSW.cwt(d, scales = scales, wavelet = "mexh")`

which uses it to determine the widths of the wavelets to test against the peak.

However, if there aren’t enough scans in the extracted chromatogram (`d`, which becomes `ms` within the `MSW.cwt()` function), then the wavelets aren’t run on the chromatogram and instead `NA` is returned.

``` r
# If there's a narrow buffer on each side (less than 10 scans)
actual_peakwidth <- 35
perfect_peak <- dnorm(seq(-3, 3, length.out = actual_peakwidth))
buffer <- numeric(10)
sample_chrom <- c(buffer, perfect_peak*100, buffer) + runif(length(buffer)*2+actual_peakwidth)
plot(sample_chrom, type="b", ylab="Peak intensity", xlab="Retention time (s)",
     main="Chromatogram with very few scans on each side")
#User-provided peakwidth (this is the default)
peakwidth <- c(20, 50)
#Say the scans are 1 second apart
scalerange <- round((peakwidth/1)/2)
scales <- seq(from = scalerange[1], to = scalerange[2], by = 2)
wCoefs <- xcms:::MSW.cwt(sample_chrom, scales = scales, wavelet = "mexh")
head(wCoefs)
# Returns NA, meaning the peak was not found

# If the buffer is increased slightly (to 15 scans)
buffer <- numeric(15)
sample_chrom <- c(buffer, perfect_peak*100, buffer) + runif(length(buffer)*2+actual_peakwidth)
plot(sample_chrom, type="b", ylab="Peak intensity", xlab="Retention time (s)",
     main="Slightly extended chromatogram")
#Provided peakwidth, scalerange, and scales are all the same
wCoefs <- xcms:::MSW.cwt(sample_chrom, scales = scales, wavelet = "mexh")
head(wCoefs)
# Returns the wavelet intensities at the lowest scale only

#If the minimum peakwidth is decreased
buffer <- numeric(10)
plot(sample_chrom, type="b", ylab="Peak intensity", xlab="Retention time (s)",
     main="Same as above, but now with smaller minimum peakwidth")
sample_chrom <- c(buffer, perfect_peak*100, buffer) + runif(length(buffer)*2+actual_peakwidth)
peakwidth <- c(10, 50)
#Say the scans are 1 second apart
scalerange <- round((peakwidth/1)/2)
scales <- seq(from = scalerange[1], to = scalerange[2], by = 2)
wCoefs <- xcms:::MSW.cwt(sample_chrom, scales = scales, wavelet = "mexh")
head(wCoefs)
# Returns the wavelet intensities at the lowest scale only
```

Note that the actual width of the peak we generated is the same in all of these; if I didn’t expect to see any peaks thinner than 20 scans, I would’ve missed this peak with a width of 35.

After some additional debugging within `MSW.cwt()`, it seems that this happens when the chromatogram is “too narrow” according to the relationship

chromatogram length \<= 2^(ceiling(log2(min(peakwidth)\*6)))

i.e., the chromatogram must be longer than the minimum peakwidth\*6, plus some log rounding magic, to be considered as valid and possibly having a peak.

For example, XCMS won’t be able to find peaks in chromatogram with a length less than 8, unless the minimum peakwidth is 1. Peaks in a chromatogram shorter than 16 scans will only be found if the minimum peakwidth is 2 or smaller, shorter than 32 needs a min peakwidth of 4, etc. For the chromatogram above (length of 55) we only find the peak when the minimum peakwidth is 8 or smaller.

To demonstrate:

``` r
# Minimum peakwidth of <=2 allows peakfinding in chromatograms with >9 scans
peakwidth <- c(2, 50)
scales <- seq(min(peakwidth)/2, max(peakwidth)/2, by=2)
xcms:::MSW.cwt(runif(7), scales) #Nope, returns NA
xcms:::MSW.cwt(runif(8), scales) #Nope, returns NA
xcms:::MSW.cwt(runif(9), scales) #Finally, the wavelet transform is performed

# Minimum peakwidth of <=4 allows peakfinding in chromatograms with >17 scans
peakwidth <- c(4, 50)
scales <- seq(min(peakwidth)/2, max(peakwidth)/2, by=2)
xcms:::MSW.cwt(runif(15), scales) #Nope, returns NA
xcms:::MSW.cwt(runif(16), scales) #Nope, returns NA
xcms:::MSW.cwt(runif(17), scales) #Finally, the wavelet transform is performed
```

Again, this is independent of the actual peak’s width. If the minimum peakwidth is 20, then it doesn’t matter whether it’s a peak with width 20 and 20 scans of buffer on each side or if it’s a fat peak with width 60 and no buffer at all.

``` r
peakwidth <- c(20, 80)
# Should be found: peakwidth is 20, min peakwidth is 20
skinny_peak <- c(numeric(20), dnorm(seq(-3, 3, length.out = 20)), numeric(20))*10 +runif(60)
xcms:::MSW.cwt(skinny_peak, scales = peakwidth/2) #Returns NA

# Should definitely be found: 60 is solidly between 20 and 80
wide_peak <- dnorm(seq(-3, 3, length.out = 60))*10 + runif(60)
xcms:::MSW.cwt(wide_peak, scales = peakwidth/2) #Returns NA
```

## Possible solutions

The simplest solution to me, and what seems to be working well so far, is to extend the chromatogram so that all scales are run. Given that the chromatogram is already being extended to have a base-2 length, it seems safe to extend it further. This could be done by modifying the `xcms:::MSW.extendNBase()` to a safe length, rather than simply to the nearest base-2 length. The extension would then be proportional to the minimum peakwidth according to the equation above, but could also be extended further (using `max(peakwidth)` rather than `min(peakwidth)`)
to guarantee all scales are run.

This solution also resolves the problem of passing a single wavelet scale to the rest of the algorithm, because the ridge finder seems to perform poorly when it’s only got a single column in the wCoef matrix (essentially choosing every local maximum as a possible peak).

It’s also easy to implement. I did so by replacing the call to `MSW.extendNBase()` and instead calling `MSW.extendLength()` directly, with `addLength=2^(ceiling(log2(min(scales)*12)))-length(ms)`. However, since the algorithm used to “reflect” the data up to a base-2 length crashes if given an extension length greater than the length of the data, I also changed the method from the default of “reflect” to “open” - i.e. zero-padding the data passed to the FFT rather than duplicating
some amount of it. I’m not a signal-processing expert, but I believe that the zero-padding is the favored method in general and wasn’t able to find a lot of literature using the “reflect” method anyway.

## sessionInfo()

R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
LC_TIME=English_United States.1252    

attached base packages:
stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
pbapply_1.4-2               fuzzyjoin_0.1.5             SummarizedExperiment_1.16.1
DelayedArray_0.12.2         matrixStats_0.55.0          GenomicRanges_1.38.0       
GenomeInfoDb_1.22.0         IRanges_2.20.2              pheatmap_1.0.12            
magrittr_1.5                pander_0.6.3                RColorBrewer_1.1-2         
faahKO_1.26.0               xcms_3.8.1                  MSnbase_2.12.0             
ProtGenerics_1.18.0         S4Vectors_0.24.3            mzR_2.20.0                 
Rcpp_1.0.3                  BiocParallel_1.20.1         Biobase_2.46.0             
BiocGenerics_0.32.0        

loaded via a namespace (and not attached):
vsn_3.54.0             splines_3.6.2          foreach_1.4.7          assertthat_0.2.1      
BiocManager_1.30.10    affy_1.64.0            GenomeInfoDbData_1.2.2 yaml_2.2.0            
robustbase_0.93-5      impute_1.60.0          pillar_1.4.3           lattice_0.20-38       
glue_1.3.1             limma_3.42.0           digest_0.6.23          XVector_0.26.0        
colorspace_1.4-1       htmltools_0.4.0        preprocessCore_1.48.0  Matrix_1.2-18         
plyr_1.8.5             MALDIquant_1.19.3      XML_3.98-1.20          pkgconfig_2.0.3       
zlibbioc_1.32.0        purrr_0.3.3            scales_1.1.0           snow_0.4-3            
RANN_2.6.1             affyio_1.56.0          tibble_2.1.3           ggplot2_3.2.1         
lazyeval_0.2.2         MassSpecWavelet_1.52.0 survival_3.1-8         crayon_1.3.4          
evaluate_0.14          ncdf4_1.17             doParallel_1.0.15      MASS_7.3-51.5         
tools_3.6.2            lifecycle_0.1.0        munsell_0.5.0          pcaMethods_1.78.0     
compiler_3.6.2         mzID_1.24.0            rlang_0.4.2            grid_3.6.2            
RCurl_1.95-4.13        iterators_1.0.12       rstudioapi_0.10        bitops_1.0-6          
rmarkdown_2.1          gtable_0.3.0           codetools_0.2-16       multtest_2.42.0       
R6_2.4.1               knitr_1.27             dplyr_0.8.3            xfun_0.12             
DEoptimR_1.0-8         tidyselect_0.2.5

**Comment by jorainer** [comment]
Wow @wkumler ! This is a very nice and comprehensive description of the problem (including a solution to it!). Impressive!

Would you mind to add a pull request with your proposed solution including a unit test for it?

**Comment by wkumler** [comment]
@jorainer Done! I've created a pull request with the above implementation, as well as two unit tests on synthetic data. Let me know if there's anything else you'd like added! Thanks for the hard work you put in to keeping this maintained and updated.

**Comment by jorainer** [comment]
Thanks for the PR. I checked now the impact your fix has on peak detection of the *ko15.cdf* file. In fact, with your fix more peaks are detected. With your setting the same peaks are identified as before plus in addition some more like the one below (left without and right with your fix):

![CP0004](https://user-images.githubusercontent.com/5506112/74441104-894bbd00-4e6f-11ea-8517-7e8b63ace51a.png)

In fact the data starts at rt 2501, so, the old code failed to identify a peak. I guess this is mostly due to using `method = "open"` in `MSW.extendLength`. Eventually more interesting is the peak below:

![CP0151](https://user-images.githubusercontent.com/5506112/74441411-11ca5d80-4e70-11ea-8db4-563888a7ad01.png)

Here, for whatever reasons, centwave failed to identify a peak before while with your fix we get the peak. I will do some more comparisons to see what and how much your fix changes.

**Comment by wkumler** [comment]
Hi @jorainer, I've kept looking into this as well. One thing that really helped me diagnose it was running the faahKO data under the current XCMS regime and with my new code added, with all the settings the same as they are in the vignette. I can email you the .rds files but it doesn't look like Github supports them so I can't upload them directly. Once they're loaded, it's easy enough to use plotChromPeaks on both of XCMSnExp objects to see the differences between the two for a given file, or some more complicated `merge()`ing or `fuzzy_join()`ing allowing a more detailed analysis of the differences.

A couple other peaks that were newly found in ko15:
mz = c(401.1, 401.3), rt = c(4000, 4200)
mz = c(441.0, 441.2), rt = c(4000, 4200)

And many peaks change their retention time boundaries. I suspect this is actually due to XCMS's use of the best-fitting wavelet as an estimate for the peakwidth, and many of these previously had a single scale or two run on them. Now, with all scales run, they can choose from a wider selection to get a better-fitting peakwidth. However, it seems like the edgefinder often runs away with them and goes well past the edge of the peak.

Some examples of this:
mz = c(419.0, 419.2), rt = c(4000, 4200)
mz = c(577.4, 577.5), rt = c(4000, 4200)

**Comment by jorainer** [comment]
Yep, I can confirm your last comment (regarding the edgefinder). I would suggest, instead of making your fix the default, to add an additional option that allows to use either the old or your new setting. More details in your PR.

**Comment by stanstrup** [comment]
I think this is missing in the print method.

```r
> params
Object of class:  CentWaveParam 
Parameters:
 ppm: 100 
 peakwidth: 1.2, 12 
 snthresh: 5 
 prefilter: 3, 10 
 mzCenterFun: apex 
 integrate: 2 
 mzdiff: -0.001 
 fitgauss: TRUE 
 noise: 0 
 verboseColumns: TRUE 
 roiList length: 0 
 firstBaselineCheck TRUE 
 roiScales length: 0 
> str(params)
Formal class 'CentWaveParam' [package "xcms"] with 15 slots
  ..@ ppm               : int 100
  ..@ peakwidth         : num [1:2] 1.2 12
  ..@ snthresh          : int 5
  ..@ prefilter         : int [1:2] 3 10
  ..@ mzCenterFun       : chr "apex"
  ..@ integrate         : int 2
  ..@ mzdiff            : num -0.001
  ..@ fitgauss          : logi TRUE
  ..@ noise             : int 0
  ..@ verboseColumns    : logi TRUE
  ..@ roiList           : list()
  ..@ firstBaselineCheck: logi TRUE
  ..@ roiScales         : num(0) 
  ..@ extendLengthMSW   : logi FALSE
  ..@ .__classVersion__ :Formal class 'Versions' [package "Biobase"] with 1 slot
  .. .. ..@ .Data:List of 2
  .. .. .. ..$ : int [1:3] 0 0 1
  .. .. .. ..$ : int [1:3] 0 0 1
```

**Comment by jorainer** [comment]
good point. I will fix.

**Comment by jorainer** [comment]
Actually, this is fixed already in the current devel version

**Comment by lingjuewang** [comment]
This is an impressive and detailed discussion. One more comment is that the `peaksWithCentWave` for EIC detection has not included this build-up yet. Would be great to have it as well.
