### ISSUE TITLE
Suppress xcmsRaw message print

### ISSUE THREAD

**Issue by poofcakes** [sneumann/xcms#447]
Hello. I was wondering if there's a way to suppress the `Create profile matrix with method 'bin' and step 1 ... OK` that gets printed when using the xcmsRaw function. It's being printed to my error output, which makes it seem like there's an issue when there's not (at least I assume so).

**Comment by sneumann** [comment]
Sounds reasonable. Can you locate the code in question ?
Yours, Steffen

**Comment by poofcakes** [comment]
https://github.com/sneumann/xcms/blob/557b936967271690140e19224be707d87ea63168/R/methods-xcmsRaw.R#L2373

**Comment by stanstrup** [comment]
You can wrap the `xcmsRaw ` call in `suppressMessages`. That should avoid the message.

**Comment by poofcakes** [comment]
> You can wrap the `xcmsRaw ` call in `suppressMessages`. That should avoid the message.

Thank you! That's exactly what I was looking for. Not sure how I missed it in my google hunt.

**Comment by jorainer** [comment]
I think there might even be a global option you can set in R to suppress messages - always.

**Comment by jorainer** [comment]
Closing the issue - feel free to re-open if necessary.
