### ISSUE TITLE
groupChromPeaks -> adjustRtime -> groupChromPeaks -> adjustRtime

### ISSUE THREAD

**Issue by lecorguille** [sneumann/xcms#448]
Hi here,

With @jfrancoismartin and @yguitton, and the W4M team, we are in the middle of a researcher school.
Obviously, we meet some strange use-cases :)

One of our trainee want to chain groupChromPeaks -> adjustRtime -> groupChromPeaks -> adjustRtime as it was possible with xcms 1.x (unless we are mistaken). The idea is to refine the alignment.

It seems now impossible:
```R
> adjustRtime(xdata, PeakGroupsParam())
Removing previous alignment results
Reverting retention times of identified peaks to original values ... OK
Error in .local(object, param, ...) :
  No feature definitions found in 'object'! Please perform first a peak grouping using the 'groupChromPeak' method.
```

Indeed, [here](https://github.com/sneumann/xcms/blob/73ccc9018ba6d3b39c179128094a34db2b88c297/R/methods-XCMSnExp.R#L1905-L1921), at the beginning of `adjustRtime`, `dropAdjustedRtime()`is applied. And [here](https://github.com/sneumann/xcms/blob/73ccc9018ba6d3b39c179128094a34db2b88c297/R/methods-XCMSnExp.R#L834-L842), the features are dropped `dropFeatureDefinitions()`

We are not questioning this choice, but we are trying to understand it.

All the best

**Comment by jorainer** [comment]
You can still do that:

`groupChromPeaks` -> `adjustRtime` -> `applyAdjustedRtime` -> `groupChromPeaks` -> `adjustRtime` ...

i.e. do a 
```r
xdata <- applyAdjustedRtime(xdata)
```
after each `adjustRtime` call.

The point is that `adjustRtime` does not change the retention times, it just adds them as a parallel numeric vector next to the original retention times and also updates/adjusts the retention times of the identified chromatographic peaks (in `chromPeaks`) - this is the same behaviour as in the old `xcms`. A next alignment would now replace this numeric vector with new adjusted retention times and adjust the (already adjusted retention times) in `chromPeaks` a second time. This will ultimately lead to a miss-match between this vector of adjusted retention times and the retention times reported in the `chromPeaks` matrix. So, while it was possible to do this with the old `xcms`, I'm not quite sure if it was doing it correctly.

With the `applyAdjustedRtime` you're actually **replacing** the raw retention times of the spectra with the adjusted ones. The object looks than like there was no alignment performed (although all retention times, of the spectra and the chrom peaks, are now adjusted). On this you can now perform a second round of alignment and, if you want to go for yet another round, call `applyAdjustedRtime` on it again.

**Comment by lecorguille** [comment]
Many thanks @jorainer 
FYI: here is the implementation: https://github.com/workflow4metabolomics/tools-metabolomics/pull/172
