### ISSUE TITLE
Add parameter `add` to `findChromPeaks`

### ISSUE THREAD

**Issue by jorainer** [sneumann/xcms#452]
Add a parameter `add` to `findChromPeaks` to allow performing a second round of peak detection, adding the newly found peaks. This would help also for issue #451

**Comment by ricoderks** [comment]
Hi, 
I would like to use this parameter, but I get the error unused argument. I'am using XCMS 3.12.0 with R 4.0.2. Is this parameter only available in a newer version of XCMS?

Cheers, Rico

**Comment by jorainer** [comment]
It should be available in xcms version 3.12.0. You would need to call it like:

```r
data <- readMSData...
data <- findChromPeaks(data, param = ...)
data <- findChromPeaks(data, add = TRUE, param = ...)
```

that *should* work. Note that this is only defined for `findChromPeaks,XCMSnExp` but not for `findChromPeaks,OnDiskMSnExp` (which also makes no sense, because that object can not contain any chromatographic peaks).

**Comment by ricoderks** [comment]
Ooh, crap! I feel so stupid now. I did it on `OnDiskMSnExp`. My apologies! Thanks for the quick reply!

**Comment by jorainer** [comment]
no worries :) happy if you find the option useful!
