### ISSUE TITLE
Error with function findChromPeaks

### ISSUE THREAD

**Issue by anna1900learn** [sneumann/xcms#456]
In the example data of xcms preprocessing I get the following error:
Example data: https://www.bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html

xchr <- findChromPeaks(chr_raw, param = CentWaveParam(snthresh = 2))
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘findChromPeaks’ for signature ‘"Chromatograms", "CentWaveParam"’

I have uninstalled and again installed all the packages used but I still get this error. Do you know why?

**Comment by sneumann** [comment]
Hi, can you give a bit more background ? Are you going through the tutorial chunk by chunk and cut&pasting the code snippets ? Which version of xcms are you using `sessionInfo()` ? Yours, Steffen

**Comment by anna1900learn** [comment]
Hi!
I have reinstalled R to the newest version then I installed xcms again and then this error disappear! :)

But one issue still appear:
raw_data <- readMSData(files = cdfs, pdata = new("NAnnotatedDataFrame", pd),
+                        mode = "onDisk")
Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.

About polarity, is this a problem? Should I handle it? In that case, how should it be handled?
Thanks!

**Comment by sneumann** [comment]
Is that polarity thing error or warning ? Currently, XCMS doesn't care about polarity, safe to ignore. Yours, Steffen

**Comment by anna1900learn** [comment]
It seems to be a warning.
Thanks!

**Comment by sneumann** [comment]
Ok, no worries then. Yours, Steffen
