### ISSUE TITLE
filterAcquisitionNum not working as expected

### ISSUE THREAD

**Issue by breidan** [sneumann/xcms#457]
Hi,
I'm trying to apply `filterAcquisitionNum` to an OnDiskMSnExp object and get the following error: "Fehler in .local(object, ...) : 
  Argument 'n' has to be an integer representing the acquisition number(s) for sub-setting."
Working with R V3.6.2, xcms 3.8.2, MSnbase 2.12.0.
The commands are:

    library(msdata)
    fms3 <- proteomics(full.names = TRUE, pattern = "MS3TMT11.mzML")
    ms3 <- readMSData(fms3, mode = "onDisk")
    filterAcquisitionNum(ms3,21945)

Am I doing something wrong here?

**Comment by jorainer** [comment]
Seems the problem is that the function expects an `integer`, but you provided a `numeric`. You would have to write either `as.integer(21945)` or `21945L`.

**Comment by breidan** [comment]
You always learn something new. Just because it looks like an integer does not mean it is an integer :-)
Thanks
