### ISSUE TITLE
Finding peaks in m/z space with MSW methods

### ISSUE THREAD

**Issue by breidan** [sneumann/xcms#458]
I am very much interested in detection of peaks in the m/z space after infusion experiments with FTMS instruments, in particular Orbitraps. I looked at the vignette `Grouping FTICR-MS data with xcms` where it seems to work with the example data. But looking at the example `fticr` data the spacing between the m/z values seems to be too even for FTMS data. And the uneven spacing of the FTMS m/z scale seems to be a problem for `MassSpecWavelet::cwt`. 
So using another file from the `msdata` package I extract a slice of m/z 600 - 750 of a MS1 event.
Load example data:
```{r example-data}
library(msdata)
fms3 <- proteomics(full.names = TRUE, pattern = "MS3TMT11.mzML")
ms3 <- readMSData(fms3, mode = "onDisk")
### taking a slice of one of the MS1 spectra
spec<-ms3%>%filterAcquisitionNum(22118L)%>%filterMz(c(600,750))
```
`spec` contains signals of one singly charged and several doubly charged compounds and the m/z spacing is uneven. Executing `findChromPeaks` as in vignette `Grouping FTICR-MS data with xcms`:
```{r vignette}
msw<-MSWParam()
spec_vignette<-findChromPeaks(spec,param = msw)
```
Many of the isotopic signals are missed even for the singly charged at around m/z 640. Using `bin` and `smooth` I can get even spacing of the m/z scale and continuos intensities.
Executing `findChromPeaks` after binning and smoothing:
```{r bin-smooth}
msw<-MSWParam()
spec_binsmooth<-spec%>%bin(binSize=0.0007)%>%smooth(method="SavitzkyGolay",
                             halfWindowSize=40)%>%findChromPeaks(param = msw)
```
This will detect all of the isotopic signals plus a lot of the very small signals. But for compounds with higher charge states and/or spectra which are denser the smoothing leads to loss of detail. Advantage of this approach is that a XCMSnExp object is obtained for further processing.

Using `stats::approx()` I can resample the spectral data to even m/z spacing and through the linear interpolation to intensities which closely reflect the original data even for dense spectral areas. Then I can use `xcms::do_findPeaks_MSW` on the resampled data and obtain the `chromPeaks` matrix. Peak detection is slightly better than with `bin` `smooth` and also slightly faster. Intensity ratios of isotopic envelope are much less distorted than with `smooth`. But here it stops. Now I have a MSnExp object and the ´chromPeaks´ matrix but not a XCMSnExp object which I could use for further processing.

So my issue is twofold: Is there anything that works like `stats::approx()` and does linear interpolation on a MSnExp, or better yet, OnDiskMSnExp object? Or how do I create the `msFeatureData` and `.processHistory` slots and fill them to obtain a XCMSnExp object afterwards?

**Comment by sneumann** [comment]
Hi, that's a very thorough description, thanks for sharing that experience. 
There was another discussion in https://github.com/sneumann/xcms/issues/237 
on flow injection, and the actual MSW algorithm is described in 
```
Du P, Kibbe WA, Lin SM (2006). “Improved peak detection in mass spectrum by incorporating continuous wavelet transform-based pattern matching.” Bioinformatics, 22, 2059-2065. 
```
Could it be possible that modifying the `MSWParam()` helps for your data ?
Yours, Steffen

**Comment by breidan** [comment]
Hi Steffen,
I have read the paper and I have played around with the `MSWParam()` settings but to no avail. When you look at `MassSpecWavelet::cwt` the authors implicitely expect an evenly spaced m/z scale.
Thinking about it...because I like my approach :-) and because I would like to learn more about `xcms` the option of how to create and fill the `msFeatureData` and `.processHistory` slots is preferred.
Cheers
Andreas

**Comment by jorainer** [comment]
Regarding now to get an `XCMSnExp` object from an `MSnExp` + `chromPeaks` matrix - unfortunately that's not possible because the `XCMSnExp` does not support keeping spectral data in memory (it's not ideal, I agree - and we're planning to move from the `MSnbase` objects to the new objects which are being developed in [RforMassSpectrometry](https://rformassspectrometry.org)).

Now, if you have an `MSnExp` what you can do is to export this to mzML with `writeMSData` and then read is again with `readMSData(..., mode = "onDisk")`. You can then convert the resulting `OnDiskMSnExp` object to an `XCMSnExp` object with `data <- as(data, "XCMSnExp")` (where `data` is your `OnDiskMSnExp` object). Now it should be possible to use `chromPeaks(data) <- cp` to add the identified chromatographic peaks (`cp`) to the object.

**Comment by breidan** [comment]
@jorainer,
thanks for that. I will try it and report. How would I go about creating the processHistory?

**Comment by jorainer** [comment]
You would do like:
```r
xph <- xcms:::XProcessHistory(param = param , type = xcms:::.PROCSTEP.PEAK.DETECTION, 
    msLevel = 1L, fileIndex = seq_along(fileNames(data)))
data@.processHistory <- c(data@.processHistory, list(xph))
```

**Comment by breidan** [comment]
@jorainer,
thanks for the help. I have a function now which takes an OnDiskMSnExp object, runs `do_findPeaks_MSW` on a FTMS spectrum resampled with `approx`, and returns a valid XCMSnExp object.

XCMS and MSnbase are great pieces of work.

**Comment by jorainer** [comment]
Thanks for the feedback @breidan !

I'm closing this issue now - feel free to re-open if needed.
