### ISSUE TITLE
Code as(xs, "xcmsSet") throws error due to matrix list

### ISSUE THREAD

**Issue by wkumler** [sneumann/xcms#464]
Hi all, me again. I’ve been super happy with my xcms results since the last pull request and have started moving on to using CAMERA to de-adduct and de-isotope my peak lists. However, I’m having some trouble converting the `XCMSnExp` object into a usable `xcmsSet` to pass to CAMERA.

I think the problem is because the new `XCMSnExp` object has an additional column in the `featureDefinitions` spot. This is problematic because the final column of the `featureDefinitions` is dropped when converting to an `xcmsSet` object with the line below:

    xs@groups <- S4Vectors::as.matrix(fgs[, -ncol(fgs)])

However, the column it’s supposed to drop is actually the peakidx column that *used* to be the final column, but is now the second-to last one. (I think at some point the `ms_level` column was added at the end.) Because the `peakidx` column is composed of lists and lists can’t be
trivially simplified to numbers, the matrix produced has a `typeof()` of `list` rather than `double`. This is problematic for CAMERA because upon conversion to `xsAnnotate` object, it assumes that the column type is `double` rather than `list`, and throws an error.

A simple solution would be to specify the `peakidx` column by name rather than column index with the below code instead:

    xs@groups <- S4Vectors::as.matrix(fgs[,names(fgs)!="peakidx"])

This change ensures that the `peakidx` column is dropped instead of the `ms_level` column, allows the `as.matrix` function to coerce it to a matrix `typeof()` of `double` rather than `list`, and CAMERA is happy to accept it again. Demonstration using the faahko data below:

    library(CAMERA)
    library(faahKO)
    library(dplyr)

    filepath <- system.file("cdf", package = "faahKO")
    cdfs <- filepath %>% list.files(full.names = TRUE, recursive = TRUE)
    metadata <- data.frame(fileid=basename(cdfs), 
                           sampletype=rep(c("KO", "WT"), each=6))
    metadata <- new(metadata, Class = "NAnnotatedDataFrame")
    raw_data <- readMSData(files = cdfs, pdata = metadata, 
                           mode = "onDisk", verbose = TRUE)

    ## Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method.
    ## Reading 1278 spectra from file ko15.CDF
    ## (...etc)

    cwp <- CentWaveParam(noise = 5000, prefilter = c(3, 5000))
    xdata <- findChromPeaks(raw_data, param = cwp)

    ## Detecting mass traces at 25 ppm ... OK 
    ## Detecting chromatographic peaks in 2075 regions of interest ... OK: 424 found.
    ## (...etc)

    xdata_rt <- adjustRtime(xdata, param = ObiwarpParam())

    ## Sample number 6 used as center sample.

    ## Aligning ko15.CDF against ko22.CDF ... OK
    ## (...etc)
    ## Applying retention time adjustment to the identified chromatographic peaks ... OK

    pgp <- PeakDensityParam(sampleGroups = metadata@data$sampletype)
    xdata_cor <- groupChromPeaks(xdata_rt, param = pgp)

    ## Processing 3196 mz slices ... OK

    xdata_filled <- fillChromPeaks(xdata_cor, param = FillChromPeaksParam())

    ## Defining peak areas for filling-in .... OK
    ## Start integrating peak areas from original files
    ## Requesting 80 peaks from ko15.CDF ... got 72.
    ## (...etc)

    # All the above is taken more or less verbatim from the xcms vignette
    # Attempt to convert using currently existing code:

    xset <- as(xdata_filled, "xcmsSet")
    xsa <- xsAnnotate(xset) #Throws an error:

    ## Error in round(groupmat[, "mzmed"], 1): non-numeric argument to mathematical function

    # Check on the CAMERA vignette to see why it's still working fine
    # Load the saved xcmsSet object (part of CAMERA vignette)
    xsg <- group(faahko)

    ## Processing 3195 mz slices ... OK

    head(xcms::groups(xset)) #Note that the peakidx column is a list and hasn't been dropped

    ##      mzmed mzmin mzmax rtmed    rtmin    rtmax    npeaks KO WT peakidx   
    ## [1,] 205   205   205   2790.417 2785.763 2794.995 12     6  6  Numeric,12
    ## [2,] 206   206   206   2790.894 2787.715 2793.467 10     4  5  Numeric,13
    ## [3,] 207.1 207.1 207.1 2719.154 2715.495 2721.164 6      2  3  Numeric,13
    ## [4,] 233   233   233.1 3029.032 3014.683 3032.421 8      4  3  Numeric,13
    ## [5,] 241.1 241.1 241.2 3686.681 3674.931 3735.887 15     3  6  Numeric,18
    ## [6,] 244.1 244.1 244.1 2834.55  2831.728 2836.562 5      2  3  Numeric,12

    head(xcms::groups(xsg)) #Here, the peakidx column has been properly dropped

    ##         mzmed    mzmin    mzmax    rtmed    rtmin    rtmax npeaks KO WT
    ## [1,] 200.1000 200.1000 200.1000 2926.264 2876.967 2931.740     10  5  5
    ## [2,] 205.0000 205.0000 205.0000 2790.894 2784.635 2795.591     12  6  6
    ## [3,] 205.9927 205.9786 206.0023 2790.112 2784.635 2795.591     12  6  6
    ## [4,] 207.0850 207.0440 207.1000 2718.906 2712.647 2726.731     12  6  6
    ## [5,] 219.0848 219.0488 219.1000 2524.852 2518.592 2529.547      9  4  5
    ## [6,] 231.0236 231.0000 231.0812 2517.029 2509.202 2535.807      6  3  3

    typeof(xcms::groups(xset)) #list

    ## [1] "list"

    typeof(xcms::groups(xsg)) #double

    ## [1] "double"

    # :: notation necessary because groups() is masked from dplyr

    # Define a new coercion function with the implemented change
    # Stolen from functions-XCMSnExp.R
    .XCMSnExp2xcmsSet_wkumler <- function(from) {
        if (any(msLevel(from) > 1))
            stop("Coercing an XCMSnExp with MS level > 1 is not yet supported!")
        xs <- new("xcmsSet")
        ## @peaks <- chromPeaks
        if (hasChromPeaks(from))
            xs@peaks <- chromPeaks(from)
        ## @groups <- part of featureDefinitions
        ## @groupidx <- featureDefinitions(x)$peakidx
        if (hasFeatures(from)){
            fgs <- featureDefinitions(from)
            xs@groups <- S4Vectors::as.matrix(fgs[,names(fgs)!="peakidx"])
            rownames(xs@groups) <- NULL
            xs@groupidx <- fgs$peakidx
        }
        ## @rt combination from rtime(x) and adjustedRtime(x)
        rts <- list()
        ## Ensure we're getting the raw rt
        rts$raw <- rtime(from, bySample = TRUE, adjusted = FALSE)
        if (hasAdjustedRtime(from))
            rts$corrected <- adjustedRtime(from, bySample = TRUE)
        else
            rts$corrected <- rts$raw
        xs@rt <- rts

        ## @phenoData
        xs@phenoData <- pData(from)
        ## @filepaths
        xs@filepaths <- fileNames(from)

        ## @profinfo (list)
        profMethod <- "bin"
        profStep <- 0.1
        profParam <- list()
        ## If we've got any MatchedFilterParam we can take the values from there
        ph <- processHistory(from, type = xcms:::.PROCSTEP.PEAK.DETECTION)
        if (length(ph)) {
            if (is(ph[[1]], "XProcessHistory")) {
                prm <- processParam(ph[[1]])
                if (is(prm, "MatchedFilterParam")) {
                    if (impute(prm) != "none") {
                        profMethod <- paste0("bin", impute(prm))
                        profStep <- binSize(prm)
                        if (profMethod == "binlinbase")
                            warning("Optional parameters for 'binlinbase' can not be",
                                    " converted yet, using default parameters.")
                    ## distance
                    ## baseValue
                    }
                }
            }
        }
        profinfo(xs) <- c(list(method = profMethod, step = profStep), profParam)

        ## @mslevel <- msLevel?
        xs@mslevel <- unique(msLevel(from))

        ## @scanrange
        xs@scanrange <- range(scanIndex(from))

        ## .processHistory: just take the processHistory as is.
        xs@.processHistory <- processHistory(from)

        ## Implement later or skip:
        ## @polarity (character), has to be "positive" or "negative"; not clear how
        ## and if this is used at all.

        ## @filled ... not yet.
        if (any(chromPeakData(from)$is_filled)) {
            fld <- which(chromPeakData(from)$is_filled)
            xs@filled <- as.integer(fld)
        }
        ## @dataCorrection (numeric) ? in xcmsSet function, if lockMassFreq.
        ## @progressInfo skip
        ## @progressCallback skip
        if (!any(colnames(pData(from)) == "class"))
            message("Note: you might want to set/adjust the",
                    " 'sampclass' of the returned xcmSet object",
                    " before proceeding with the analysis.")
        if (validObject(xs))
            return(xs)
    }

    #Compare outputs
    xset_orig <- xcms:::.XCMSnExp2xcmsSet(xdata_filled)

    ## Note: you might want to set/adjust the 'sampclass' of the returned xcmSet object before proceeding with the analysis.

    xset_wkumler <- .XCMSnExp2xcmsSet_wkumler(xdata_filled)

    ## Note: you might want to set/adjust the 'sampclass' of the returned xcmSet object before proceeding with the analysis.

    xsAnnotate(xset_orig) # Throws the same error as before

    ## Error in round(groupmat[, "mzmed"], 1): non-numeric argument to mathematical function

    xsAnnotate(xset_wkumler) #Succeeds

    ## An "xsAnnotate" object!
    ## With 0 groups (pseudospectra)
    ## With 12 samples and 294 peaks
    ## Polarity mode is set to:   
    ## Using automatic sample selection
    ## Memory usage: 3.26 MB

If this is a good and useful change, I’m happy to submit another pull request and some unit tests!

**Comment by jorainer** [comment]
Hi @wkumler, I was not aware that the conversion to `xcmsSet` does no longer work. Yes, sure, happy if you make a pull request (to the current master branch).

**Comment by wkumler** [comment]
Hi @jorainer, I've tried a couple times to add this and a couple unit tests to assert proper behavior but now can't get it to pass R CMD check due to the unit tests I've added. I'm having trouble diagnosing it because installing via RStudio works perfectly and the functionality is present afterward. The unit tests run fine when I run them manually, so I'm suspecting a namespace issue with R not knowing which version of XCMS to run.

I noticed that there were no unit tests for the XCMSnExp -> xcmsSet conversion, so I created a new test_that() function. Were you having similar problems and decided not to test that method for the same reason?

**Comment by jorainer** [comment]
The unit test is in *test_methods-XCMSnExp.R*, it's called `test_that("as,XCMSnExp,xcmsSet works")`. Don't worry if your local unit tests fail. If you make the pull request it will be automatically tested also using github actions (and Travis CI).

**Comment by wkumler** [comment]
@jorainer Found them! And I found the test that was failing - one of the earlier tests does a similar thing where it drops only the last column rather than the `peakidx` column, so I made the same change there. It looks like it's now passing R CMD check on Travis CI and is probably ready for a pull request after I merge any upstream changes.

**Comment by jorainer** [comment]
Excellent!

**Comment by wkumler** [comment]
Pull request done! Let me know if there's anything more I can do to help, and apologies for the slow process - things have been a little hectic lately.

**Comment by jorainer** [comment]
Thanks! I really appreciate that!
