### ISSUE TITLE
Plotting spectra (MS1 level), xcms vignette

### ISSUE THREAD

**Issue by Tony-II** [sneumann/xcms#465]
Whilst following the vignette under

[](https://www.bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html#4_chromatographic_peak_detection)

according to 

```
raw_data %>%
  filterRt(rt = rtr) %>%
  filterMz(mz = mzr) %>%
  plot(type = "XIC")

```

which works fine, I thus also tried:

```
raw_data %>%
  filterRt(rt = rtr) %>%
  filterMz(mz = mzr) %>%
  plot(type = "spectra")

```

but I get the error: 

`Error in if (centroided.) { : missing value where TRUE/FALSE needed`

Is there a suggestion on what is to be done for plotting the spectra (MS1)?

**Comment by jorainer** [comment]
Seems that `centroided(raw_data)` is `NA` in your case. A quick fix for that is to manually specify if the data is centroided or not. If it is centroided do `fData(raw_data)$centroided <- TRUE`, if not `fData(raw_data)$centroided <- FALSE`. With that you should be able to execute the commands above.

**Comment by Tony-II** [comment]
I forgot in my first post to include the link, mentioning that I use the vignette (release) of xcms
I am only using the demo data as available in the current stable releases of Bioconductor 3.10 (with R 3.6.3) and also no own code, just the code as per vignette:

[](https://www.bioconductor.org/packages/release/bioc/vignettes/xcms/inst/doc/xcms.html#4_chromatographic_peak_detection
)

Unfortunately I get no plot drawn with:

`
fData(raw_data)$centroided <- FALSE
raw_data %>%
  filterRt(rt = rtr) %>%
  filterMz(mz = mzr) %>%
  plot(type = "spectra")  #  device opens, but very less visible ...

`

**Comment by jorainer** [comment]
The type `"spectra"` AFAIK draws each spectrum separately and the plot can become very busy when you have many spectra. Try with the `type = "XIC"`, this should show you some data - unless you have many samples in your `raw_data`.

**Comment by Tony-II** [comment]
thank you for the answer.

Is there maybe any way/workaround to get an analogue (for `type = "XIC"`) plot for the spectrum, maybe restricted to the peak apex scan?
