### ISSUE TITLE
fillChromPeaks Throwing Exception

### ISSUE THREAD

**Issue by sjgreig27** [sneumann/xcms#475]
Hello, I apologise if this is my misinterpretation as I am new to both R and XCMS but I am having some issues running direct infusion data through XCMS. My script is based upon the following -> https://rdrr.io/bioc/xcms/f/vignettes/xcms-direct-injection.Rmd.

The exception is:
Requesting X peaks <file name>.mzML ... Error in mtx[, 3]: subscript out of bounds

Here is the relevant part of the script, that is following the example a little too faithfully at the moment:
```R
mzdata_files <- list.files(mzdata_path, recursive = TRUE, full.names = TRUE)

## Create a data.frame assigning samples to sample groups, i.e. ham4 and ham5.
grp <- rep("ham4", length(mzdata_files))
grp[grep(basename(mzdata_files), pattern = "^160518")] <- "hela"
pd <- data.frame(filename = basename(mzdata_files), sample_group = grp)

## Load the data.
ham_raw <- readMSData(files = mzdata_files,
                      pdata = new("NAnnotatedDataFrame", pd),
                      mode = "onDisk")

## Only a single spectrum with an *artificial* retention time is available
## for each sample
rtime(ham_raw)

## Define the parameters for the peak detection
msw <- MSWParam(scales = c(1, 4, 9), nearbyPeak = TRUE, winSize.noise = 500,
                SNR.method = "data.mean", snthresh = 10)

my_prep <- findChromPeaks(ham_raw, param = msw)
write.csv(chromPeaks(my_prep), file = file.path(output_peak_dir, 'chromPeaks.csv'))

## Using default settings but define sample group assignment
mzc_prm <- MzClustParam(sampleGroups = my_prep$sample_group)
my_prep <- groupChromPeaks(my_prep, param = mzc_prm)

## Here is where the exception is thrown
my_prep <- fillChromPeaks(my_prep, param = FillChromPeaksParam())

feat_vals <- featureValues(my_prep, value = "into")
write.csv(featureDefinitions(my_prep), file = file.path(output_peak_dir, 'featureDefinitions.csv'))
write.csv(feat_vals, file = file.path(output_peak_dir, 'filledPeaks.csv'))
```

When fillChromPeaks is called, I get to this line:
```R
if (findPeakMethod == "MSW") {
	rts <- rtime(object, bySample = TRUE)
	if (any(lengths(rts) > 1)) 
		stop("The data is supposed to be direct injection data, ", 
			"but I got files with more than one spectrum/", 
			"retention time!")
         # Exception originates from .getMSWPeakData ***
	res <- bpmapply(FUN = .getMSWPeakData, objectL, pkAreaL, 
		as.list(1:length(objectL)), MoreArgs = list(cn = cp_colnames), 
		BPPARAM = BPPARAM, SIMPLIFY = FALSE)
}
```

And then onto .getMSWPeakData:

```R
for (i in 1:nrow(res)) {
	mz_area <- which(mzs >= peakArea[i, "mzmin"] & mzs <= 
		peakArea[i, "mzmax"])
	mtx <- cbind(time = -1, mz = mzs[mz_area], intensity = ints[mz_area])
	if (length(mtx)) {
		if (!all(is.na(mtx[, 3]))) {
			res[i, "into"] <- sum(mtx[, 3], na.rm = TRUE)
			mzDiff <- abs(mtx[, 2] - peakArea[i, "mzmed"])
			mz_idx <- which(mzDiff == min(mzDiff))
			maxi <- mz_idx[which.max(mtx[mz_idx, 3])]
			res[i, c("mz", "maxo")] <- mtx[maxi, 2:3]
		}
		else {
			res[i, ] <- rep(NA_real_, ncols)
		}
	}
	else {
		res[i, ] <- rep(NA_real_, ncols)
	}
}
```

The issue seems to be that when you find features within this range you'll get "time", "mz" and "intensity". However, when no peaks are found then you seem to get just "time" (mtx num [1, 1] -1) which causes the exception to be thrown because mtx still has a length. I apologise in advance if this error is simply my lack of knowledge of XCMS or R but as the check for length is there I thought it was worth posting the issue to check.

XCMS Version: 3.10.0
R Version: 4.0.0

Thank you for taking the time to read through my issue and if there is any other information that would be useful then please let me know.

**Comment by sonial** [comment]
Hi,

I am getting the same error following a similar procedure - only difference is that I started from direct infusion data containing multiple scans, which were combined as described [here](https://github.com/lgatto/MSnbase/issues/404). 

@sjgreig27, have you found a fix?

**Comment by sjgreig27** [comment]
Hi @sonial,

I think we have the same issue, the data I have is direct infusion data as well containing multiple ms1 scans. I've used ProteoWizard to filter by polarity and just include ms level 1. I'm happy to share my script if that is of any use to you. I've modified it slightly but have the same issue as before.

```R
library(xcms)
library(MassSpecWavelet)
library(CAMERA)

register(SerialParam())

merge_spectra <- function(
  input_dir,
  output_dir
){
  
  # ## https://github.com/lgatto/MSnbase/issues/404
  # ## https://github.com/sneumann/xcms/issues/237
  # ## https://rdrr.io/bioc/xcms/f/vignettes/xcms-direct-injection.Rmd
  if(!dir.exists(output_dir)){
    dir.create(output_dir)
  }
  
  # ## 1. Load ms1 profile data mzML format
  ms_profile_files <- list.files(input_dir, recursive = TRUE, full.names = TRUE)
  for (i in 1:length(ms_profile_files)){
    profile <- readMSData(ms_profile_files[i], pdata=NULL, msLevel. = 1, verbose = isMSnbaseVerbose(), centroided.=NA, smoothed.=NA, cache.=1L, mode="onDisk")
    spec <- Spectra(spectra(profile))
    comSpec <- combineSpectra(object=spec, method=meanMzInts)
    comSpec[[1]]@rt <- -1
    writeMSData(object = as(comSpec, "MSnExp"), file = file.path(output_dir, basename(ms_profile_files[i])))
  }
}

main <- function(
  input_dir,
  output_dir,
  data_dir
){
  # merge_spectra(input_dir, output_dir)
  mzdata_files <- list.files(output_dir, recursive = TRUE, full.names = TRUE)
  
  ## Create a data.frame assigning samples to sample groups, i.e. ham4 and ham5.
  grp <- rep("Hek", length(mzdata_files))
  grp[grep(basename(mzdata_files), pattern = "HeLa")] <- "HeLa"
  pd <- data.frame(filename = basename(mzdata_files), sample_group = grp)
  
  direct_injection_raw <- readMSData(files = mzdata_files, pdata = new("NAnnotatedDataFrame", pd), mode = "onDisk")
  # ## Define the parameters for the peak detection
  msw <- MSWParam()
  direct_injection_prep <- findChromPeaks(direct_injection_raw, param = msw, msLevel=1)
  write.csv(chromPeaks(direct_injection_prep), file = file.path(data_dir, 'chromPeaks.csv'))
  mzc_prm <- MzClustParam(sampleGroups = direct_injection_prep$sample_group)
  direct_injection_prep <- groupChromPeaks(direct_injection_prep, param = mzc_prm)
  write.csv(featureDefinitions(direct_injection_prep), file = file.path(data_dir, 'featureDefinitions.csv'))
  feat_vals <- featureValues(direct_injection_prep, value = "into", msLevel=1)
  write.csv(feat_vals, file = file.path(data_dir, 'featureValues.csv'))
  direct_injection_prep <- fillChromPeaks(direct_injection_prep, msLevel=1, param=FillChromPeaksParam())
  feat_vals <- featureValues(direct_injection_prep, value = "into", msLevel=1)
  write.csv(feat_vals, file = file.path(data_dir, 'filledPeaks.csv'))
}
```

Unfortunately I still haven't figured out the cause of the issue. From above I can see where the exception originates but I need to spend a bit more time working on debugging it and understanding the surrounding logic to see if this is just something daft I'm just missing.

**Comment by jorainer** [comment]
Thanks for reporting this. I made a (very simple) tentative fix for this issue - could you please check if this indeed fixes the problem (I can't because I haven't any data to test this)?

To install the `xcms` version with the tentative fix:

```r
devtools::install_github("sneumann/xcms", ref = "jomaster")
```

**Comment by sjgreig27** [comment]
Hi @jorainer, thank you for having a look into this for me! It's really appreciated! I've rerun my data and that seems to have done the trick for me. If you have a chance @sonial, would you be able to confirm that this is indeed fixed. Once again, thank you so much for your help with this!

**Comment by sjgreig27** [comment]
![Screenshot 2020-05-19 at 15 22 00](https://user-images.githubusercontent.com/10533127/82338159-756ea480-99e4-11ea-9385-202b9a6a1297.png)

Just checked the solution in the debugger and I think it looks good to me! Cheers @jorainer

**Comment by sonial** [comment]
Thanks a lot Johannes, it works for me too!

**Comment by jorainer** [comment]
Great. Thanks for the feedback and reporting the problem! It might take some time until this is included into the current version in the Bioconductor release 11 - in the meantime I suggest you use *jomaster* branch.

I'm also closing the issue. Feel free to reopen if needed.
