### ISSUE TITLE
New vignette benchmarking.Rmd requires new dependency

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#48]
````
* checking re-building of vignette outputs ... NOTE
Error in re-building vignettes:
  ...

    IQR, mad, xtabs

Quitting from lines 48-52 (benchmarking.Rmd) 
Error: processing vignette 'benchmarking.Rmd' failed with diagnostics:
there is no package called 'microbenchmark'
````

**Comment by jotsetung** [comment]
I'll replace the microbenchmark stuff by standard timing functions to avoid the need to include that into the dependencies.

**Comment by jotsetung** [comment]
Added `microbenchmark` to `Suggests`. Decided to include the package since the timings it provides are much more accurate then `system.time` calls. Benchmarking vignette was thus added in commit https://github.com/sneumann/xcms/commit/1d3bb742ee0ea3e4f2b3739a59baf15574e1b1d3.
