### ISSUE TITLE
How to set polarity for netCDF data?

### ISSUE THREAD

**Issue by ZandkarimiF** [sneumann/xcms#483]
Hi there, 

I am trying to process my LC-MS data using " xcms 3.10.1" and I am getting the following message when I load 
```

readMSData(files = cdfsNeg, pdata = new("NAnnotatedDataFrame", pd), mode = "onDisk")

Polarity can not be extracted from netCDF files, please set manually the polarity with the 'polarity' method

```
From the message, it is clear that netCDF files do not contain the polarity information, but I'd like to know how I can manually set the polarity?

It seems the polarity method only "returns" the polarity values (NA's) for every feature. But I cannot figure out how to set it? (E.g., negative ion mode in my case)

Thank you so much for your help,
Fereshteh

**Comment by sneumann** [comment]
Hi, indeed polarity is not set from netCDF, on the other hand, 
there is no place in xcms where that would be used, so it would 
become relevant only in any downstream analysis. Yours, Steffen

**Comment by ZandkarimiF** [comment]
Thanks for the prompt response.
