### ISSUE TITLE
Chromatogram objects with sample subset selection

### ISSUE THREAD

**Issue by Tony-II** [sneumann/xcms#487]
Is it possible to pass an argument "sampleIndicees" for a sample subset selection when aquiring objects of class `Chromatograms` or `XChromatograms` for fuctions:

`chromatogram(object, rt, mz, aggregationFun = "sum", missing = NA_real_, msLevel = 1L, BPPARAM = bpparam())`

`featureChromatograms(x, expandRt = 0, aggregationFun = "max", features, include = c("feature_only", "all"), filled = FALSE, ...)`
  
This would be helpful for large and very large studies to only load a dedicated subset of samples from disk for visualisation purposes via these two above functions. Imagine a very large study (say > 100 or > 1000 samples) ... . Calling those functions are forced to load ALL samples without any given possibility to avoid that, if I assume right?

**Comment by jorainer** [comment]
Instead of specifying the index of the samples from which you want to extract the chromatogram you can first subset the object with `filterFile` (making sure to set parameter `keepFeatures = TRUE`). You can then call `chromatogram` or `featureChromatograms` on the subsetted object. This parameter was only recently added to `filterFile` so you might have to install `xcms` from github (`devtools::install_github("sneumann/xcms")`).

**Comment by jmorim** [comment]
MChromatogram objects aren't subsettable with filterFile. Is there another way to do this?

**Comment by jorainer** [comment]
`MChromatogram` objects actually contain values from only a single file (chromatogram). `MChromatograms` are supposed to contain data from multiple chromatograms and multiple files. The data is arranged in a matrix structure, rows are EICs (chromatograms with the same m/z and retention time range), columns samples. If `chroms` is an `MChromatograms` object you can get all chromatograms from e.g. the second file with `chroms[, 2]`.

I know, this isn't ideal as it is quite different from `Spectra` and `MSpectra`, but note that we started already with an alternative (more flexible) implementation with the [Chromatograms](https://github.com/rformassspectrometry/Chromatograms/) package, but development got stuck a while ago.
