### ISSUE TITLE
fillChromPeaks fails processing data

### ISSUE THREAD

**Issue by ZandkarimiF** [sneumann/xcms#497]
Hi,

I am trying to process LC-MS data using XCMS (3.11.3) in R version 4.0.1 on a UINIX server (Platform: x86_64-pc-linux-gnu (64-bit). I am using one of the cluster's high memory nodes (512 GB) with 24 processors.

When I get to fillChromPeaks function, it stops working. I have used the following codes but none of them work.
Thanks for your suggestions and help!

`register(SerialParam())
> xdata5 <- fillChromPeaks(xdata4)`
_Defining peak areas for filling-in .... OK
Start integrating peak areas from original files
Requesting 13024 peaks from 200526-BLANK-NEG-0101.CDF ... Killed_

`register(MulticoreParam(10))`
_Defining peak areas for filling-in .... OK
Start integrating peak areas from original files
Segmentation fault_

`register(MulticoreParam(2))
 xdata5 <- fillChromPeaks(xdata4)`
_Defining peak areas for filling-in .... OK
Start integrating peak areas from original files
Error in result[[njob]] <- value : 
  attempt to select less than one element in OneIndex
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
> srun: Exceeded job memory limit
srun: Force Terminated job 20107791
srun: Job step aborted: Waiting up to 32 seconds for job step to finish._

`registerDoParallel(2)
foreach(i=1:3) %dopar% sqrt(i)
 xdata5 <- fillChromPeaks(xdata4)`
_Segmentation fault (core dumped)_

--Fereshteh

**Comment by jorainer** [comment]
The `srun` tells me that you are running this through the SLURM queueing system on your cluster. To me this looks like you run out of memory. Did you request enough memory for your job (if I'm not wrong it is the `-m` parameter)?

**Comment by ZandkarimiF** [comment]
Thanks for your help! It works now.

Best,
Fereshteh

**Comment by jorainer** [comment]
I'm closing the issue now. Feel free to re-open if needed.
