### ISSUE TITLE
Warning message: Not a validObject(): no slot of name "extendLengthMSW" for this object of class "CentWaveParam"

### ISSUE THREAD

**Issue by jmorim** [sneumann/xcms#500]
```
warning messages from top-level task callback 'vsc.globalenv'
Warning message:
Not a validObject(): no slot of name "extendLengthMSW" for this object of class "CentWaveParam"
```
Occurs when loading xcms in RStudio at the start or if using VSCode, after every command is executed.
I'm assuming it's related to the change here:
https://github.com/sneumann/xcms/blob/bd047c5bc3460e6ba340d5bcb9de08af61e8a9bb/inst/NEWS#L55-L61

**Comment by jorainer** [comment]
I guess you updated `xcms` recently and load either an old R workspace or an R object created with `xcms` prior to version 3.9.4? Could you please specify when exactly you get the warning?

**Comment by jmorim** [comment]
I was getting it in VSCode every line but now I realize it's because it reloads my CentWaveParam into the workspace every time I open it.
Rerunning my script from the start in RStudio fixed it and rm(cwp) fixed it for VSCode.
