### ISSUE TITLE
Error: package ‘MSnbase’ 2.15.0 was found, but >= 2.15.3 is required by ‘xcms’

### ISSUE THREAD

**Issue by Mewozzz** [sneumann/xcms#501]
The whole package contains an older version of MSnbase, which doesn't work for the updated xcms.
> library(xcms)
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find, get,
    grep, grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position,
    rank, rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply, union, unique, unsplit, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with 'browseVignettes()'. To cite Bioconductor, see 'citation("Biobase")', and
    for packages 'citation("pkgname")'.

Loading required package: BiocParallel
Error: package ‘MSnbase’ 2.15.0 was found, but >= 2.15.3 is required by ‘xcms’

**Comment by sneumann** [comment]
Hi, I might need a bit more information what you exactly did. xcms does not "contain" an MSnbase. 
I would guess you have an existing R and BioC installation, and tried to install_github("xcms") on top of it ?
The error message indicates that the MSnbase found on your installation is too old for the xcms you tried to install.
Yours, Steffen

**Comment by jorainer** [comment]
The best practice to install `xcms` (to get the stable version) is through Bioconductor:

```
install.packages("BiocManager")
BiocManager::install(c("MSnbase", "xcms"))
```

**Comment by Mewozzz** [comment]
> Hi, I might need a bit more information what you exactly did. xcms does not "contain" an MSnbase.
> I would guess you have an existing R and BioC installation, and tried to install_github("xcms") on top of it ?
> The error message indicates that the MSnbase found on your installation is too old for the xcms you tried to install.
> Yours, Steffen

MSnbase is not updated with the xcms package, and there's no where to download MSnbase 2.15.3.
The current version is MSnbase 2.15.0.

BiocManager::install(c("MSnbase", "xcms"))
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'MSnbase', 'xcms'

  There is a binary version available but the source version is later:
        binary source needs_compilation
MSnbase 2.15.0 2.15.3              TRUE

  Binaries will be installed
trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/MSnbase_2.15.0.zip'
Content type 'application/zip' length 7450464 bytes (7.1 MB)
downloaded 7.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/xcms_3.11.4.zip'
Content type 'application/zip' length 6043749 bytes (5.8 MB)
downloaded 5.8 MB

package ‘MSnbase’ successfully unpacked and MD5 sums checked
package ‘xcms’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\zhong.198\AppData\Local\Temp\1\RtmpQ3FvX3\downloaded_packages
Installation path not writeable, unable to update packages: survival
Old packages: 'DelayedArray', 'MSnbase', 'multtest'
Update all/some/none? [a/s/n]: 
a

  There are binary versions available but the source versions are later:
             binary source needs_compilation
DelayedArray 0.15.4 0.15.7              TRUE
MSnbase      2.15.0 2.15.3              TRUE

  Binaries will be installed
trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/DelayedArray_0.15.4.zip'
Content type 'application/zip' length 2324875 bytes (2.2 MB)
downloaded 2.2 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/MSnbase_2.15.0.zip'
Content type 'application/zip' length 7450464 bytes (7.1 MB)
downloaded 7.1 MB

trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/windows/contrib/4.0/multtest_2.45.0.zip'
Content type 'application/zip' length 953901 bytes (931 KB)
downloaded 931 KB

package ‘DelayedArray’ successfully unpacked and MD5 sums checked
package ‘MSnbase’ successfully unpacked and MD5 sums checked
package ‘multtest’ successfully unpacked and MD5 sums checked

**Comment by jorainer** [comment]
In fact there is `MSnbase` 2.15.3 available but, as it says, not as a compiled (binary) version. If you have RStudio (I think) the compilers (aka Rtools) should also be available to install packages from source - please try to run the code from within RStudio and choose to install packages from source if possible. If this is not working you might need to install the Rtools, which you can download from https://cloud.r-project.org/ -> Download R for Windows -> Rtools.

**Comment by jorainer** [comment]
Closing this issue now. Feel free to re-open if needed.
