### ISSUE TITLE
get only the peaks that meet the "prefilter" criterion

### ISSUE THREAD

**Issue by mar-garcia** [sneumann/xcms#502]
Hi XCMS team!

I have noticed that during the chromatographic peak detection step with the `centWave` method, some of reported features do not always present "k" points with an intensity >= "I" counts [considering that the parameter "prefitler" is defined as follows: `prefilter = c(k, l)`].
@jorainer told me that `centWave` consists of 2 separate parts, the first to "detect the ROIs" (the regions of interest) where there might be a chromatographic peak and then the actual peak detection within each ROI; and that the prefilter is a setting for the first step.

So I was wondering if it might be possible to develop a new "postprocessing algorithm" (i.e., function) that removes chromatographic peaks that do not fullfill the `prefilter` criteria (i.e., remove all peaks that do not have "k" data points above "l" counts). Of course, if I can help on developing it I'm more than happy! ;) (just that I'm not able to develop it alone...).

Thanks!
Mar

**Comment by jorainer** [comment]
This is a little tricky as it requires the raw data to be imported for each chrom peak. I think of a way to do it in a not too slow way...

**Comment by jorainer** [comment]
The filter is implemented. To keep only peaks that have e.g. 3 intensities above 50000:

```r
xdata <- refineChromPeaks(xdata, param = FilterIntensityParam(nValues = 3, threshold = 50000))
```

You would have to install the github version of `xcms`:

```r
BiocManager::install("sneumann/xcms")
```

**Comment by mar-garcia** [comment]
Thanks @jorainer!!!! I'm going to update xcms and apply the new filter right now! :)

**Comment by jorainer** [comment]
Excellent. I'm closing this issue. Feel free to reopen if you encounter problems
