### ISSUE TITLE
issue # 479

### ISSUE THREAD

**Issue by MetabolomicsSA** [sneumann/xcms#509]
I'm reopening this issue to provide more info.
The error seems to pop up when installing xcms after a recent update (13th of September in this case) even after running BiocManager::install() and updating the packages . 
Also, the error only occurs when installing from Binaries.  When the package is installed from source everything runs fine.
Hope this is useful.
thanks

_Originally posted by @MetabolomicsSA in https://github.com/sneumann/xcms/issues/479#issuecomment-692449016_

**Comment by jorainer** [comment]
Closing this issue because it is a double post to #479
