### ISSUE TITLE
xcms version 3.3.1 

### ISSUE THREAD

**Issue by michael-vermeulen** [sneumann/xcms#513]
In an attempt to replicate previous results I require xcms v3.3.1
I'm having difficulty finding this version on bioconductor and bioconda. 

Is there a way I can download this version?

**Comment by jorainer** [comment]
The odd number in the version at position 2 (i.e. x.3.x) tells that that was a package from a developmental branch of Bioconductor. So, this version is not archived in BioC.
I checked the github history and in https://github.com/sneumann/xcms/commit/ec9fa9913f98bab4320ade4f0678ce8da36dda20#diff-35ba4a2677442e210c23a00a5601aba3 the version was bumped to 3.3.2, thus, the last code base in github with the version 3.3.1 is https://github.com/sneumann/xcms/commit/7bb2a11e27efd05b758f38f07474f33fae2f35c2#diff-35ba4a2677442e210c23a00a5601aba3.

You can install that version with 

```r
devtools::install_github("sneumann/xcms", ref = "7bb2a11e27efd05b758f38f07474f33fae2f35c2")
```

But be aware that you will also need other packages that match that old version (and ideally also an old version of R).

**Comment by michael-vermeulen** [comment]
thank you!

**Comment by jorainer** [comment]
Closing this issue now - feel free to reopen if needed @michael-vermeulen
