### ISSUE TITLE
FindchromPeaks issue

### ISSUE THREAD

**Issue by BaylorSci** [sneumann/xcms#517]
I recently updated both my R and Rstudio and so also updated my XCMS (3.11.7) [windows]. Re-running samples which have successfully run before for FindchromPeaks is returning the following error: 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'X' in selecting a method for function 'bplapply': No MS level 2 spectra present.

However, upon checking using table(msLevel(exp)) and confirming the return of ms1 and MS2, i'm lost in what could be happening. Centwave params where chosen based on optimization via the patRoon package and are within reasonable parameters of all prior successful runs. 
I've also noticed that loading time for my ms1 files have dramatically increased from 15 minutes to ~ 3 -4 hours and wondered whether there was a glitch/bug somewhere?
Any help would be greatly appreciated.

**Comment by jorainer** [comment]
Could you please provide a little more information providing also the code you use to load the data and to run the peak detection.

Also, please report the output of calling `sessionInfo()` in R.
