### ISSUE TITLE
fillPeaks.MSW-methods 

### ISSUE THREAD

**Issue by yuan596** [sneumann/xcms#520]
Hi,I have some questions about filling peaks.After peak grouping, the obtained matrix has many 'NA'.Can l fill the missing peak by the fillPeaks.MSW method ?

**Comment by jorainer** [comment]
In general, gap-filling (peak-filling) is performed after peak grouping (i.e. correspondence analysis).
Note that the `fillPeaks.MSW` function is part of the *old/original* `xcms` (these functions are no longer updated/maintained). It is highly suggested to use the `findChromPeaks`, `groupChromPeaks` and `fillChromPeaks` functions instead.

Also, the `MSW` method can only applied to direct injection data (i.e. not LC-MS data). If you have direct injection data, performed the peak detection with `findChromPeaks` with the `MSWParam`, then `fillChromPeaks` will automatically use the correct peak filling method (which corresponds to the `fillPeaks.MSW`).

**Comment by yuan596** [comment]
Thank you very munch！

**Comment by jorainer** [comment]
Closing this issue now - feel free to re-open if needed.
