### ISSUE TITLE
Request: filterPeaks() like method

### ISSUE THREAD

**Issue by rickhelmus** [sneumann/xcms#541]
Hey guys,

I got a (hopefully small) request to have a way to remove peaks from an `XCMSnSet` object, similarly as could be done with `xcms::peaks` with the old `xcmsSet` interface. My main use case is to synchronize objects with those from `patRoon`. For now `xcms:::.filterChromPeaks()` does the job, but not quite ideal since it's not exported ;-) Ideally, this would leave grouping (features) intact.

Thanks,
Rick

**Comment by jorainer** [comment]
Hi Rick! This is a very good suggestion indeed! I will make a `filterChromPeaks` method to allow filtering of peaks (and then obviously keeping the feature assignment correct).

**Comment by rickhelmus** [comment]
Excellent, many thanks!
