### ISSUE TITLE
there is no package called 'MsBackendMgf'

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#546]
Hi, currently we have a build error on 
http://bioconductor.org/checkResults/devel/bioc-LATEST/xcms/malbec2-buildsrc.html
due to a missing dependency:
```
Error: processing vignette 'xcms-lcms-ms.Rmd' failed with diagnostics:
there is no package called 'MsBackendMgf'
```
Despite the declaration in https://github.com/sneumann/xcms/blob/master/DESCRIPTION#L76
Yours, Steffen

**Comment by jorainer** [comment]
Answer from Lori:
 
> Currently the builders do not allow the user of remotes and you would have to wait for it to be submitted to CRAN or Bioconductor.  All Bioconductor dependencies must be on CRAN or Bioconductor. 

So, we need to submit the `MsBackendMgf` package to BioC.

**Comment by sneumann** [comment]
... and `dontrun` that section of the vignette for the time being. Yours, Steffen

**Comment by jorainer** [comment]
I've just submitted the package - let's hope it doesn't take too long...

**Comment by sneumann** [comment]
With the disabled vignette parts we're back to green. Thanks Jo, yours, Steffen
