### ISSUE TITLE
About exporting feature definition.

### ISSUE THREAD

**Issue by gmhhope** [sneumann/xcms#549]
Dear XCMS developer,

Thanks very much for the excellent tutorial of XCMS. 

I am looking through the tutorial but I cannot find a best practice to export the feature definition and feature table. I can easily export the matrix using `write.csv(featureValues(xdata, value = "into"), path2output)`. But using `write.csv` on `feature Definitions` create some strange organization of the column `peakidx`
[featureDefinitions_top_rows.csv.zip](https://github.com/sneumann/xcms/files/6139994/featureDefinitions_top_rows.csv.zip)

Could you help to answer this! I greatly appreciate your input.

Thanks,
Minghao Gong

**Comment by jorainer** [comment]
Actually, I would rather exclude the `"peakidx"` column before exporting:

```r
fts <- featureDefinitions(xdata)
write.csv(fts[, colnames(fts) != "peakidx"], ...)
```

The reason for the export problems are that the `"peakidx"` column is a `list` with the indices of the assigned chromatographic peaks and the `as.character` call on that during export is not formatting it correctly.

**Comment by gmhhope** [comment]
Thanks very much for the reply!

**Comment by jorainer** [comment]
I'm closing the issue now - feel free to re-open if necessary
