### ISSUE TITLE
Correspondence: parameters set-up

### ISSUE THREAD

**Issue by gmhhope** [sneumann/xcms#550]
Dear XCMS developers, 

This is the image of correspondence result with bw = 30; When I set a smaller bw values, the feature peaks can be distinguished.

However, I do want to know what will be the best practice for optimizing this value including many other critical correspondence parameters. Could you suggest anything?

Many thanks,
Minghao Gong

![image](https://user-images.githubusercontent.com/12982817/111661482-6d8ab700-87e5-11eb-946f-99b0d9e09a3e.png)

**Comment by jorainer** [comment]
I ususally extract chromatograms for m/z ranges where I know that compounds are either co-eluting or eluting one after the other and then tune the `bw` setting on those signals with the help of the `plotChromPeakDensity` function (trying to separate them as good as possible).

You can also have a look [here](https://github.com/jorainer/metabolomics2018) (or [here](https://jorainer.github.io/metabolomics2018/xcms-preprocessing.html) for the rendered version) for some additional explanations and examples.

**Comment by gmhhope** [comment]
Thanks very much! 

Oh I don't know there is a rendered version. I have already put your tutorial into Rmd myself. Thanks for letting me know. I will take a look at those! Thanks very much for your assistance!

Best,
Minghao Gong

**Comment by jorainer** [comment]
I'm closing the issue now - feel free to re-open if needed.
