### ISSUE TITLE
Warnings: Undocumented code objects

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#56]
Hi @Treutler, can you please address these:

```
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘findPeaks.centWaveWithPredictedIsotopeROIs’
Undocumented S4 methods:
  generic 'findPeaks.centWaveWithPredictedIsotopeROIs' and siglist
    'xcmsRaw'
```

as they lead to Warnings in https://bioconductor.org/checkResults/3.4/bioc-LATEST/xcms/zin1-checksrc.html
Thanks, Steffen

**Comment by jotsetung** [comment]
Was fixed a time ago - just feels good to close issues.
