### ISSUE TITLE
fillpeaks on data matrix

### ISSUE THREAD

**Issue by ccshao** [sneumann/xcms#580]
Hello, 
I would like to know how to fill the "0" in the lipidomimcs data, with only a data matrix.

Briefly, we got a data matrix from collaborators from our  LC-MS/MS experiments. It is a **compound id by sample** matrix, while the compound ids are in the format of "retentiontime_mz", like "10_1000m/z". The data is generated by **waters progenesis**. We know the groups of samples. 

In the matrix there are a few "0", we interpret them as missing value but no really "0".  Our collaborator suggest to try the `fillpeaks` in `xcms`. 

My question is, is it possible to do so with only a matrix, and how? What else info do I need to generate the xcmsSet in addition to the matrix?
Sorry for the quite basic question.

**Comment by jorainer** [comment]
The `fillChromPeaks` only works on an `XCMSnExp` which represents the raw data (i.e. data in the original mzML files) of an experiment as the algorithm *fills in* raw signal from these files. Without that you would need to impute missing values. There are various approaches to do that, but they are not implemented in `xcms`.

**Comment by ccshao** [comment]
Thanks for the update! Do you have some ideas on which imputation methods to choose? Actually I saw a few papers on this topic but am not sure how broadly their conclusions in those papers hold.

**Comment by sneumann** [comment]
Your best bet will be to test a few on your data for the kind of analysis you aim for. Yours, Steffen

**Comment by ccshao** [comment]
Thanks, I might try a few used for microarray studies.
