### ISSUE TITLE
findPeaks.massifquant returns different objects based on withWave setting

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#60]
The `findPeaks.massifquant` method for `xcmsRaw` object returns by default a `matrix`, but if `withWave = 1` it returns an `xcmsPeaks` object.
Given that all `findPeaks.*` methods return an `xcmsPeaks` object I think, to be consistent, we should change this behavior and always return an `xcmsPeaks` object (which in the end just extends `matrix` anyway).

**Comment by topherconley** [comment]
Good point. Thanks for finding that inconsistency. Brief inspection suggests that nothing should break with this change, although I have done no testing myself. If an `xcmsPeaks` object what I think it is, essentially a matrix with a names attribute, then I don't see any harm.

**Comment by jotsetung** [comment]
Thanks for looking into this!

Yes, the `xcmsPeaks` object is essentially a `matrix`, i.e. it extends `matrix`. So I'll fix the default to always return a `xcmsPeaks`.
