### ISSUE TITLE
Re: questions about some data processing parameters

### ISSUE THREAD

**Issue by JianFelixGuo** [sneumann/xcms#605]
Dear developer,

As a loyal user of XCMS, I usually use the default parameters for mzdiff = 0.01 and integrate = 1 in CentWave algorithm. I am wondering if I should change these 2 values based on certain criteria when I process different kinds of datasets. Do you have any experience of using different values for certain types of data? 

It would be greatly appreaciated if you could kindly enlighten me on these questions. Thank you!

Best,

Jian

**Comment by jorainer** [comment]
I don't have any clear rules on that. I'm usually using `integrate = 2` if the peaks have a long tail. With `integrate = 1` centWave assumes more *symmetric* peaks and cuts the tail. For `mzdiff` I usually use `mzdiff = 0.001` - but more out of a *gut feeling* (maybe your choice might be better).

**Comment by JianFelixGuo** [comment]
Thank you so much for the quick reply! I will try using your parameters.
