### ISSUE TITLE
this is a typo I think: `baseleve` :)

### ISSUE THREAD

**Issue by arabidopsis** [sneumann/xcms#623]
https://github.com/sneumann/xcms/blob/af3d030152198c653813fe0434634ed13f7d3a12/R/methods-xcmsRaw.R#L434

**Comment by sneumann** [comment]
Hi, well spotted ! The only reason this hasn't bitten us so far is a "feature" of R to lookup list elements by some matching, rather than exact name lookup:
```
> l <- list(first = "1")
> l$firs
[1] "1"
```
Nevertheless, will of course be fixed asap. 
Thanks for reporting, 
Yours, 
Steffen
