### ISSUE TITLE
 adjustRtime error-Error in `colnames

### ISSUE THREAD

**Issue by fengmingchen** [sneumann/xcms#626]
hello here
I am a newbie in learning and very grateful for your work.
  ```
> xset_g_r <- adjustRtime(xset_g, param = params$PeakAlign)
Error in `colnames<-`(`*tmp*`, value = basename(fileNames(object))[subs]) :  
Cannot set 'colnames' for objects with dimensions less than two
```
 The whole process is used in accordance with the XCMS tutorial, so I want to know where the problem is.

**Comment by fengmingchen** [comment]
`params$PeakAlign` <- PeakGroupsParam(smooth = "loess", span = 0.6, minFraction	= 0.9, family = "gaussian", extraPeaks = 3)
> xset_g_r <- adjustRtime(xset_g, param = params$PeakAlign) 
Performing retention time correction using 1 peak groups.
Error in do_adjustRtime_peakGroups(chromPeaks(object, msLevel = msLevel),  : 
  Not enough peak groups even for linear smoothing available!
In addition: Warning message:
In do_adjustRtime_peakGroups(chromPeaks(object, msLevel = msLevel),  :
  Too few peak groups for 'loess', reverting to linear method
> traceback()
5: stop("Not enough peak groups even for linear smoothing ", "available!")
4: do_adjustRtime_peakGroups(chromPeaks(object, msLevel = msLevel), 
       peakIndex = .update_feature_definitions(featureDefinitions(object), 
           rownames(chromPeaks(object)), rownames(chromPeaks(object, 
               msLevel = msLevel)))$peakidx, rtime = rtime(object, 
           bySample = TRUE), minFraction = minFraction(param), extraPeaks = extraPeaks(param), 
       smooth = smooth(param), span = span(param), family = family(param), 
       peakGroupsMatrix = pkGrpMat, subset = subset(param), subsetAdjust = subsetAdjust(param))
3: .local(object, param, ...)
2: adjustRtime(xset_g, param = params$PeakAlign)
1: adjustRtime(xset_g, param = params$PeakAlign)``

**Comment by sdauly532** [comment]
Hi, May I ask how do you fix this problem? I met the same error, Thanks!!!
