### ISSUE TITLE
What is the difference between ....?

### ISSUE THREAD

**Issue by linlennypinawa** [sneumann/xcms#631]
I got different outcomes while using the following two options.  What is the difference?
```
option#1:
xcmsSet(`file directory`)
```

```
option#2:
xcmsSet(`file directory`, method="centWave", fitgauss=FALSE, mzCenterFun="wMean",
                      ppm=10, peakwidth=c(5, 20), prefilter=c(3,100), mzdiff=0.01, snthresh=6, integrate=1, noise=100)
```
In option#2, the arguements are default.  

I thought I did not specify arguements in option#1, therefore I would expect the same outcome from both options.

**Comment by stanstrup** [comment]
default method is `"matchFilter"`.

**Comment by sneumann** [comment]
In addition, it is recommended to move forward to the XCMS3 interface with XCMSnExp and friends, and leave `xcmsRaw` and xcmsSet` behind. The latter are essentially unmaintained and have less functionality. Yours, Steffen

**Comment by sneumann** [comment]
Yes. Both the original `xcmsSet` classes/interface and the new `XCMSnExp` class are in the current xcms, but only the new interfaces  `XCMSnExp`  are actively under development. But that was just an additional suggestion on top of Jan's response above. In that case I think we can close the issue. Yours, Steffen
