### ISSUE TITLE
How to reach to .. with XCMSnExp data? 

### ISSUE THREAD

**Issue by linlennypinawa** [sneumann/xcms#634]
I used to load the data files to xcmsSet data container, and get to diffreport().  
Could you tell me the workflow with XCMSnExp data to get the same report?

**Comment by jorainer** [comment]
the `diffreport` is not available for `XCMSnExp` objects. With the updated workflow it's now suggested to call `quantify` on the results `XCMSnExp` which returns a `SummarizedExperiment` object (standard data container from Bioconductor) and then use any other tool or method to perform the statistical analysis. There are way better approaches available in R to do the statistical tests then `diffreport` did.

As alternative, there is still the possibility to convert the `XCMSnExp` to a `xcmsSet` object and then call the `diffreport` on that. To convert:

```r
xset <- as(xdata, "xcmsSet")
```

where `xdata` would be your `XCMSnExp` object.

**Comment by linlennypinawa** [comment]
Thank you

**Comment by jorainer** [comment]
One possibility would be Bioconductor's `limma` package - although it was developed originally for gene expression (microarray) data it works also good for metabolomics data. You can find the userguide [here](https://bioconductor.org/packages/release/bioc/vignettes/limma/inst/doc/usersguide.pdf)

**Comment by linlennypinawa** [comment]
> One possibility would be Bioconductor's `limma` package - although it was developed originally for gene expression (microarray) data it works also good for metabolomics data. You can find the userguide [here](https://bioconductor.org/packages/release/bioc/vignettes/limma/inst/doc/usersguide.pdf)

Fantastic!
