### ISSUE TITLE
Missing a few intensities information

### ISSUE THREAD

**Issue by ykim7263** [sneumann/xcms#635]
Dear All,

I was extracting chromatogram information (Rt, intensity) with Chrompeaks function.  And when I compared the extracted rt, the intensity of specific m/z with Chrompeaks function, there is some missing intensity information and shown as NA, which was shown as a real data point, when I checked the row data. I have attached some screenshots to help you understand.
[ss.pptx](https://github.com/sneumann/xcms/files/9471165/ss.pptx)

Best,

**Comment by jorainer** [comment]
I'm a little puzzled - you use `chrompeaks` in the example code (first slide) but then show `arginine_ms1_chr` which is a `XChromatograms` that is extracted with the `chromatogram` function. If I understand you are using the `chromatogram` function to extract the EIC and in that some of the mass peaks (for rt 41.869 etc) are missing.

Can you please provide the exact call you used to extract the chromatogram (please add that as text directly into the issue and not as a separate file/pptx)? Could be that the m/z range you used for the chromatogram extraction is different to the m/z range you used in the software to look at the raw data.

**Comment by ykim7263** [comment]
Sorry, I actually solved the problem, Please close it. Thank you
