### ISSUE TITLE
Build failure in two vignettes dims [product 50] do not match the length of object [10]

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#637]
Hi, we have a build failure on all architectures:
http://bioconductor.org/checkResults/devel/bioc-LATEST/xcms/
```
Quitting from lines 84-85 (LC-MS-feature-grouping.Rmd) 
Error: processing vignette 'LC-MS-feature-grouping.Rmd' failed with diagnostics:
error in evaluating the argument 'x' in selecting a method for function 'as.matrix': dims [product 55] do not match the length of object [11]
--- failed re-building ‘LC-MS-feature-grouping.Rmd’

--- re-building ‘xcms-direct-injection.Rmd’ using rmarkdown
Quitting from lines 176-177 (xcms-direct-injection.Rmd) 
Error: processing vignette 'xcms-direct-injection.Rmd' failed with diagnostics:
error in evaluating the argument 'x' in selecting a method for function 'as.matrix': dims [product 50] do not match the length of object [10]
--- failed re-building ‘xcms-direct-injection.Rmd’
```
I haven't checked details, but there is a suspicious factor of five in both cases when running:
https://github.com/sneumann/xcms/blob/a0e4c206b4c1f14f34f96282fe0f8dd1023a3917/vignettes/LC-MS-feature-grouping.Rmd#L84
and 
https://github.com/sneumann/xcms/blob/a0e4c206b4c1f14f34f96282fe0f8dd1023a3917/vignettes/xcms-direct-injection.Rmd#L176

Since last commit was 2022-04-26 I suspect that must be something in our dependencies. 
Yours,
Steffen

**Comment by jorainer** [comment]
Yes, I reported it already (https://github.com/Bioconductor/S4Vectors/issues/109) - it should be OK in the next couple of days.

**Comment by sneumann** [comment]
Confirmed, builds fine now. One warning left for a docs issue. Thanks Johannes, Yours, Steffen
