### ISSUE TITLE
Next Steps After Compounding (grouping)?

### ISSUE THREAD

**Issue by NotReallyContributing** [sneumann/xcms#638]
Hello,

I'm new to R and attempting untargeted metabolomics. I understand the Compounding (grouping) of LC-MS features does not yet aggregate the values but only defines the feature groups. Is this there anything one can do after defining the feature groups? Or should this function be ignored until the ability to aggregate the features per value is complete?

Kind regards.

**Comment by stanstrup** [comment]
I am not sure I understand your question. Grouping in the xcms sense tries to figure out which peaks are the same in the different samples. Thus creating features that you can extract in a feature/peak table. This has to be done to do anything with your data.

Grouping in the CAMERA sense tries to figure out which features are actually coming from the same compound (fragments/adducts).

I am not sure which one you are talking about or what you want to "do". What are you trying to achieve?
Maybe look through a tutorial like https://nexs-metabolomics.gitlab.io/INM/inm-booklet/0405_XCMS.html for a common workflow?

**Comment by stanstrup** [comment]
Yes, that procedure you link to is another implementation of the same idea as CAMERA.

So is what you are asking what to do after that step? Typically one would do statistics on all the features without regard for the feature groups. I am not aware of anyone condensing each feature group to a single variable; even though it would seem like a logical step it is difficult to find a good way to choose what the intensity should be on such a variable.

**Comment by NotReallyContributing** [comment]
So I should perform the statistics on all features without regard for the output of CAMERA or the implementation I linked? I'm concerned of falsely annotating signals as compounds when multiple arise from a single mother ion.

**Comment by stanstrup** [comment]
Yes, typically the statistics is done without regard for the grouping. You then consider it again when you do ID of course.

**Comment by NotReallyContributing** [comment]
Thank you for all of the guidance! I highly appreciate it.

**Comment by YonghuiDong** [comment]
> Yes, typically the statistics is done without regard for the grouping. You then consider it again when you do ID of course.

Hi @stanstrup, You mentioned that typically the statistics is done regardless of the grouping, which I think it is not a good practice. Too much redundant features will sacrifice the statistical power when you need to perform false positive correction. It will be better to perform statistics after deisotoping, and ideally use the precursor ion from each group for statistical analysis. 

Do you have any idea how to select the precursor ions from xcms after grouping?

Thanks,

Dong

**Comment by stanstrup** [comment]
That is the problem. You cannot know which is the "precursor" in a normal MS1 profiling experiment. You can try to guess; but you will often be wrong and sometimes the precursor/pseudo molecular ion is not the best representative (low intensity due to fragmentation etc). Hence I would rather sacrifice power than throw out stuff I don't know if is relevant.
Deisotoping you can do though. I doubt it practically makes a big difference.
