### ISSUE TITLE
Filter out one mz

### ISSUE THREAD

**Issue by linlennypinawa** [sneumann/xcms#649]
I have an idea of cleaning up mz data by removing 'weeds'.  They could be interferences.  I read `methods-XCMSnExp.R` file.  It seems to me the default `filterMz()` is `range(mz)`. 

Is it by any chance I could use filter() in R with between(), and logic functions, like `|` ,`&`, or `!=`?

The work around solution would be: extract spectrum data, manipulate mz data, and put back to MSnExp.  Is it correct?

**Comment by jorainer** [comment]
No, `xcms` does not support `between` or `filter` and logic operations for filters. The only available filter for now is `filterMz` as you already found and specifying an upper and lower m/z keeping all peaks with m/z within these.

The next large update of `xcms` will use the [Spectra](https://github.com/RforMassSpectrometry/Spectra) package for MS data representation. So, in future there might be better and more powerful filters available.
