### ISSUE TITLE
worker failed with the error: wrong args for environment subassignment (xcMSnExp obj)

### ISSUE THREAD

**Issue by Pembs** [sneumann/xcms#657]
Hello, 

I'm running the xcms workflow and having issues when getting to the rt alignment stage, I have version 3.2 xcms.  Please see below my code;

raw_data <- readMSData(files = paths, pdata = new("NAnnotatedDataFrame", PD_pos),
                       mode = "onDisk", msLevel.=1, centroided. = T)

high <- filterMz(raw_data, mz = c(1000, 2300))
high <- filterEmptySpectra(high)

#pick
xcms1 <- findChromPeaks(high, param = CentWaveParam(ppm=6, peakwidth=c(5,45), snthresh=10, noise=15000, prefilter=c(3, 1000),  mzdiff=0.05, fitgauss=TRUE))

#rt alignment 
xcms2 <- adjustRtime(xcms1, param = ObiwarpParam()) gets the error of ...

 worker failed with the error: wrong args for environment subassignment

Error: BiocParallel errors
  1 remote errors, element index: 3
  365 unevaluated and other errors
  first remote error:
Error in socketConnection(port = port, server = TRUE, blocking = TRUE, : cannot open the connection

Please could you tell me how I would overcome this?

**Comment by Pembs** [comment]
disabling parallel processing worked for this issue 

register(SerialParam())

**Comment by jorainer** [comment]
Thanks for updating and closing the issue. Yes, seems that somehow parallel processing is not possible on your system/settings. I guess it's Windows - what might help is restarting R or even the computer to get it working again - or to be on the "safe side" and use `SerialParam()` to disable completely.
