### ISSUE TITLE
Handling multtest dependency (BioC build error)

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#671]
Hi, I think we have leftover historic misuse in our dependency handling. 

In the old days, we avoided bloating dependencies, because some default behaviour was to recursively install all `Suggest`ed packages, and e.g. `multtest` pulled in a lot of that. So, we have 

https://github.com/sneumann/xcms/blob/fcab3c6b00de176fd7613f6c290f0b2469756af7/R/methods-xcmsSet.R#L1565

Which in turn triggers a build error on BioC builds with new R-devel (r83996)
Error report on https://master.bioconductor.org/checkResults/3.17/bioc-LATEST/CAMERA/nebbiolo1-checksrc.html
```
  Test files with failing tests:
     test_annotateDiffreport.R 
       test.annotateDiffreport.calcCaS 
       test.annotateDiffreport.calcCiS 
       test.annotateDiffreport.calcIso 
       test.annotateDiffreport.graphMethod 
       test.annotateDiffreport.intval 
       test.annotateDiffreport.pval 
...  
Error in .local(object, ...) : 
  The use of 'diffreport' requires package 'multtest'. Please install with 'Biobase::install("multtest")'
```

**Comment by jorainer** [comment]
two solutions:

- change the code from `diffreport` to use `p.adjust` instead.
- add `multtest` to *Suggests*.

I would prefer solution 1 as I don't see why we should need/use the `multtest` package at all?

**Comment by jorainer** [comment]
So, `multtest` is already in `Suggests` - so it should work. Note that I've seen recently also dependency problems for other packages on that particular build system. Maybe it might also be related to something not working properly on that build server?

**Comment by jorainer** [comment]
Seems to have resolved itself.
