### ISSUE TITLE
Two overlapping peaks with the same m/z detected as one

### ISSUE THREAD

**Issue by MonicaCalSan** [sneumann/xcms#674]
Hi! We are trying to integrate a sample in which two isomers appear too close, so that peaks are overlapped. The problem is that, even if the two peaks can be visualize clearly, they are integrated together. We have tried centwave and other param options, modified snthreshold, peak width, and a lot of other parameters, but without success. Someone here with a similar issue knows how to solve this question?
Here is the chromatogram with the two peaks:
![Overlapped peaks 20572](https://github.com/sneumann/xcms/assets/92379607/0e27217b-0efd-4580-ae39-aea85ead512a)

**Comment by jorainer** [comment]
reducing the `peakwidth` (lower and upper value) did not help? maybe also try in combination with `integrate = 2` and `extendLengthMSW = TRUE`?

**Comment by MonicaCalSan** [comment]
Thanks a lot, it works!!!
