### ISSUE TITLE
Introduce a changelog

### ISSUE THREAD

**Issue by hechth** [sneumann/xcms#680]
Would it be possible to start using a changelog according to semver2?

The XCMS Galaxy tools for example are version 3.12 and bioconductor hosts 3.22 but it is not possible to find out which features were added or what changed in a straightforward manner.

**Comment by sneumann** [comment]
Could you be more specific ? There is https://github.com/sneumann/xcms/blob/devel/inst/NEWS
which shows the versions and changes. Could you pick an example from there how that should look like ? 
Yours, Steffen
