### ISSUE TITLE
Build error invalid class "MsBackendMzR" object: slots not in object: "peaksVariables"

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#690]
Hi,
we have an error in https://bioconductor.org/checkResults/3.18/bioc-LATEST/xcms/nebbiolo2-buildsrc.html
```
Quitting from lines 70-75 [load-data] (LC-MS-feature-grouping.Rmd)
Error: processing vignette 'LC-MS-feature-grouping.Rmd' failed with diagnostics:
invalid class "MsBackendMzR" object: slots in class definition but not in object: "peaksVariables"
```
Yours, Steffen

**Comment by jorainer** [comment]
Should be fixed by this commit: https://github.com/sneumann/xcms/commit/25b6326750f5be2fe08d370e87610d205a83e382

**Comment by jorainer** [comment]
Fixed now. All green on BioC.
