### ISSUE TITLE
Suggested starting parameters for GC-MS data

### ISSUE THREAD

**Issue by ckeeling** [sneumann/xcms#720]
Can you suggest starting parameters for GC-MS data?

**Comment by jorainer** [comment]
For which algorithm(s)? I've never worked with GC-MS data, but I would suggest to try/check the code in the [xcms tutorials](https://jorainer.github.io/xcmsTutorials/articles/xcms-preprocessing.html#chromatographic-peak-detection) related to chrom peak detection maybe?

**Comment by sneumann** [comment]
Also depends on your instrument and settings. The W4M team also has great tutorials using xcms behind the scenes https://workflow4metabolomics.org/howto, including https://download.workflow4metabolomics.org/docs/w4e2018/2018-10_EC_W4E%20-%20MSprocessing_GC-MS_processing.pdf
Yours, Steffen

**Comment by ckeeling** [comment]
Thanks @sneumann, the pdf link is broken but @yguitton is now aware of this, and directed me to additional information, including [metaMS](https://github.com/yguitton/metaMS) and the [metaRbolomics Toolbox](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6835268/).
