### ISSUE TITLE
Bad practices with peak merging

### ISSUE THREAD

**Issue by jmorim** [sneumann/xcms#724]
This has always bothered me in the vignette. These are two distinct chromatographic peaks that happen to share an m/z, so probably isomers. Why does the vignette suggest merging the two peaks?

https://github.com/sneumann/xcms/blob/48ac5e0cd983b34437719063d1327c452f2d29af/vignettes/xcms.Rmd#L485C1-L496C1

**Comment by jorainer** [comment]
that's a fair comment. this is just an example to show how such peaks _could_ be joined, we don't say the _should_ be. This is just to illustrate the effect of the `minProp` parameter. I will update the vignette to make it more clear.

**Comment by jorainer** [comment]
I've updated the description in the vignette now. Thanks for the feedback!

Feel free to reopen the issue if further changes are necessary
