### ISSUE TITLE
msLevel=2L chromatograms (MRM or SRM) not working with MsExperiment interface

### ISSUE THREAD

**Issue by jmorim** [sneumann/xcms#725]
Data is an mzML converted from an Agilent 6495 triple quad, run in dynamic MRM mode
```
data = readMsExperiment(file)
spectra(data)
#      msLevel     rtime scanIndex
#    <integer> <numeric> <integer>
#1           2    93.051         1
#2           2    93.304         2
#3           2    93.556         3
chromatogram(data) |> plot()
```
all chromatograms empty
```
chromatogram(data, msLevel=2L) |> plot()
```
all chromatograms empty

might be something obvious i'm missing but the readMsData interface worked.

**Comment by jorainer** [comment]
we did not (yet) update the code to import/handle MRM/SRM data. for chromatographic data we're still using/relying on the `MSnbase` package - until we proceed with the [Chromatograms](https://github.com/RforMassSpectrometry/Chromatograms) package - but that will still take some time.

I will close the issue, feel free to reopen if needed.
