### ISSUE TITLE
Combine / split xcmsSets, RT correction is not discarded

### ISSUE THREAD

**Issue by mheiser-md** [sneumann/xcms#75]
According to the manual grouping and retentiontime data is discarded.  I'm not sure if this is a misunderstanding, but I found that the rt corrected slot remains the same:

``` r
library(xcms)
library(faahKO)

### perform retcor
xs <- group(faahko)
xs <- retcor(xs)

### RT is corrected and differs from "original" data
all.equal(faahko@rt$corrected, xs@rt$corrected) # FALSE

### now split xs in WT and KO
xss <- split(xs, xs@phenoData$class)

### the rt correction is maintained after the split
all.equal( xss[[1]]@rt$corrected,  xs@rt$corrected[1:6]) # TRUE

### combine data
xsc <- Reduce(c, xss)

### RT correction remains the same
all.equal( xsc@rt$corrected,  xs@rt$corrected) # TRUE
```

the group information is discarded, but I would have expected that the rt$corrected were the same as in the rt$raw slot after splitting/ combining.

**Comment by sneumann** [comment]
Hi, indeed, well spotted. Corrected RTs should be discarded if the context (grouping) in which they were corrected is also gone. Yours, Steffen

**Comment by mheiser-md** [comment]
Hi Steffen, 
thank you for your feedback. The current behavior is funnily the one I was trying to achieve. On a related note, how do you see the filled peaks during split/ combine?. Should they be discarded too, as they also stem from the grouping context?

Best,
Michael

**Comment by sneumann** [comment]
The actual reason behind split() was to run one huge xcmsSet() on all files in a study, 
which is the most time-consuming step, and save()ing that to disk. Then, subsequent 
analysis can be done on any re-combination of the xcmsSet()s. A downside of also discarding fillPeaks()ed intensities is that they'd then rely on the other files grouped with it. Difficult decision.

**Comment by jotsetung** [comment]
What about adding an argument `dropGrouping`, `dropRt` etc to enable the user to decide what to discard and what to keep?

**Comment by jotsetung** [comment]
Be aware that for removing the adjusted retention times in an `xcmsSet` object is not that simple - rt adjustment does not only add the adjusted retention times to `@rt$corrected`, but does also change the rt reported in the `@peaks`.
Here I would like to point to the new user interface and classes in the `xcms3` branch that are able to handle this correctly. For the new `XCMSnExp` object there are methods `dropAdjustedRtime` available that remove the adjusted retention times AND revert the rts reported for the features/peaks.
To be consistent, subsetting will for `XCMSnExp` however almost always drop all results, except the detected features (peaks).

**Comment by jorainer** [comment]
The new classes and functions allow to specify whether or not adjusted retention times should be kept or dropped.
