### ISSUE TITLE
Peak mz values when running findChromPeaks on XChromatograms object

### ISSUE THREAD

**Issue by CLUES-Emory** [sneumann/xcms#765]
Hello,
Currently, mz values are dropped when running findChromPeaks on XChromatogram objects, even if the mz range for an XIC is included when defining the XChromatogram option. This is leading to some issues when we are detecting peaks and running correspondence analysis across multiple samples (we are creating XChromatograms from XICs generated in the rawrr package). Is there anyway to include the XChromatogram mz values (and/or the provided range) in the peak tables generated from XChromatograms objects? Thanks!

**Comment by CLUES-Emory** [comment]
Ah, just realized the feature definitions return the row number of the chromatogram, which allowed me to link back to the original mz and resolves the issue above.

**Comment by jorainer** [comment]
thanks for reporting! Actually, this is a very interesting issue - indeed, reporting the m/z values in the `chromPeaks()` matrix if that information is provided/stored in the `XChromatograms` would be an interesting information.

**Comment by jorainer** [comment]
btw, with the commit linked above I'm also reporting the chromatogram's m/z in the `chromPeaks()` matrix.
