### ISSUE TITLE
Parameters change from xcms2 to xcms3 (profStep, mzwid)

### ISSUE THREAD

**Issue by VinzentRisch** [sneumann/xcms#782]
I am currently trying out IPO for parameter optimisation. 
I have seen that IPO is still using the older xcmsset object for the optimisation. But i would like to use the optimized parameters with the newer XCMSsExp object and the newer functions.
I have seen that for the peak picking  all parameters stay the same and I am assuming that they can be used for the older and the newer functions interchangeably.
But for alignment with obiwarp and correspondence with density there are two parameters that changed. In obiwarp its profStep to binsize and in density its mzwid also to binsize.
I wanted to ask if these parameters were just renamed and can be used interchangeably or if they describe something entirely different.

**Comment by jorainer** [comment]
we renamed both parameters to `binsize` to have more consistent parameter names. They have the same meaning.

**Comment by VinzentRisch** [comment]
Okay, thank you!

**Comment by sneumann** [comment]
Hi, does that mean IPO can expect a pull request at some later stage :-) ? I know an eMail if there is no immediate response, but it wouldn't hurt to keep it alive. Yours, Steffen
