### ISSUE TITLE
Add a *do* function for findPeaks.centWaveWithPredictedIsotopeROIs

### ISSUE THREAD

**Issue by jotsetung** [sneumann/xcms#82]
Actually, it might be good to split the functionality and implement a `do_findPredictedIsotopeROIs` function that does the ROI detection which can then be fed into the `centWave` method.

**Comment by sneumann** [comment]
@HendrikTreutler, do you think that is feasible ?
Yours, Steffen

**Comment by Treutler** [comment]
I think this is reasonable and feasible. I will have a look at that soon.
Best, Hendrik

**Comment by jotsetung** [comment]
That would be awesome - check out the `xcms3` branch and have a look at *do_detectFeature-functions.R*. The `do_detectFeatures_massifquant` is somewhat similar as it uses `do_findKalmanROI` to find the regions of interest and feeds that to the `do_detectFeatures_centWave`. In your case I think it would be possible to define a `do_detectPredictedIsotopeROIs` function that returns a list of ROIs.

**Comment by Treutler** [comment]
please find pull request #88 as a proposal to this issue
