### ISSUE TITLE
centWave: debug me: (omz == 0)?

### ISSUE THREAD

**Issue by stanstrup** [sneumann/xcms#90]
I am trying to do some targeted peak picking manually inputting an ROI.list.

But I end up with `centWave: debug me: (omz == 0)?`
-->
https://github.com/sneumann/xcms/blob/4b2458e54e11a874fd5a0ce42cfb4d4e475a2865/R/methods-xcmsRaw.R#L420

I guess this happens when there is nothing in the mz/rt range?
Any work-around for this?

**Comment by jotsetung** [comment]
Yes, looks like it stops when there is no data in that mz/rt range. 
I'm wondering what happens if instead of `stop` a simple `next` would do it too, i.e. just skipping that ROI and moving to the next one.

**Comment by stanstrup** [comment]
Thanks. That seems to work. In that I get an empty table.
Does it need to find a peak in the range or should there just be data? Because it seems it errors even if the range has some spikes.

**Comment by stanstrup** [comment]
Seems the recent merging of the xcms3 branch reverted this. Do I make a new pull request?

**Comment by jotsetung** [comment]
Sorry my fault. You fixed the original findPeaks.centWave method that I replaced with the `do_*` function. I'll fix in the xcms3 branch, so next time Steffen merges it will be included.

**Comment by jotsetung** [comment]
OK, it's now (since https://github.com/sneumann/xcms/commit/95f5c30fdd727e0419de928553121d204e032ae4) in `xcms` branch. Will be in devel once Steffen merges.
