### ISSUE TITLE
incorrrect indexing getEIC function

### ISSUE THREAD

**Issue by WMBEdmands** [sneumann/xcms#92]
Hi we noticed an indexing error in the xcmsSet "getEIC" method.
On line 1397 of https://github.com/Bioconductor-mirror/xcms/blob/release-3.4/R/methods-xcmsSet.R
`lcraw <- getXcmsRaw(object, sampleidx=i, rt=rt)`
should be
`lcraw <- getXcmsRaw(object, sampleidx=sampidx[i], rt=rt)`
We noticed when supplying the names of samples or an integer to the groupidx argument of the getEIC function that the getXcmsRaw function was printing incorrect sample names to the console.

**Comment by jotsetung** [comment]
Thanks for the info, I'll investigate. Actually I thought we fixed that.

**Comment by jotsetung** [comment]
Indeed the indexing was wrong. I've fixed it and added a corresponding unit test in commit https://github.com/sneumann/xcms/commit/02444fdc4f3e2264d7ff85e7320e9df955969379 (in current _devel_ branch). @sneumann could you push that to Bioconductor 3.4 (current stable) too?

@WMBEdmands thanks for reporting the bug! just as an info, we're currently modernizing `xcms`, so in future there might be some bigger changes.

**Comment by WMBEdmands** [comment]
Hi Johannes,
I would be very happy to help with the xcms project although I doubt you need any. I think I would greatly benefit from the experience. I'm not sure if any fundamental/big changes are needed as it is already a great package.
