### ISSUE TITLE
How to use xcms3 from bioconductor

### ISSUE THREAD

**Issue by fcyu** [sneumann/xcms#95]
Is xcms installed from bioconductor xcms3? If not, how to import xcms3 into R?

Thanks

**Comment by sneumann** [comment]
Hi Fengchao, 
yes, changes from xcms3 are available from the 
BioC devel branch at http://bioconductor.org/checkResults/devel/bioc-LATEST/xcms/ . 
I just merged a bunch of changes into the the upcoming 
xcms-1.51.3 and later.
Yours, Steffen

**Comment by jotsetung** [comment]
Alternatively you could install the _xcms3_ branch directly from github using the `devtools` package: `install_github("sneumann/xcms", ref = "xcms3")` - but be aware that the code is not stable yet.

**Comment by fcyu** [comment]
Thanks a lot.
