### ISSUE TITLE
MTBLS2 build failure: 'rtrange' number 1 (-89.417, 130.583) is outside of the retention time range of 'object'

### ISSUE THREAD

**Issue by sneumann** [sneumann/xcms#99]
Reported by Valerie Obenchain:
http://www.bioconductor.org/checkResults/3.5/data-experiment-LATEST/mtbls2/malbec2-buildsrc.html

```
Error: processing vignette 'MTBLS2.Rmd' failed with diagnostics:
'rtrange' number 1 (-89.417, 130.583) is outside of the retention time range of 'object'
```
Yours, Steffen

**Comment by jotsetung** [comment]
Apparently the checks that I introduced into the `getEIC` and `profMat` methods triggered. The extension of the retention time window by 100 secs in both directions resulted in these negative retention times. I will add a fix to the `getEIC` method that ensures that the provided `rtrange` are within the rt range of the object - or throws the error if both, the lower and the upper boundary are outside.

**Comment by jotsetung** [comment]
It's in commit https://github.com/sneumann/xcms/commit/48055c072e5589fa2fd3351b5a14de0b5bbc3a9b#diff-b04c69d32c3ee3891f92cab482473dfd in the xcms3 branch - somehow I failed/forgot to make a dedicated commit for that one fix :(

**Comment by sneumann** [comment]
Fix is on BioC svn. Yours, Steffen
